### ISSUE TITLE
[Tarea 1] Parte2.1 cambios permitidos

### ISSUE THREAD

**Issue by Aloncarrasco** [UC-IIC2613/Syllabus#10]
Hola en esta parte tengo que solucionar un código, pero que pasa si lo soluciono sin usar count?
además que tanto puedo cambiar estas lineas:
camino(X,Y,Largo) :- arco(X,Y), Largo=1.
camino(X,Y,Largo) :- camino(X,Z,L1), camino(Z,Y,L2), Largo=L1+L2.

puedo elminarlas o cambiar las condiciones que  tienen?

**Comment by FeBalla** [comment]
Con respecto a la primera duda, el uso de `#count` es **obligación** para esta pregunta, aunque existan otras maneras de resolverlo, ya que la idea es que investiguen en el libro y comprendan el manejo del operador. En cuanto al cambio de los predicados de las líneas que mencionas, **no deben cambiarlas**, ya que la idea es que entiendan qué ocurre con esas definiciones en particular  al añadir un ciclo y lo expliquen.
**[EDIT]** La idea es que luego definan su propio predicado para calcular el largo de un camino y que usando `#count` sea capaz de hacerlo para cualquier grafo (con o sin ciclos).

**Comment by vchadwick** [comment]
`[EDIT] La idea es que luego definan su propio predicado para calcular el largo de un camino y que usando #count sea capaz de hacerlo para cualquier grafo (con o sin ciclos).`
@FeBalla solo para confirmar, podemos cambiar las lineas para la **segunda parte de la pregunta**, es decir, para ayudarnos a encontrar los ciclos y definir despues nuestros propios predicados?

**Comment by FeBalla** [comment]
> `[EDIT] La idea es que luego definan su propio predicado para calcular el largo de un camino y que usando #count sea capaz de hacerlo para cualquier grafo (con o sin ciclos).`
> @FeBalla solo para confirmar, podemos cambiar las lineas para la **segunda parte de la pregunta**, es decir, para ayudarnos a encontrar los ciclos y definir despues nuestros propios predicados?

Para **la segunda parte** de esa pregunta sí pueden modificarlo
