### ISSUE TITLE
[Tarea 2][Pregunta 1.4] Duda sobre open

### ISSUE THREAD

**Issue by FelipeLara00** [UC-IIC2613/Syllabus#100]
Hola!
Tengo 3 dudas sobre está parte:
1.- La open se ordena sola de menor a mayor?
2.- El empate se puede dar entre 2 o más nodos? O solo entre 2?
3.- El método extract() elimina de la open al nodo extraído?

Espero se entiendan las preguntas.
Gracias!

**Comment by diegomendieta** [comment]
Hola Felipe, 

1. Sí, la Open es un Binary Heap, una estructura de datos que corresponde a un árbol binario usada para implementar colas ordenadas en base a algún criterio (en este caso, la función f, con el nodo de menor valor a la cabeza). Si no te suena, no te preocupes; lo vas a ver en el curso Estructuras de Datos y Algoritmos.

2. Sí, se puede dar entre más de 2 nodos. El razonamiento es análogo al caso de empate entre 2 nodos.

3. Sí, el método extract saca al nodo del heap.

**Comment by FelipeLara00** [comment]
Perfecto muchas gracias!!
