### ISSUE TITLE
[Tarea 2] [Pregunta 1.4]

### ISSUE THREAD

**Issue by Christian-Klempau** [UC-IIC2613/Syllabus#101]
Hola!
En la parte 1.4 se pide comparar "esta regla de desempates" (supongo que refiriendose a la regla de la parte 1.3) y luego comparar la diferencia en rendimiento, pero no me queda claro con qué lo debo comparar:
- g ineficiente vs g **eficiente**
- g ineficiente vs implementación normal
- g **eficiente** vs implementación normal

Gracias!

**Comment by diegomendieta** [comment]
Hola Christian, debes comparar la situación "correcta" (en que el primer nodo que sacas de la Open, entre todos aquellos que tienen el menor valor de f, es aquel que tiene el mayor valor de g) con la situación incorrecta (en que, entre todos aquellos nodos que tienen el menor valor de f, eliges sacar de la Open aquel que tiene el menor valor de g). Si corres A* con esas dos situaciones, te vas a dar cuenta que una se demora bastante más que la otra, ya que hace exponencialmente más expansiones. Éxito!

**Comment by Christian-Klempau** [comment]
Genial, me quedó claro! Gracias!!

**Comment by Brocoleta** [comment]
> Hola Christian, debes comparar la situación "correcta" (en que el primer nodo que sacas de la Open, entre todos aquellos que tienen el menor valor de f, es aquel que tiene el mayor valor de g) con la situación incorrecta (en que, entre todos aquellos nodos que tienen el menor valor de f, eliges sacar de la Open aquel que tiene el menor valor de g). Si corres A* con esas dos situaciones, te vas a dar cuenta que una se demora bastante más que la otra, ya que hace exponencialmente más expansiones. Éxito!

Hola, esa situacion que se demora bastante mas, cuanto tiempo mas es? Por que lo estoy corriendo y no me corre ni siquiera el primer test, nose si estamos hablando de tiempos de media hora o mas, o tal vez tengo malo el codigo
