### ISSUE TITLE
[Tarea 2][Pregunta 3.1]

### ISSUE THREAD

**Issue by Huasito-Appel** [UC-IIC2613/Syllabus#103]
Hola! resulta que no estoy entendiendo muy bien como funciona num_pref y out_of, pense que era un estimado en terminos de % de cuantas veces escogeremos los nodos en preferred sobre la open, sin embargo al intentar con % que yo pensaba "iguales" me arroja resultados distintos.
iguales entendiendo con que poseen la misma relacion, num_pref/out_of , como por ejemplo :
4-10, 
0.4-4 ,
40-100
Por si me pueden orientar algo o por el contrario es parte de la pregunta.
Quedo atento, gracias de antemano.

**Comment by jcechavarri** [comment]
Hola!

No es exactamente como mencionas, si bien los porcentajes finales deberían ser aproximadamente `num_pref / out_of` y `1 - (num_pref / out_of)`, tienes que fijarte bien cómo se estan extrayendo los elementos de las listas. Asumamos que `self.preferred` y `self.open` tienen suficientes elementos para no quedarse vacías. 
Luego la parte del código que importa para ver de donde se extrae el siguiente elemento es:

```python
elif counter % self.out_of < self.num_pref:
    queue = self.preferred
    self.preferred_extractions += 1
else:
    queue = self.open
    self.open_extractions += 1
```

Ahora tomemos el ejemplo que das; 4-10. Cuantas veces se va a cumplir que `counter % 10 < 4` antes de que empecemos a extraer de la open?

Tomando otro ejemplo "equivalente"; 40-100, ese número cambia o se mantiene igual??

Espero que con eso puedas responder tu pregunta, cualquier duda que te quede por favor escribe nomas! 😄

**Comment by Huasito-Appel** [comment]
Gracias, me quedo mas claro ahora esta parte, aun tengo un par de duas respecto al caso borde en donde num_pref = out_of.
Adicionalmente para esta parte, podemos realizar el analisis sobre una cantidad fija de problemas? o tenemos que hacerlo sobre todos.
Grcias de antemano.

**Comment by jcechavarri** [comment]
Con respecto al caso borde que mencionas, analiza el caso dónde `counter % num_pref < num_pref` (que siempre se cumple). Entonces, en ese caso siempre se extraerá de `self.preferred` a menos que esté vacía.

En cuanto a tu segunda duda, te recomiendo que lo corras con todos los problemas, así obtienes una mayor representatividad. Recuerda que puedes poner un límite de tiempo para que no se te demore tanto!
