### ISSUE TITLE
Control 18

### ISSUE THREAD

**Issue by CataAlamos** [UC-IIC2613/Syllabus#104]
Hola, no me quedo claro si estamos cambiando los valores de x,y,z o a,b,c,d de la pregunta del control. ¿Alguno de esos valores son constantes en la función? En otras palabras, ¿No me queda claro que estamos estudiando?
¿Me lo pueden clarificar? 
Muchas gracias
<img width="647" alt="Screen Shot 2021-05-21 at 09 43 09" src="https://user-images.githubusercontent.com/62016215/119146945-21443900-ba19-11eb-99dd-cbdb87eeeb76.png">

**Comment by Jamidd** [comment]
Hay un grupo de variables que son las que definen la función y por ende forman el espacio de hipótesis. Esas son los que estamos buscando. 
Saludos, 
Jaime
