### ISSUE TITLE
[Tarea 2] 1.4 Aclaración del código entregado

### ISSUE THREAD

**Issue by CataAlamos** [UC-IIC2613/Syllabus#105]
Hola, en la línea 52-53 del astar.py se hace 
`path_cost = n.g + cost  # costo del camino encontrado hasta child_state
 if is_new or path_cost < child_node.g:`
Quiero clarificar que entendí bien el código. No estoy del todo segura si n es otro child del nodo parent que comparamos con otro nodo child. Por ejemplo, el nodo parent sería a y sus hijos c y b 
  /c
a
  \b
¿Entonces n y child_node son c y b?

**Comment by ebrzovic** [comment]
n es el nodo que tú extraes para el open. Es el nodo padre con quien tú trabajas para expandirlo creando sus hijos (siempre y cuando no te encuentres en el objetivo). Entonces cuando calculas el path_cost, el n.g corresponde al costo del nodo n, cuanto ha recorrido el nodo padre desde el comienzo, y a eso le sumas el costo que toma avanzar desde el padre hasta el child_node.
