### ISSUE TITLE
[Tarea 2][Parte 2] light_manhattan

### ISSUE THREAD

**Issue by josejimenezp** [UC-IIC2613/Syllabus#106]
Hola, quería saber si es que la heurística que debemos implementar en la pregunta 2 tiene que ser mejor en términos de número de expansiones y tiempo de ejecución que manhattan_div_15, o no es necesario?

**Comment by SarahEverke** [comment]
Hola,
no es necesario que sea mejor en lo que mencionas. Lo importante es que sea admisible para el problema.

**Comment by josejimenezp** [comment]
Y tengo otra duda, con la heurística manhattan_div_15 me da esto:
![image](https://user-images.githubusercontent.com/48298035/119243813-42e81200-bb38-11eb-8c0a-0cc4ca4f3dbb.png)

Mientras que con mi heurística me da esto:
![image](https://user-images.githubusercontent.com/48298035/119243819-4a0f2000-bb38-11eb-9254-bf51ddcf7f71.png)

Quería saber si los 0.99 son un problema o no, ya que con el mismo manhattan dividido 15 hay un 0.98. De antemano muchas gracias!
