### ISSUE TITLE
[Tarea 2][1.4 "Mejora"]

### ISSUE THREAD

**Issue by CataAlamos** [UC-IIC2613/Syllabus#107]
Hola, ¿Cuando se dice que presentamos una ‘versión mejorada’, necesariamente se refiere a tiempo?
<img width="477" alt="Screen Shot 2021-05-23 at 14 57 54" src="https://user-images.githubusercontent.com/62016215/119273085-441c4c00-bbd7-11eb-97ea-9051fd2d2cae.png">
En la imagen, el de arriba es la 'versión mejorada', todo es optimizado menos el tiempo. ¿Sería valido?
Gracias

**Comment by jmopaso** [comment]
Hola!

La mejora en rendimiento de tu versión mejorada debe ser vista desde el punto de vista de **nodos expandidos**, por lo que lo que mencionas si sería válido (ya que tu versión mejorada es mejor en rendimiento). Sin embargo, no es común que al haber menos nodos expandidos el tiempo fuera mayor, te recomiendo para esto correr tu programa sobre más que un sólo problema (el enunciado pide que lo corras sobre los 10 primeros).

Saludos!

**Comment by CataAlamos** [comment]
Hola, ¿Sería posible mostrarte lo que hice, no por github por el código de honor, para entender porque pasa esto? Corri los 10 problemas, donde la primera ejecución es sin la regla de empates y la segunda es con. Marque con verde las con menos expansiones y con rojo las con mas expasiones. Pero no entiendo porque esta mal lo que hice.
<img width="496" alt="1  No tie; 2  tie " src="https://user-images.githubusercontent.com/62016215/119383548-75595280-bc91-11eb-82b5-8c4a24a57ff6.png">

**Comment by CataAlamos** [comment]
¿Para cuántos casos debe mejorar? Hay un número esperado, porque no todos mejoraron en mi caso.

**Comment by jmopaso** [comment]
En parte eso es lo que tu debes analizar en la pregunta. Esta muy bien que te llame la atención que con la regla de empates tengas peor rendimiento en algunos problemas, ya que es contra intuitivo según lo discutido en las otras preguntas, por lo que uno al menos debería observar una mejora en la mayoría de los problemas, el hecho de que esto no suceda podría ser una señal de que algo no se está implementando bien.

Para esta pregunta la clave es fijarse en la función `fvalue` del archivo `astar` ya que esta define como se van a ordenar los elementos en la open.

Saludos!
