### ISSUE TITLE
[Parte 2][Pregunta 2] Confusión con los costos

### ISSUE THREAD

**Issue by joaquinhernandezg** [UC-IIC2613/Syllabus#108]
No me queda muy claro como se definen los costos, en el enunciado quiere decir que mover una pieza tiene costo 1, mover 2 piezas tiene costo 1/2 y así sucesivamente? O que al mover la pieza con el numero  1 tiene costo 1, la pieza con el numero 2 tiene costo 1/2 y así hasta la pieza 15?

**Comment by jmopaso** [comment]
Hola!

Es lo segundo que dices. Mover la pieza con el número n tiene costo 1/n.

Saludos
