### ISSUE TITLE
[Tarea 1] Descuento por un formato que no está en el enunciado

### ISSUE THREAD

**Issue by kylevon** [UC-IIC2613/Syllabus#109]
No aparece la opción de apelar esto en el form de recorrección por eso hago este issue. Y también porque vi que no fui el único que le descontaron por esto. En el enunciado no se especifica que no se puede agregar otras carpetas, sólamente especifica que hay que "crear el directorio T1/ que contenga todos los archivos y subdirectorios especificados". Creo que es injusto que se descuente puntaje por algo que no aparece en el enunciado.

**Comment by lucas-valenzuela** [comment]
Sumado a lo anterior, encuentro desproporcionado que se aplique un descuento de 0.5, que es equivalente a lo que se aplica por entregar atrasado. Si se descuenta de forma tan grande creo que deberían explicitar en el enunciado  la gravedad de la sanción
