### ISSUE TITLE
[Tarea 1] Pregunta 2.1

### ISSUE THREAD

**Issue by Aloncarrasco** [UC-IIC2613/Syllabus#11]
Hola,
Puedo tener un grafo asi:
<img width="360" alt="Sin título" src="https://user-images.githubusercontent.com/62113089/114598955-7f367180-9c60-11eb-9db3-28d97cd8e2a4.png">

**Comment by jfuentesg26** [comment]
Hola! Si se puede tener un grafo así, lo señalado con rojo cuenta como un ciclo.

**Comment by Aloncarrasco** [comment]
Otra pregunta, si le pongo al nodo de la derecha A y al de la izquierda B (los que estan marcados con la cosa roja). Puedo tener el camino camino(A,B,3) o el camino camino(A,A,4)? (considerando que el programa termina y muestra los otros camino) o no puedo generar un camino que repita arcos?, además el camino camino(A,A,2) sería valido? pues no repite arcos.

**Comment by jmopaso** [comment]
Hola!

Como bien dices, todos esos caminos son válidos tenerlos en tu modelo (considerando el grafo de arriba), ya que corresponden a caminos de un ciclo. Como dice la pregunta: ```Esto no significa que no debe considerar los caminos con ciclos. Lo que debes asegurar es que no se le 'escape' ningún camino sin ciclos existente en el grafo```, por lo que mientras se cumpla esa condición (considerar tanto los caminos **sin ciclos** como con ciclos) y tu programa termine todo bien.

Saludos

**Comment by Aloncarrasco** [comment]
Puedo interpretar el enunciado de la siguiente forma?

El programa debe si o si devolver todos los caminos sin ciclos que encuentre y **PUEDE** devolver devolver caminos con ciclos aunque no es necesario.

**Comment by jfuentesg26** [comment]
Hola! tu programa debe devolver todos los caminos sin ciclos que encuentre y también debe devolver los caminos con ciclos

**Comment by Aloncarrasco** [comment]
> Hola! tu programa debe devolver todos los caminos sin ciclos que encuentre y también debe devolver los caminos con ciclos

pero hay caminos con ciclos de largo tan grande como se quiera, ¿como podría devolver esos caminos?
