### ISSUE TITLE
[Materia] Diferencia entre los sets de entrenamiento y validación

### ISSUE THREAD

**Issue by gsalinas0** [UC-IIC2613/Syllabus#110]
Hola. En las últimas clases hemos visto bastante los 3 tipos de sets de ejemplos que existen para entregarle a un algoritmo, y entiendo que el set de Testeo sirve como prueba para este. Eso sí, no logro entender cual es la diferencia entre el set de entrenamiento y el de validación. Entiendo que el de validación sirve para ajustar algo llamado 'hiperparámetros', pero tampoco entiendo que son estos, ni como se diferenciarían de parámetros comunes. Me podrían ayudar con esto?

Saludos

**Comment by diegomendieta** [comment]
Hola. Para entender estos conceptos, es importante recalcar primero que la finalidad del Machine Learning es poder generar un modelo que permita predecir outputs y **generalizar** conocimiento. Es decir, que a partir de un set de datos, el modelo sea capaz de predecir el comportamiento de datos _fuera del conjunto original_.

Ahora, a tu pregunta. En primer lugar, y como bien dices, el **set de test** sirve para medir el rendimiento efectivo de tu algoritmo. Una vez que tienes el modelo ya entrenado, evalúas su comportamiento en el set de test. Si, por ejemplo, tu accuracy resultó ser de un 95% en el set de test, te quedas con que tu modelo tiene una capacidad de predicción de un 95%.

En segundo lugar, el **set de entrenamiento** corresponde a los datos usados para afinar los parámetros _entrenables_ de tu modelo. Estos corresponden, en el caso de una SVM, por ejemplo, a los parámetros de la ecuación del hiperplano utilizado para hacer la clasificación. A partir de los datos de entrenamiento, generas un modelo que _esperas_ que se ajuste bien a la realidad.

En tercer lugar, el **set de validación** corresponde a los datos que ocuparás para evaluar el comportamiento en la etapa de entrenamiento.

Tomemos el ejemplo de una red neuronal (se que aún no lo han visto, pero aguántame un poco; en este caso, basta con saber que puedes evaluar el comportamiento de la red a medida que vas entrenándola); si midieras la accuracy de tu red sobre el set de entrenamiento, estarías obteniendo un valor sesgado, ya que estás evaluando qué tan bien se ajusta tu modelo a los mismos datos que estas ocupando para entrenar, **y no qué tan bien generaliza** y predice outputs para inputs que no ha _visto_ antes.
Debido a esto, una buena medida para saber si tu entrenamiento está siendo efectivo o no es ir observando la accuracy en el set de validación; si esta va mejorando, significa que tu modelo también lo está haciendo, ya que **mejora su capacidad de predicción sobre datos que no ha _visto_ antes**.

Preguntaste, además, por los **hiperparámetros**. Estos corresponden a los parámetros **no entrenables** de un modelo, que deben ser elegidos de manera _manual_. Un ejemplo de hiperparámetro es el _slack_ de una SVM. El entrenamiento no afina el slack utilizado, sino que, dado un slack pre-fijado, encuentra aquellos parámetros del hiperplano que logran una mejor separación de los datos. De esta manera, el set de validación sirve además para encontrar los valores de los hiperparámetros que resultan en que nuestro modelo se comporte de mejor manera, **sin sesgar nuestras observaciones** buscando mejorar el rendimiento en el set de test.

En resumen, el flujo de trabajo en un modelo de Machine Learning es el siguiente:
1. Usar el set de entrenamiento para entrenar el modelo
2. Observar el rendimiento en el set de validación. Si estamos conformes con el resultado, continuar. Si no, ajustar hiperparámetros (o derechamente cambiar de modelo) y volver a entrenar.
3. Observar el rendimiento _**real**_ del modelo, evaluando sobre el set de test.

Espero haber respondido a tu pregunta, y perdona por extenderme tanto, pero es un tema que es importante manejar. Éxito!

**Comment by FelipeA7** [comment]
Hola! Me sumo a la pregunta pues luego de leer la respuesta de @diegomendieta no me queda tan clara la diferencia entre los datos de testing y validación.
Para el ejemplo de la red neuronal, cual sería la diferencia entre el rendimiento que entrega el modelo al usar los datos de validación o los datos de testing?

**Comment by diegomendieta** [comment]
Hola, @FelipeA7. En el ejemplo de la red neuronal, el set de validación es ocupado **durante** el entrenamiento, para entender en _tiempo real_ cómo se está comportando el modelo y si el entrenamiento está yendo como esperamos o no. En cambio, el set de test es ocupado **después** de la etapa de entrenamiento, para medir el **desempeño real** del modelo.

La razón de esto es que si ocupásemos solamente el set de test para evaluar el entrenamiento y el desempeño final, estaríamos **sesgando** nuestros resultados, ya que estamos afinando parámetros de manera tal que aumente la accuracy de test. Para evitar sesgar los resultados obtenidos, ocupamos el set de validación durante el entrenamiento, y afinamos parámetros de manera tal que aumente la accuracy de **validación**. Cuando ya estemos conformes con el resultado (o creamos que el modelo no puede seguir mejorando, según la accuracy de validación obtenida), **terminamos la etapa de entrenamiento** y evaluamos el **rendimiento real** del modelo en el set de test (conjunto de datos que el modelo no ha visto nunca antes y, por lo tanto, representativos del desempeño real de nuestro modelo).
