### ISSUE TITLE
[Parte2][Pregunta 2] Valores de suboptimalidad

### ISSUE THREAD

**Issue by joaquinhernandezg** [UC-IIC2613/Syllabus#111]
Hice una heurística para el light puzzle, pero cuando veo los valores de subptimalidad, a veces me salen valores menores que 1, tiene sentido eso, o significa que mi heurística está mala? Los de la heurística/15 son todos 1 :(:(

**Comment by jcechavarri** [comment]
Hola!
Recuerda que en la ayudantía se define la *suboptimalidad* como el cuociente entre el costo de la solución encontrada (c) y el costo óptimo (c*). Si te dan valores menores a 1, significa que `c/c* < 1`  ->  `c < c*`.

¿Te hace sentido que el costo de la solución que encuentras sea menor al costo óptimo??
Espero que con eso puedas resolver tu problema 👋

**Comment by joaquinhernandezg** [comment]
Bueena gracias, entonces el problema era que mi heurística no era admisible pq estaba sobreestimando el costo del camino óptimo
