### ISSUE TITLE
[Tarea 2] Problema con cota de suboptimalidad

### ISSUE THREAD

**Issue by jorge-ovalle** [UC-IIC2613/Syllabus#112]
En una ayudantía se demostró lo siguiente:
![Captura de pantalla (17)](https://user-images.githubusercontent.com/69663302/119581241-29d99e00-bd90-11eb-996a-0d04eb803218.png)
Creo que está mal la demostración, porque en el contexto de Weighted A* f(s) = g(s) + wh(s) y no g(s)+ h(s) como lo ponen en la demostración. Además, los nodos se van extrayendo según g(s) + wh(s), lo que no implica que se extraiga el nodo con menor g(s) + h(s). Por lo mismo, creo que el resultado no es válido.

Aunque yo esté equivocado tampoco es correcto que f(s) <= f(s)* para todo s extraido. Eso es solo cierto cuando h es consistente. Si h es admisible se cumple solo cuando s está en el camino óptimo.

**Comment by jcechavarri** [comment]
Hola!
En la demostración cuando hacen eso no están hablando de *weighted A** en particular, sino que de una función de evaluación definida como f(s) = g(s) + h(s) (para poder reemplazarlo con el g(s)+h(s) en el PD). Si te fijas, te piden demostrar que el estado *s* con menor g(s) + h(s) dentro de la *Open* es menor o igual al costo óptimo de la solución. Con respecto a lo segundo que comentas, creo que tienes razón y debería salir consistente. De esa manera, puedes asegurar que para ~cualquier~ algún s en la *Open*, f(s) <= c*.

Espero haber respondido tu duda 😄

**Comment by jorge-ovalle** [comment]
Hola! Es que la demostración me hace ruido por los siguientes puntos:
1. La desigualdad f(s) <= c* es solamente válida para los estados s que fueron expandidos y no todos los de la _Open_.  A modo de ejemplo, si en la ejecución de _A*_ (no _weighted_)  s* es el estado objetivo con valor f(s*) = c* (pues h es consistente), entonces todos los otros estados s que quedan en la _Open_  después de terminada la ejecución  (nunca fueron expandidos) cumplen que f(s*) >= c*.
2.  En la _Open_ asociada  a _Weighted A*_ pueden quedar elementos que nunca se hubieran expandido en el algoritmo _A*_ y por lo explicado en el punto anterior estos cumplen que f(s*) >= c*, por lo que no se cumpliría lo que plantea la demostración de que f(s) <= c* para todo s de la _Open_.

**Comment by jcechavarri** [comment]
Perdón! Me equivoqué al escribir que todos los estados en la *Open* cumplen con `f(s) <= c*`. Aun así, se pide demostrar que el estado que se **extrae** de la *Open* (el s con menor f(s)) tiene un valor de `f(s) <= c*`. Esto si tiene sentido en la demostración ya que cualquier estado s* perteneciente al camino óptimo, por definición de consistencia, debe cumplir que `f(s*) <= c*`.

Con respecto al punto 2 que mencionas, tienes razón al mencionar que en *weighted A**  pueden quedar estados "mejores" sin expandir, pero no tiene directa relación con la demostración. El objetivo de esta es simplemente mostrar que se puede obtener una cota máxima de *sub-optimalidad* para una solución encontrada.

Puedes verlo como que *weighted A** con peso `w` encontró solución con costo `c(pi)` (no te interesa cómo exactamente). Sabemos por clases que  la *sub-optimalidad* de tu algoritmo esta acotada por `w`, pero la gracia es que puedes estimar una cota más estrecha utilizando los estados que quedaron el la *Open*. Así, te quedaría algo como `subopt <= c(pi) / (min g(s) + h(s)) <= w`.

**Comment by jorge-ovalle** [comment]
Pero en la ejecución la extracción ocurre según g(s) + wh(s). Si wh(s) fuera consistente se cumple que g(s) + wh(s) <= c*, lo que permite concluir (como w>=1) que g(s) + h(s) <= c*. Sin embargo, en general se pierde la consistencia en _Weighted A*_ . La demostración asume que los elementos que están en la _Open_ son aquellos que se hubieran extraído de _A*_ no _weighted_, pero eso no es necesariamente cierto. Es como si en el tiempo de ejecución de _Weighted A*_  se **extrae** un estado s debido a que tiene la menor g(s) + wh(s) hasta ese momento, pero no es estrictamente cierto que usando g(s) y h(s) se cumple que g(s) + h(s) <= c*.

**Comment by jcechavarri** [comment]
Tienes que considerar que **siempre** habrá un estado s en la *Open* tal que es parte de la solución óptima c*! (y por lo tanto esta como si hubiese sido expandido por A*). Principalmente sabes que el estado inicial **pertenece a c***. Luego, si expandes este, tienes dos opciones:

1. Extraes de la *Open* un estado que no pertenece a c*: en este caso queda en la *Open* un estado que pertenece a c*.
2. Extraes un estado que pertenece a c*: Dentro de los nuevos estados que agregas a la *Open* existe uno que pertenece a c*.

Independiente de cuantas iteraciones realices con *weighted A**, siempre habrá en la *Open* al menos un estado que pertenezca a la solución óptima y, por lo tanto, cumple con que `g(s) + h(s) <= c*`.

**Comment by jorge-ovalle** [comment]
Aun veo problemas con tus dos puntos:
1. El estado inicial si cumple que pertenece a c*, eso lo entiendo. Sin embargo, se expande altiro (por ser el punto de partida), por lo que abandona la Open y los estados que produce no podemos asegurar que estén en c*. Si todos lo estados que produce no están en c*, entonces la Open solo tendrá estados que no están en c* (pues ya se sacó el inicial).
2. Si se fuera a cumplir que el estado inicial produce un estado que pertenece a c*, naturalmente en la Open aparecerá dicho estado que cumple la condición.

A lo que voy es que el punto 1. no necesariamente se cumple. En la implementación que se dio en la ayudantía se busca el mínimo de la Open según g(s)  + h(s) al final de la ejecución. Si cada punto extraido nunca produce hijos c*, entonces según 1. en la Open no habrá ningún estado c*.

**Comment by jcechavarri** [comment]
Creo que ahí está lo que te confunde, cuando expandes el estado inicial, agregas TODOS los estados nuevos a la *Open*. Es decir, si existe un camino desde el estado inicial al final, necesariamente al expandir el estado inicial, uno de los sucesores será si o si parte del camino óptimo (sino no podrías llegar al objetivo). Si bien se extrae un estado cualquiera de la *Open* (según el f(s)), siempre habrá un estado que si pertenece al camino óptimo.

**Comment by jorge-ovalle** [comment]
Ya perfecto. Ahí si me queda claro. Sory por tantas pregunta jaja. Muchas gracias!

**Comment by jcechavarri** [comment]
Para eso estamos! Éxito con la tarea 🎉
