### ISSUE TITLE
[Tarea 2] Manhattan 

### ISSUE THREAD

**Issue by CataAlamos** [UC-IIC2613/Syllabus#113]
Hola, en la pregunta 2.2 se nos pide crear una variación de Manhattan, pero no me queda claro ¿Qué tan similar debe ser a la Manhattan? ¿Podemos hacer una heurística distinta, dado que Manhattan se basa en la suma de distancias?
Muchas gracias

**Comment by jcechavarri** [comment]
Hola!
La idea de la pregunta es que te cuestiones por qué no es admisible la suma de distancias Manhattan y veas una posible solución a esto. Así como proponen en el enunciado que una solución podría ser dividir la distancia en 15, la idea es que pienses en otra solución que abarque el tema de la no admisibilidad. Es decir, tiene que usar algo como Manhattan y no una heurística distinta.
Espero haberte ayudado!
