### ISSUE TITLE
[Tarea 2] [Pregunta 3] Error en import

### ISSUE THREAD

**Issue by milosoria** [UC-IIC2613/Syllabus#114]
Hola! Al correr test_preferred_astar.py me arroja el siguiente error:
`ModuleNotFoundError: No module named 'litemodel'`
Ya instalé tensorflow y silence_tensorflow, debiese instalar algo mas?

**Comment by jcechavarri** [comment]
Hola!
Esto se refiere al archivo `litemodel.py` que está en el mismo directorio que `test_preferred_astar.py`. En caso de que esté y no lo reconozca, fíjate desde que directorio estás ejecutando tu tarea, puede que estés en otro directorio :smile:
