### ISSUE TITLE
[Tarea 2][Pregunta 2] Explicacion general o especifica 

### ISSUE THREAD

**Issue by NickCastillo** [UC-IIC2613/Syllabus#115]
Hola! Para esta pregunta se pide una explicacion general? Hablando solo del **resultado** de utilizar la regla de desempate (sea cual sea)? O nos piden una explicacion mas especifica mencionando la tecnica implementada (por ejemplo el nuevo calculo de f en caso de tener uno) ?

**Comment by jcechavarri** [comment]
Hola! Te refieres a la Pregunta 1 de la Tarea 2, cierto?

Tal como dice en el enunciado;

> Una buena implementación, al tener dos nodos en la Open con el mismo valor f (es decir, dos nodos n1 y n2 tales que f(n1) = f(n2)), debiera preferir para expansión a aquel que tiene el mayor valor g, o, equivalentemente, menor valor h.

En la primera pregunta, se pide que expliques de manera general por qué esta implementación es mejor que no quebrar empates (o quebrarlos hacia el otro lado). Esto puedes hacerlo usando tu intuición, pero tienes que argumentar a favor de esta regla.

Espero haberte ayudado 😄
