### ISSUE TITLE
[Tarea 2][Pregunta 3.1] Numero de problemas

### ISSUE THREAD

**Issue by Brocoleta** [UC-IIC2613/Syllabus#117]
Es necesario correr todos los problemas por cada test, o podemos por ejemplo correr solo los primeros 10 problemas?

**Comment by fivaldivia** [comment]
Hola! Corre todos los problemas pero si tienes alguno que se demora mucho tiempo (este tiempo definido por ti como dice el enunciado) no lo ejecutes.
