### ISSUE TITLE
[Tarea 2][1.4 Optimalidad]

### ISSUE THREAD

**Issue by mvbeuchat** [UC-IIC2613/Syllabus#118]
Hola!

En el enunciado nos piden el rendimiento de nuestra "versión mejorada" en las soluciones óptimas. Sin embargo, por la implementación que se sugiere en otras issues cambiando el valor de fvalue y lo visto en clases, la "versión mejorada" genera soluciones que no necesariamente son óptimas. ¿Es necesario entonces, encontrar una "versión mejorada" que encuentre soluciones óptimas cambiando solo fvalue? ¿O podemos implementar una versión mejorada que encuentre soluciones subóptimas?

**Comment by jcechavarri** [comment]
Hola!

Si bien se sugiere que cambien cómo se calcula el `fvalue`, este solo debe cambiar con respecto a la preferencia de un estado particular en caso de empate. Si cumples con esto tu solución sí será la óptima, ya que sigues extrayendo los nodos de acuerdo a un `fvalue` decreciente.
