### ISSUE TITLE
[Tarea 1] Problemas con el código entregado

### ISSUE THREAD

**Issue by CataAlamos** [UC-IIC2613/Syllabus#12]
Hola, estoy en la Parte 2 en la pregunta 1 y he intentado correr el siguiente código:
`camino(X,Y,Largo) :- arco(X,Y), Largo=1.
camino(X,Y,Largo) :- camino(X,Z,L1), camino(Z,Y,L2), Largo=L1+L2.
`
pero no se carga en mi terminal. Esto ocurrió cuando agregué la condición de ser no dirigido. Ha estado corriendo por aprox 20 minutos y me preocupa dado que lo necesitamos para los otros problemas de la tarea.

**Comment by aamedinaj** [comment]
Cuando se quede pegado ejecutando mucho tiempo puedes forzar la interrupción en la consola con Ctrl + C (en windows, sé que hay un análogo para otros sistemas, es lo mismo que en python). Ahí puedes ir cambiando cosas y ver si se sigue quedando pegado o no.

🦊

**Comment by CataAlamos** [comment]
Hola, estoy usando el mismo programa de la tarea. El problema ocurre solamente con el grafo no dirigido, ¿Qué condición puedo cambiar para que no se quede pegado? Me preocupa eliminar algo que pueda ser evaluado, ya que la pregunta me pide decir como cambía el resultado de un grafo dirigido a uno no dirigido. 

<img width="573" alt="Screen Shot 2021-04-13 at 17 22 16" src="https://user-images.githubusercontent.com/62016215/114623118-d1858b80-9c7c-11eb-832b-34339b91e033.png">

**Comment by jmopaso** [comment]
Hola,

En el caso de la pregunta 1 de la parte 2 debes considerar que el grafo sea **dirigido**. Sólo para las demás preguntas de esta parte (luminarias) debes considerar el predicado ```arco(X,Y) :- arco(Y,X)``` que finalmente vuelve tu grafo dirigido a uno no dirigido.

Saludos!
