### ISSUE TITLE
[Tarea][1.3]

### ISSUE THREAD

**Issue by Huasito-Appel** [UC-IIC2613/Syllabus#120]
Hola, es posible pedir ayuda sobre la ayuda? llevo un par de dias pensando en como puede ser este tipo de problema de busqueda y la verdad siento que no llego a puerto.

**Comment by gsalinas0** [comment]
Me sumo a esto. También estoy perdido en como hacer la 1.3 :sweat:

**Comment by jcechavarri** [comment]
@Huasito-Appel @Gsalinas1506 Les recomiendo ir a la sesión de ayuda para la tarea hoy, yo creo que el profe les podrá aclarar mejor las dudas que tengan!

De cualquier manera, más que nada la ayuda dice que busquen un problema en el cual existan muchas soluciones "muy parecidas" o iguales, a las cuales se puede llegar por varios ordenes de exploración distintos (en específico, que el orden de la solución no afecte a la solución en sí). Fíjense que pasa cuando se quiebran empates hacia un lado o el otro, ¿Cómo afecta a la cantidad de nodos expandidos?

Espero haber podido darles alguna pista más de como responder la pregunta 😁
