### ISSUE TITLE
[Tarea 2][Pregunta 1.4] Como ordenar los nodos?

### ISSUE THREAD

**Issue by gsalinas0** [UC-IIC2613/Syllabus#121]
Hola. Estoy tratando de hacer el item 1.4, y la verdad no entiendo que linea(s) tengo que agregar/modificar.

Entiendo que la gracia es que dados dos nodos en la open con mismo valor de f, debo elegir extraer/expandir aquel con mayor valor de g. Mi problema es que no logro encontrar la forma de poder 'ver' el valor del f de los sucesores para poder elegir uno el cual expandir, y mucho menos poder ordenarlos. Se me ocurre quizás revisar todos los sucesores con el `for` , y cuando ya se hayan instanciado todos los nodo, ordenarlos de acuerdo al criterio de desempate. El tema es que después no sabría como agregarlos a la open con tal de que "salgan/se extraigan en el orden que yo quiero".
Por ejemplo, si tengo 3 nodos sucesores _a_, _b_ y _c_ , y estimo que, en orden, debiesen expandirse primero _c_, luego _b_ y después _a_ ¿Cómo los agrego a la open?¿lo hago en orden inverso (partiendo por _a_, luego _b_ y luego _c_), o como?
Pregunto porque vi en otra issue que la open es una estructura de datos llamada Binary Heap que se ordena de a pares o algo así (quizás estoy hablando puras tonteras, no he dado estructuras de datos), y me preguntaba si esto no afectaría de alguna forma casos en los que pudiesen haber triples empates o superiores.
Por favor ayuda, estoy muy confundido :sweat:

**Comment by jcechavarri** [comment]
Hola!

El *Binary Heap* corresponde a un árbol en el cual cada nodo se ordena de acuerdo a su `key` en orden ascendente. Si bien podría ordenar según un par de llaves, no está implementado así y tampoco es la idea que se compliquen en hacerlo.
Luego, si te fijas en el archivo `binary_heap.py`, se puede ver que al insertar un nodo nuevo, este se agrega lo más abajo en el árbol y luego va subiendo a través del árbol (`percolateup`) hasta que no hayan nodos con una `key` menor a este. [Acá](https://www.youtube.com/watch?v=VEYSSANa-cw) te dejo un video cortito de cómo se maneja la inserción en un árbol binario. Si entiendes esto tal vez se te ocurra alguna forma de implementarlo como mencionas en tu pregunta.

De cualquier forma, como sabemos que la *Open* ordena según el valor de `fvalue`, existe la opción que simplemente modifiquen cómo se calcula esta, sin la necesidad de complicarse o modificar mucho código.

Espero haberte ayudado!
