### ISSUE TITLE
[Control 21] Error en aproximación pregunta de entropía

### ISSUE THREAD

**Issue by gicrot** [UC-IIC2613/Syllabus#122]
Hola, 

Acabo de hacer el control y en la pregunta donde piden la entropía usé 4 decimales en vez de solo 2, entonces al momento de aproximar la respuesta Canvas me lo tomó como que la pregunta estaba mala, siendo que si lo aproximo al segundo decimal (como sale en la solución), la respuesta es correcta.

**Comment by Jamidd** [comment]
Ok, voy a revisar tu respuesta y lo cambio acorde. 
Saludos, 
Jaime.
