### ISSUE TITLE
[Tarea 2][Pregunta 2] Algoritmo en video

### ISSUE THREAD

**Issue by knight-who-says-ni** [UC-IIC2613/Syllabus#123]
Hola!!

Tenía la duda de si hay que explicar el algoritmo del paper para calcular la heurística en el video, o basta con dar la idea e intuición de la heurística.

Gracias!!

**Comment by fivaldivia** [comment]
Hola, tal como menciona el enunciado se pide que expliques la idea de **cómo se calcula** la heurística. Con tal de que la expliques como más te haga sentido y creas que el público objetivo del video lo entienda, está bien!
