### ISSUE TITLE
[Tarea 2][Pregunta 3.1]

### ISSUE THREAD

**Issue by tomasalvarez13** [UC-IIC2613/Syllabus#124]
Hola, estoy teniendo el siguiente error al tratar de correr `test_prefered_astar.py`
![image](https://user-images.githubusercontent.com/48598610/119911835-1e20df80-bf28-11eb-9e75-c317596c49f7.png)
Que podrá ser? Hay alguna versión específica de tensorflow que haya que instalar?

**Comment by ebrzovic** [comment]
Hola,

Que extraño, el error que sale es porque supuestamente estás codificando un string. No es necesario codificarlo porque ya está codificado. ( https://stackoverflow.com/questions/28583565/str-object-has-no-attribute-decode-python-3-error )

Te recomiendo hacer lo siguiente, verifica que los archivos que estás ocupando sean los mismos archivos que se encuentran actualizados el repositorio. Si no te funciona eso, instala la versión 2.5 de tensorflow que es la que me funciona por lo menos. (puede ser que no tengas actualizado pip, así que asegúrate que tengas la última versión de pip).

Quedo atento a cualquier cosa.
