### ISSUE TITLE
[Tarea 2][Pregunta 2.2]

### ISSUE THREAD

**Issue by sperezmasri** [UC-IIC2613/Syllabus#125]
Hola, tengo dos dudas con respecto a esta pregunta.

1. Tenemos que probar nuestro código con el desempate incluido? o con el original?
2. Hay que cambiar el código (aparte de crear la nueva heurística) para implementar el costo nuevo?

**Comment by jmopaso** [comment]
Hola!

1. Lo importante de esta pregunta es que compares el rendimiento de ambas heurísticas bajo el mismo criterio (si pruebas una heurística con un criterio, la otra también debe ser probada con el mismo). Esto quiere decir que no es estrictamente necesario que lo implementes con la regla de desempate, sin embargo, podría ser mejor realizarlo de esta forma, ya que como se indica en la parte 1 esta es una mejor implementación.
2. Si bien la pregunta se centra principalmente en la implementación de las heurísticas, también es necesario que implementes la lógica del `LightPuzzle`, como bien dices, cambiando la forma en que se calcula el costo en relación con el puzzle de 15 normal. De otra forma tus resultados obtenidos no serían los esperados.

Saludos!
