### ISSUE TITLE
[Tarea 2][Pregunta 2.2]

### ISSUE THREAD

**Issue by Christian-Klempau** [UC-IIC2613/Syllabus#126]
Hola!
Tenía una duda:
para implementar el problema de light_manhattan, debo cambiar los costos g de los nodos, por lo que me hizo sentido crear una clase similar a Puzzle, pero donde los costos de movimientos no son 1, como para puzzle original.

Luego, implementé ambas heurísticas: div_15 y la propia, pero se me genera un problema:
no es posible encontrar una solución. O por lo menos, no en un tiempo razonable, ya que después de mucho tiempo ejecutando, probando con distintos pesos para h, y probando con las 2 distintas heurísticas, no llego a nada. Se les ocurre qué podría ser??

P.D: imprimo los valores f y efectivamente son crecientes.
P.D 2: si utilizo manhattan tradicional, el problema se soluciona en menos de 0.5s para cada test (aunque claro, con subobtimalidad menor a 1).

**Comment by ebrzovic** [comment]
Hola Cristian,
Tengo 2 teorías de lo que puede estar pasando con tu código, ya que no lo puedo ver directamente.
1)	El primero es que simplemente cambiaste el costo de la heurística o solo le cambiaste los pesos de ella. En ese caso te recomiendo crear una heurística nueva que no sea solo cambiar los pesos. 
2)	La segunda es que tu heurística no es admisible. Probablemente el error de tu código proviene a que tienes mal implementada h, ya que f no debería ser creciente. En ese caso, modifica tu heurística para que sea admisible
Quedo atento a cualquier duda.

**Comment by Christian-Klempau** [comment]
Perdón por la demora :(
Gracias por responder, lo tendré en cuenta :)
Los tests del profesor mejoraron mi análisis y ahora tarda menos de 10 segundos
