### ISSUE TITLE
[Tarea 2] [Pregunta 3.6] Duda de enunciado

### ISSUE THREAD

**Issue by milosoria** [UC-IIC2613/Syllabus#127]
Hola! Por _parte 1_ se refiere a la pregunta 1 de la tarea, cierto?  O la pregunta 3.1?
Gracias de antemano!

**Comment by jmopaso** [comment]
Hola!

Tal y como dices, se refiere a la parte 1 de la tarea (o como tu lo señalaste la pregunta 1 **de la tarea**)

Saludos.
