### ISSUE TITLE
[Tarea 2] [Pregunta 1.3]

### ISSUE THREAD

**Issue by FelipeA7** [UC-IIC2613/Syllabus#128]
Hola, para el ejemplo del problema exponencial puedo usar una imagen de internet que muestra expansiones del algoritmo A* o solo puedo usar contenido que haya sido creado por mi?

**Comment by ebrzovic** [comment]
Hola Felipe,
Si se puede, siempre y cuando entiendas lo que quiere decir la imagen. Es preferible explicar con tus propias palabras lo que la imagen transmite. 
Que no se te olvide citarlo o referenciarlo 😊

**Comment by tvallotton** [comment]
Hola, si para esta parte se me ocurrio un ejemplo de orden O(n^2) pero no uno de orden O(exp(n)) cuenta?
