### ISSUE TITLE
[Tarea 1] Parte 2.1

### ISSUE THREAD

**Issue by lucas-valenzuela** [UC-IIC2613/Syllabus#13]
Hola, de acuerdo al enunciado, si tengo los arcos (a, b), (b,c) y (c,a), entonces estos serían los caminos que deberíamos entregar:

Largo 2:
a-b
b-c
c-a

Largo 3:
a-b-c
b-c-a
c-a-b

Estoy en lo correcto?

**Comment by jmopaso** [comment]
Hola Lucas,

Considerando que tengas ese grafo debiese ser:

Caminos con largo 1:
a-b
b-c
c-a

Caminos con largo 2:
a-b-c
b-c-a
c-a-b

En todo caso, ojo que el grafo que señalas es un grafo cíclico, por lo que si lo pruebas con el código propuesto en el enunciado no te va a funcionar (en la primera parte de la pregunta debes explicar por qué pasa eso). Una vez que propongas un predicado usando ```#count``` el modelo te debería entregar los caminos con los largos de arriba.

Saludos.

**Comment by szabala** [comment]
Hola! viendo la ultima respuesta a #11, no deberian estar tambien:

Caminos de largo 3:
a-b-c-a
b-c-a-b
c-a-b-c

ya que estos corresponden a los caminos (a,a,3), (b,b,3) y (c,c,3)?

**Comment by jfuentesg26** [comment]
Hola! Tu modelo debería considerar aquellos caminos con ciclos, por lo que debes tener los caminos de largo 3 que describes, lo importante es que no se te escape ninguno de los caminos sin ciclo y que incluyas también aquellos con un ciclo.

**Comment by jmopaso** [comment]
Hola @szabala, 

Si, en este caso particular deberían considerarse esos caminos porque son un camino (cíclico) posible. Pero de nuevo, lo importante además de eso es que no se les escape ningún camino no cíclico en el modelo.
