### ISSUE TITLE
[Tarea 2] P1.1 Admisibilidad de la heurística usada

### ISSUE THREAD

**Issue by dfloreaa** [UC-IIC2613/Syllabus#130]
Hola, podemos asumir que la heurística utilizada para nuestra demostración en la pregunta 1 de la parte 1 es una heurística admisible? De no ser así, A* no encontraría una solución óptima y weighted A* encontraría soluciones menos óptimas también.

De ser una heurística utilizada para la búsqueda no admisible, el desempate podría a veces resultar perjudicial. ¿Debo explicar el por qué o simplemente hacer la asunción de que h(n) es admisible?

Gracias ☺

**Comment by ebrzovic** [comment]
Hola, Daniel, 

Para esa pregunta se puede asumir admisibilidad. De lo contrario sucede lo que dices, que el desempate podría a veces resultar perjudicial. Se esperaría que mientras más cerca estoy del objetivo entonces menor es mi heurística h y para que esto ocurra la heurística debe ser admisible.

Saludos.
