### ISSUE TITLE
[Tarea 2] [Pregunta 3.4 y 3.6] Duda enunciado

### ISSUE THREAD

**Issue by milosoria** [UC-IIC2613/Syllabus#131]
Hola! En la 3.4, donde dice _extracción de un elemento desde alguna cola, en tiempo constante, calcula el mínimo_, la extracción se hace con extract y para el mínimo top? No le veo el sentido a hacer ambas operaciones con top, pero creo que no queda claro en el enunciado. Por otro lado, qué num_pref debiesemos utilizar para esta pregunta y la 3.6?

**Comment by Huasito-Appel** [comment]
Me sumo a la parte de la pregunta 3.6, ademas de esto debemos ahcer un reporte como en el apartado 3.1? o podemos mostrar una tabla comparativa simple y comentar un par de cosas.

**Comment by diegomendieta** [comment]
Hola, @milosoria. En relación a la 3.4, sí, tiene sentido lo que dices. El enunciado se refiere a que el cálculo del mínimo no debe depender de la cantidad de elementos en las colas. En relación a lo otro, usen el mejor num_pref que les haya dado en la 3.1, hagan una tabla simple pero clara y comenten sus resultados.

**Comment by milosoria** [comment]
@diegomendieta  Gracias por las respuestas! Creo que para la 3.4 tiene más sentido ocupar un num_pref que genere mayor suboptimalidad, no? Si la idea es comprobar que el método garantiza, efectivamente, respetar una cierta cota de suboptimalidad.
