### ISSUE TITLE
[Tarea 2][Parte 3] Dudas acerca 3.4

### ISSUE THREAD

**Issue by gustavobarrezueta** [UC-IIC2613/Syllabus#132]
Hola!
Tengo dos dudas específicas con esta parte. La primera es, para la parte 3 completa, ¿siempre asumimos que estamos con peso igual a 1 o el peso puede ir cambiando? Esto lo pregunto porque al usar siempre w = 1, creo que puedo acortar un poco el código para la parte 3.4. La otra pregunta es acerca de esa parte en específico: cuando nos dicen "La idea clave de esta modificación es que tu algoritmo ya no retornará una solución a menos que pueda demostrar que la solución satisface la cota de suboptimalidad", ¿quiere decir que el algoritmo siempre debe retornar una solución o puede no hacerlo?
Gracias!

**Comment by diegomendieta** [comment]
Hola, @gustavobarrezueta. Asume que el peso puede ir cambiando, no debería requerir mucho esfuerzo adicional. En relación a lo segundo, la garantía pedida sería una solución que te demuestra que puedes conseguir ese grado de suboptimalidad. Por lo tanto, si el algoritmo no es capaz de encontrarla, no retornará una solución.

**Comment by gustavobarrezueta** [comment]
Allí tengo una duda, porque siempre existirá la solución óptima que cumplirá con cualquier cota de suboptimalidad que yo ingrese a PrefAstar, pero parece ser que no encuentra esa solución el algoritmo (o se demora más del límite de tiempo que impuse). Entonces no sé si dejar corriendo mi algoritmo hasta que encuentre esa solución o retorno que no se cumple con la cota al primer nodo solución encontrado que no cumpla con la cota.

**Comment by diegomendieta** [comment]
Si el algoritmo no es capaz de encontrar una solución que cumpla con la suboptimalidad pedida en un tiempo que consideras razonable, entonces retorna que no encontró una solución. En otras palabras, el criterio de parada debe ser encontrar una solución que cumpla, o que se cumplió un tiempo de ejecución determinado.

**Comment by gustavobarrezueta** [comment]
Entiendo, muchas gracias, Diego.
