### ISSUE TITLE
[Tarea 2][Parte 3] Problemas con tensorflow

### ISSUE THREAD

**Issue by ivergara1** [UC-IIC2613/Syllabus#133]
Hola!
Estoy teniendo varios problemas con tensorflow que no me dejan ejecutar el código. Cuando trato de ejecutar test_preferred_astar.py me sale lo siguiente: 

![error](https://user-images.githubusercontent.com/48482469/120123189-700d7380-c17b-11eb-865f-7b2c1ddbf0ca.png)

Llevo mucho tiempo tratando de arreglarlo, pero me siguen saliendo distintos errores. No sé si es un error de instalación o de la configuración de mi computador. Alguien me puede ayudar?

**Comment by benjavicente** [comment]
Hola! Sale que no encuentra el archivo. Yo cambié esta línea
https://github.com/UC-IIC2613/Syllabus/blob/abe1cd797a4a8a0eee62dfe91664e87072c1cace/Tareas/Tarea%202/Parte%203/puzzle_nn_new.py#L15
a esto, usando un path relativo al archivo:
```py
from os import path  # mejor si está al inicio
model = keras.models.load_model(path.join(__file__, '..', '15puzzle_solver_model.h5'))
```
y me funcionó perfecto.

**Comment by ivergara1** [comment]
Bueena @benjavicente  muchas gracias!! Ya había intentado hacerlo con paths relativos pero parece que lo había hecho mal porque de la forma que yo lo hacía no me funcionaba jaja. Te pasaste!!
