### ISSUE TITLE
[Tarea 2][Pregunta 1.4] Duda Open

### ISSUE THREAD

**Issue by beatrizacuna** [UC-IIC2613/Syllabus#135]
Hola! Estoy implementando el desempate en fvalue extrayendo los dos nodos a la cabecera del heap y luego insertándolos de vuelta, pero estoy teniendo un error cuando corro test_astar.py, que según yo, es porque en Open siempre hay o 0 elementos o 1, y no sé por qué se da eso. Este es el error que me tira:

Traceback (most recent call last):
  File "test_astar.py", line 36, in <module>
    print('%5d%10d%10d%10d%10.2f%10.2f' % (prob+1, s.expansions, len(s.generated), result.g, s.end_time-s.start_time, s.estimate_suboptimality()))
AttributeError: 'NoneType' object has no attribute 'g'

Alguien podría ver mi código y ayudarme porfiiii

**Comment by benjavicente** [comment]
Es el problema que menciono en la issue anterior, #134

**Comment by beatrizacuna** [comment]
Pero no entendí muy bien, debería cambiar los archivos mencionados?

**Comment by benjavicente** [comment]
En `Tarea 2/Parte 1/test_astar.py:35-37` cambiar:

```py
result = s.search() 
print('%5d%10d%10d%10d%10.2f%10.2f' % (prob+1, s.expansions, len(s.generated), result.g, s.end_time-s.start_time, s.estimate_suboptimality())) 
total_time += s.end_time - s.start_time
```

a algo como

```py
result = s.search()
time_delta = s.end_time - s.start_time
if result:
    data = (prob + 1, s.expansions, len(s.generated), result.g, time_delta, s.estimate_suboptimality())
    total_cost += result.g
    if show_solutions:
        print(result.trace())
else:
    data = (prob + 1, s.expansions, len(s.generated), -1, time_delta, -1)
print("%5d%10d%10d%10d%10.2f%10.2f" % data)
total_time += time_delta
```

para no usar `result.g` en el caso que `result` sea `None`.

**Comment by beatrizacuna** [comment]
Y lo que está pasando en Open está bien? Que siempre haya solo un elemento

**Comment by benjavicente** [comment]
> Estoy implementando el desempate en fvalue extrayendo los dos nodos a la cabecera del heap y luego insertándolos de vuelta, pero estoy teniendo un error cuando corro test_astar.py, que según yo, es porque en Open siempre hay o 0 elementos o 1

Esto creo que es un error, porque open debería poder guardar más nodos.

Parece que al sacarlos e insértalos devuelta hay un error en los Heaps, como muestran en esta issue #129, lo que hace que no se encuentre una solución correcta porque desaparecen los nodos.

En la issue #88 explican más o menos que se espera en esta parte, que en resumen es solo modificar `fvalue` para ver el desempate.

**Comment by beatrizacuna** [comment]
Sii es que solo estoy modificando fvalue, pero como uso extract e insert, la open no me está funcionando bien. La solución es sin el uso de estos? 
Edit: use otra implementación sin insert y extract
