### ISSUE TITLE
[Tarea 2] [3.3]

### ISSUE THREAD

**Issue by CataAlamos** [UC-IIC2613/Syllabus#136]
Hola, ¿En esta pregunta nos piden demostrar como lo hicimos en la ayudantía o con palabras basta?
Gracias de antemano

**Comment by jcechavarri** [comment]
Hola!

La idea de las demostraciones es que quede le quede claro a una persona escéptica de por qué se cumple la tesis. Si consideras que con palabras logras convencer a alguien de que la cota es correcta puedes hacerlo!  (siempre y cuando expliques detalladamente y paso a paso).
