### ISSUE TITLE
[Tarea 2][1.3] 

### ISSUE THREAD

**Issue by tvallotton** [UC-IIC2613/Syllabus#137]
Si es que se me ocurrió un problema que es O(n^2) cuenta como ejemplo? o tiene que ser estrictamente O(exp(n))?

**Comment by jmopaso** [comment]
Hola, es necesario que sea O(exp(n)). 

Esto es, si es que con la solución con regla de empates el rendimiento es O(n), entonces para el caso de la solución ocupando la regla de empates contraria el rendimiento es O(exp(n)).

Saludos
