### ISSUE TITLE
[Tarea 2][Pregunta 2.4] Ubicación de linear_conflicts 

### ISSUE THREAD

**Issue by aicnelavs** [UC-IIC2613/Syllabus#138]
¿Puede ser que el linear_conflicts del que se habla en la 2.4 es el que está implementado en el archivo puzzle_nn_new.py de la parte 3? Es que lo estaba buscando en la Parte 1 (donde dice que está) y no lo encontré, pero si hay uno en la otra parte que se llama así.

**Comment by jmopaso** [comment]
Hola! Tienes razón en la pregunta debiese aparecer `En el archivo puzzle_nn_new.py ...` en vez de `En el archivo puzzle.py ...`. Gracias por avisar!

Saludos
