### ISSUE TITLE
[Tarea 1] Duda Parte 2.1

### ISSUE THREAD

**Issue by jorge-ovalle** [UC-IIC2613/Syllabus#14]
Hola! Tengo una consulta con respecto a la parte 2.1. Entiendo que si hay un ciclo, por ejemplo: a->b->c->a, el modelo debiera, entre otras cosas, mostrar `camino(a, a, 3n)` para todo `n>=1`. Esto claramente haría que el programa no terminase.  Mi pregunta es cómo debo restringir con `#count` porque el enunciado explicita que se deben contar todos los caminos sin ciclos, pero también dice que no se deben ignorar los caminos con ciclos. Entonces, debería considerar los caminos `camino(a, a, 3n)`, pero eso implicaría que mi programa corriera eternamente.

**Comment by aamedinaj** [comment]
Si te fijas #count usa notación de conjunto `{cosas : restricciones}`, esas restricciones son las que te van a ayudar con lo que se busca

🦊

**Comment by jorge-ovalle** [comment]
> Si te fijas #count usa notación de conjunto `{cosas : restricciones}`, esas restricciones son las que te van a ayudar con lo que se busca
> 
> 🦊

Sisi eso entiendo. Mi pregunta va en la dirección de lo que dice el enunciado de no ignorar tampoco los caminos con ciclos. Si fuera así debería considerar, según mi ejemplo, todos los caminos `camino(a, a, 3n)` que serían infinitos. Por lo mismo, qué debo cortar o restringir. Eso no me queda claro.

**Comment by aamedinaj** [comment]
Ya, en el enunciado dice que tu programa debe 
> ser capaz de contar el largo de todo camino sin ciclos existente en el grafo

Y , considerando tu ejemplo, sí hay una manera de considerar ESE ciclo, pero __sin la necesidad de contarle todas las vueltas__ (pero si te la digo te respondo la pregunta de la tarea ~y me pegan~ ). Si aún te quedan dudas sigue preguntando, pero te recomiendo que no te compliques en contar los 3*n pasos, para cada n.

🦊

**Comment by Aloncarrasco** [comment]
Osea, estas diciendo que debo considerar camino(a,a,n) pero no el camino camino(a,a,2n)?

**Comment by jorge-ovalle** [comment]
> Osea, estas diciendo que debo considerar camino(a,a,n) pero no el camino camino(a,a,2n)?

Tengo la misma pregunta

**Comment by aamedinaj** [comment]
Exacto, no es necesario re-contar los ciclos. Para `a` debería bastar
```
camino(a,b,1)
camino(a,c,2)
camino(a,a,3)
```

🦊
