### ISSUE TITLE
[Tarea 2][Implementacion linear_conflicts]

### ISSUE THREAD

**Issue by Huasito-Appel** [UC-IIC2613/Syllabus#140]
Hola, la verdad me esta costanto entender bien como funciona el codigo de implementacion de conflictos lineales.
![image](https://user-images.githubusercontent.com/62345634/120270744-1c348480-c278-11eb-96a2-5d44b133c73f.png)

entiendo que el doble for cuanta la cantidad de conflictos que tenemos y los mete a esta arrays counts, luego dentro del else de la linea 140 vamos "descontando" o solucionando cada conflicto y le agregamos costo 1 a esta operacion, por el costo manhattan, lo que no entiendo bien es que hace la linea 138-139, por si me puedes explicar, ademas de corregirme si entendi algo mal de lo otro.
Gracias de antemano

**Comment by ebrzovic** [comment]
Hola, 

Tu razonamiento está correcto, también lo entendí de esa manera.  Lo que entiendo es que en el caso de que no haya conflictos o todos los conflictos previos han sido solucionando, retorna un valor ans*2 que puede ser 0 en caso de que no haya conflictos o  la cantidad de conflictos que ya se han solucionado previamente. 

Saludos

**Comment by Huasito-Appel** [comment]
claro, me hace sentido, gracias.
