### ISSUE TITLE
[Tarea 2] [Pregunta 3] Enunciado

### ISSUE THREAD

**Issue by tomasalvarez13** [UC-IIC2613/Syllabus#142]
Hola, en la 3.6 no entiendo si se nos pide hacer una comparacion del algoritmo de la pregunta 3 con cota N vs el algoritmo de la pregunta 1 con peso N, o comparar los diferentes resultados del algoritmo de la pregunta 3 con peso y cota N.

**Comment by jmopaso** [comment]
Hola! 

Como bien dices, en la 3.6 se pide la comparación entre el algoritmo `Preferred A*` modificado en la parte 3 vs el `Weighted A*` de la parte 1. La idea también es que la comparación sea usando el mismo valor para el peso (Weighted A*) y para la cota de suboptimalidad (Preferred A*).

Saludos!
