### ISSUE TITLE
[Tarea 2][3.2] Suboptimalidad

### ISSUE THREAD

**Issue by raimundoloeser** [UC-IIC2613/Syllabus#144]
Hola,
Tengo una duda con la suboptimalidad en la parte 3.2
Implementando el metodo estimate_suboptimality me surgió la duda de que no me llega a 1.0 la maxsubopt cuando lo corro con suboptimality 1.0 (y poniendo prints dentro de mi metodo, me aparecen valores más bajos que el Goal que lo encuentro muy raro). También me gustaría saber por qué el default de suboptimality en PrefAstar es 1.5? tiene alguna razon? como que no pueda llegar a 1.0?
Gracias

**Comment by diegomendieta** [comment]
Hola, como dice el enunciado, se entrenó una red neuronal para determinar, a partir de un estado del juego, la acción óptima a tomar. Esto se hizo mediante aprendizaje reforzado, contenido que van a ver dentro del curso. Como la cantidad de estados es tan grande, la red neuronal no es capaz de aprender una política perfecta (es decir, que para cada situación a la que se vea enfrentada, tomar la decisión óptima), aunque sí una bastante buena. Es por esto que, si le pides suboptimality 1, le estás diciendo que necesitas que tu solución sea la óptima, y puede que el algoritmo, usando la red como heurística, se demore mucho tiempo en encontrarla.

**Comment by bjbarias** [comment]
respecto a lo primero que puso Raimundo, no será que la cota está al revés? Copié la cota de la ayudantía y me salen solo valores <= a 1 (si lo doy vuelta salen mayores o iguales a 1, que hacría sentido)
