### ISSUE TITLE
[Tarea 2] Duda formato de entrega. Estructura proyecto

### ISSUE THREAD

**Issue by kylevon** [UC-IIC2613/Syllabus#145]
Hola,

¿Cómo específicamente debe ser la estructura de la tarea?

¿Se puede incluir el directorio T1 de la tarea pasada?

¿Se pueden agregar archivos que no se pidieron específicamente?

¿Se puede agregar el código en carpetas internas, por ejemplo. T1/Parte1/codigo/astar.py junto a todos los otros archivos de la base de la tarea?

**Comment by ebrzovic** [comment]
Hola 😊

Sobre la estructura depende exclusivamente de la pregunta. En el último párrafo de cada pregunta se especifica que se debe entregar en cada parte. Generalmente las preguntas teóricas se responden en un PDF mientras que las preguntas de programación se responden en un archivo indicado modificado.

Sobre el directorio sí, no es necesario que lo borren.  Lo importante es que todo lo relacionado con la tarea 2 debe estar en el directorio de la tarea 2.

Sobre los archivos que no se pidieron, no habrá ningún descuento por incluir más archivos.

No se puede agregar el código en carpetas internas.  

Espero haber podido ayudarte.

**Comment by kylevon** [comment]
Sí gracias! 😊
