### ISSUE TITLE
[Tarea 2][Pregunta 2.1 a]

### ISSUE THREAD

**Issue by beatrizacuna** [UC-IIC2613/Syllabus#146]
Hola! Quería saber si para la demostración de esta pregunta puedo empezar por la premisa de que f(s) <= f(s') o algo por el estilo?

**Comment by ebrzovic** [comment]
Hola Beatriz
Para ese problema te recomiendo usar las propiedades de consistencia ósea;
-	h(s) = 0, para todo s ∈ G 
-	h(s) ≤ c(s,s′) + h(s′), para todo vecino s′ de s. (s=Padres, s′= Hijos)
Saludos

**Comment by beatrizacuna** [comment]
o sea esas propiedades son las que tengo que demostrar o no? o tengo que probar que se cumplen para el puzzle de 15?

**Comment by ebrzovic** [comment]
No tienes que demostrar esas propiedades.  Puedes utilizar las propiedades de consistencia para demostrar que la suma de distancias Manhattan es una heurística consistente para el puzzle de 15.
