### ISSUE TITLE
[Tarea 3][Pregunta 1] Duplicados en datos y sesgo al modelo

### ISSUE THREAD

**Issue by sofiacorreabusquets** [UC-IIC2613/Syllabus#149]
¡Hola! Tengo una duda respecto a cuánto tenemos que confiar, y cuánto podemos incidir, en la calidad del set de datos que se nos entrega inicialmente. Estaba procesando los datos asumiendo que todos los valores del atributo `pixels` serían distintos, porque cada foto aparecería una sola vez en el set de datos. Por el contenido de clases, entendería que fotos repetidas sesgarían el modelo. Sin embargo, lo probé con `duplicated` y me descolocó el output:

![image](https://user-images.githubusercontent.com/61999464/122226018-8dcd1f00-ce83-11eb-8074-10fbd3509a7f.png)

Esto es sin haber hecho ningún cambio en los datos iniciales aparte de estructurarlos como `pandas.DataFrame`. No sólo me encuentra 685 filas completas del set de datos que se repiten, sino que además ese número sube a 845 cuando considero solamente la columna de `pixels`. Para explicar esos 160 datos de diferencia sólo se me ocurren 2 opciones: o bien el dataset contiene instancias que etiquetan la misma foto con distintas clases —y por tanto hay datos mal etiquetados—, o bien el dataset sugiere usar la misma imagen etiquetada para 'Test' y 'ToV'. La última explicación necesariamente me generaría un modelo que 'hace trampa' incluyendo instancias de _train_ en _test_, ¿no?

**¿Hay alguna manera de explicarse estos duplicados que no refleje mal sobre la calidad del dataset? Si no la hay, ¿cuánta libertad tengo de filtrar el dataset para lidiar con eso?** ¡Gracias de antemano!

**Comment by chris-carstens** [comment]
Hola! @sbcorrea
Muy buen comentario. 
En general hay que recordar que las bases de datos en la vida real en ningún caso son perfectas, y se pueden dar outliers o incluso errores dentro. Por lo mismo la etapa de **preprocessing** es clave en estos modelos. Ahora en este caso, la fracción es baja, y puedes tomar decisiones en base al análisis que hagas de los datos que encontraste duplicados. Por ejemplo, si analizas los datos duplicados y te das cuenta que se da cierta tendencia anormal, quizás te convenga eliminarlos por completo, o en caso contrario eliminar solo las versiones duplicadas.
Al final, depende de el análisis lo que convenga, aunque probablemente la solución es simple y convenga eliminar solo las versiones duplicadas y utilizar el original.
No es lo esperado, pero en teoría también podrían salir otras anomalías que dependen de la profundidad del análisis de la bdd que hagan.
De todos modos no te preocupes, al final es un detalle que si no detectan no restará en su evaluación 
Saludos!
