### ISSUE TITLE
[Tarea 1] Funcionalidad de Parte 2.1

### ISSUE THREAD

**Issue by benjavicente** [UC-IIC2613/Syllabus#15]
En el enunciado se menciona que
> Ahora **propón una manera de evitar el problema** que se genera en un grafo con ciclos usando el operador
`#count` (...)

¿Eso quiere decir que tenemos que **solo proponer una solución teórica** o tenemos que hacer funcionar esta manera?

**Comment by dtgazmuri** [comment]
Debes programarlo y hacerlo funcionar.

**Comment by FelipeLara00** [comment]
Pero en la parte que dice que debemos entregar sale que la pregunta 1 y 4 de la parte 2 van en respuesta.pdf
