### ISSUE TITLE
[Tarea 3][Pregunta 2] Extracción de características

### ISSUE THREAD

**Issue by gicrot** [UC-IIC2613/Syllabus#150]
Hola!
Leyendo e implementando la tarea, me quedó una duda del enunciado sobre qué se espera que hagamos para la extracción de características, que no se si me piden crear los modelos usando las landmarks como características, o si podemos usar las landmarks para extraer otras características en base a estas.

**Comment by szabala** [comment]
Me sumo a esta duda, ¿tenemos libertad para extraer las features que queramos de las imágenes? El enunciado se pega un salto desde estudiar las imágenes a entrenar los modelos.

**Comment by IngElecPuc** [comment]
Hola
Cuando diseñé esta tarea quería que les saltara esa duda, pues es algo con lo que todos los que vayan a trabajar con este tipo de problemas (ciencias de datos en general). Para dejar las cosas claras a nivel general el esquema a modo de pasos es el siguiente:
1.- Aprender el dominio del problema: aprender sobre el problema en sí, sus variables generales y fenómenos asociados. En este caso se menciona en el enunciado, pero suele ser un proceso más largo cuando uno se sumerge en un proyecto.
2.- Selección y adición de datos: tomar muestras, construcción o selección de un set de datos. Aquí se les está pasando un set de datos, no es necesario construir uno. 
3.- Preprocesamiento: Extracción de características útiles y limpieza de datos. En este punto están situadas sus dudas, los detalles se los aclaro más abajo.
4.- Transformación: Se adecúan los datos para formatearlos según los requerimientos de entrada de los modelos. En esta etapa se crean las matrices de características y los vectores de etiqueta. También se pueden crear aquí los sets de entrenamiento, validación y test si es que no vienen pre-separados (esto último es más general).
5.- Minería de datos: Eso se refiere al entrenamiento de los modelos, y la búsqueda de hiperparámetros adecuados. El término es relativo a una disciplina llamada con el mismo nombre, pero es genérico a todas las ciencias de datos.
6.- Evaluación e interpretación: Se evalúa el modelo entrenado y sus capacidades, Se interpretan sus alcances y otras cosas analizadas correspondientes a la fenomenología del problema.
7.- Descubrimientos y visualizaciones: Sería finalmente lo que entregue la etapa conclusiva. ¿Se lograron los objetivos? ¿Se necesita otro tipo de modelos? ¿Se aprendió algo nuevo del problema? (El objetivo genérico de las ciencias de datos es crear nuevos datos a partir de un grupo existente, en esos nuevos datos están estos descubrimientos)

Con respecto a lo que ustedes preguntan. En general, deben trabajar con la extracción de datos que nosotros les estamos exigiendo, eso significa que tienen que utilizar dlib para extraer los landmarks. No pueden agregar otros extractores. Puede que les aparezcan outliers, esto es, algunos elementos que se escapan del dominio del problema, no aportan información, o esa información es ruidosa o poco confiable. Deben poder manejar esos casos, y justificar los criterios que utilicen. Nos importa más la justificación de su criterio, que una aplicación bien hecha, pero no justificada, ojo con eso.
Finalmente, sí pueden preprocesar los landmarks como ustedes deseen. Bien sea eliminar algunos que crean que no sean útiles, aplicar transformaciones a los landmarks, entre otras opciones. Eso es parte de lo que tienen disponible como rango de acción.
Saludos
Felipe Ríos
