### ISSUE TITLE
Clase 27 grabación 

### ISSUE THREAD

**Issue by oerlandsen** [UC-IIC2613/Syllabus#151]
Hola! podrían subir la grabación de la clase?
Saludos!

**Comment by FeBalla** [comment]
> Hola! podrían subir la grabación de la clase?
> Saludos!

Hola! Mil disculpas, cambiamos el sistema hoy para tenerles las clases subidas antes, pero por algún motivo no se publicó (lo dejamos listo en la mañana 😢 ). No volverá a suceder. Mucho éxito!
