### ISSUE TITLE
[Tarea 3] Distribución de puntajes

### ISSUE THREAD

**Issue by sofiacorreabusquets** [UC-IIC2613/Syllabus#152]
¡Hola! Quería preguntar si cada una de las 6 preguntas de la Tarea 3 equivale a un punto de nota, y/o si tendremos acceso al detalle de la distribución de puntajes como el que estaba integrado en los enunciados anteriores. ¡Gracias de antemano!

**Comment by aamedinaj** [comment]
Hola
La respuesta es bien simple en realidad. La cantidad de puntos es pareja para toda la tarea: 1 punto cada pregunta

🦊

**Comment by sofiacorreabusquets** [comment]
Gracias!
