### ISSUE TITLE
[Tarea 3] Libreria para mostrar imagenes

### ISSUE THREAD

**Issue by sebaelsaca** [UC-IIC2613/Syllabus#153]
Hola, dado un set de pixeles, podemos ocupar cualquier libreria para desplegar la imagen con tales pixeles?

**Comment by chris-carstens** [comment]
Sí, puede que ocupes una librería o combinación para procesar y visualizar. Mientras se muestre correctamente está bien.

**Comment by sebaelsaca** [comment]
Gracias @chris-carstens, otra pregunta que tenía es si es obligación ocupar google colab o no, ya que hice todo en un jupyter notebook sin google colab.

**Comment by chris-carstens** [comment]
No hay problema, simplemente como recomendación se suele usar más colab por las prestaciones de hardware que tiene. Probablemente para correr los modelos más rápido te sirva usar  GPU de colab también, puede que se te demore mucho sin ella.

**Comment by IngElecPuc** [comment]
Dentro de las opciones más recomendadas: Pillow, OpenCv, el comando display de Colab, Matplotlib, e incluso openpifpaf tiene unos códigos que vimos en la ayudantía con los que se puede desplegar la imagen
