### ISSUE TITLE
[Tarea 3] Posición de landmarks fuera de la imagen

### ISSUE THREAD

**Issue by gustavobarrezueta** [UC-IIC2613/Syllabus#154]
Hola! Me surgió una duda calculando los landmarks de las imágenes, ya que algunas marcas quedan fuera de la imagen misma. Por ejemplo, si pensamos que el eje x va desde 0 a 40, existen landmarks que se ubican en valores negativos de x y, por tanto, quedan fuera de la imagen. No me esperaba este resultado y por eso quería preguntar si es que es normal que ocurra eso y simplemente no considero esos puntos que quedan fuera de la imagen o debo encontrar una forma que se calculen landmarks solo dentro de la foto.
Desde ya muchas gracias por la ayuda!

**Comment by amahns1** [comment]
Me sumo a la pregunta, mantenemos los _landmarks_ que están dentro de la imagen? O esos _landmarks_ que están afuera (con coordenadas negativas) equivalen a una "proyección" de la cara y por lo tanto hay que mantenerlas?

**Comment by IngElecPuc** [comment]
En tal caso el landmark es una predicción de la librería dlib. Tienes que resolver esto según si serviría o no como una característica para el reconocimiento. ¿Invalida este rasgo el ponerla en la matriz de características? En ese caso si la quitas o descartas tienes que mencionar el porqué. Ahora, si se trata de solamente desplegar la imagen, no te va a caber en la original, puedes o bien ampliar la imagen como si estuvieses agregando ejes que no existen, o simplemente no agregar ese punto al desplegarla. 
En ambos casos es importante el uso del criterio, y eso depende de ustedes. Lo que nos importa es que, independiente del criterio que utilicen, que lo puedan justificar.
