### ISSUE TITLE
Definición o calidad de la imagen

### ISSUE THREAD

**Issue by amahns1** [UC-IIC2613/Syllabus#155]
Hola!

Espero que estés muy bien :)

Quería preguntar si es importante mantener la calidad de la imagen. Como las imágenes están en formato 48X48, es un poco difícil visualizarlas sobretodo con los _face_landmarks_. ¿Está bien si se pierde la definición o calidad de la imagen al mostrarlas con y sin _landmarks_?.

Muchas gracias!!

**Comment by aamedinaj** [comment]
Si las imágenes vienen en ese formato no hay problema que así se queden, si quieres mostrar los landmarks puedes mostrar "pares de fotos" en el mismo output:

[FOTO ORIGINAL SIN LMs][MISMA FOTO AGREGANDO LOS LMs].

🦊
