### ISSUE TITLE
[Tarea 3] Definir el Modelo 

### ISSUE THREAD

**Issue by CataAlamos** [UC-IIC2613/Syllabus#157]
Hola, en la pregunta 2 de la tarea, ¿Es necesario decir qué modelo vamos a usar o sólo como se está dividiendo el set de entrenamiento y validación?

**Comment by aamedinaj** [comment]
Hola, 
Es buena idea ir indicando qué se está haciendo en cada paso, el enfoque es evaluar si entendieron cómo usar los distintos sets y los distintos modelos. Aprovechen que es un colab y se puede añadir harto texto entremedio de cada celda de código 

🦊

**Comment by IngElecPuc** [comment]
Hola
En la propia pregunta 2 dice "Explique y justifique". Así que sí, deberías explicar esas cosas. Has uso de las herramientas de texto como te lo indica Pavel.

**Comment by DiegoEmilio01** [comment]
Para justificar la toma de decisiones se puede utilizar información expuesta en clases (citando el uso del material) o en ese caso debo investigar fuentes externas que expogan la teoría? Muchas gracias de antemano

**Comment by aamedinaj** [comment]
Pueden ser ambas, lo que más te acomode

🦊
