### ISSUE TITLE
[Tarea 3] Problemas al instalar face_recognition

### ISSUE THREAD

**Issue by josejimenezp** [UC-IIC2613/Syllabus#159]
Hola, me sale este error cuando intento instalar la librería :(

![image](https://user-images.githubusercontent.com/48298035/122703879-83fb4100-d220-11eb-8ea2-ba8397fe0dc8.png)
![image](https://user-images.githubusercontent.com/48298035/122703904-92495d00-d220-11eb-9f41-38a9ac56be07.png)

**Comment by chris-carstens** [comment]
Hola! Antes de arreglar el error, por qué no usas colab mejor?
(Y si aún así prefieres correrlo en local, te recomiendo usar un virtual env para no descargar todas las librerías, que pueden ser bien pesadas, en tu path global de python)

**Comment by IngElecPuc** [comment]
Para utilizarlo en tu computador local tienes que tener una GPU configurada con los drivers. Eso es bastante trabajo, y no queremos que entren en eso (a menos que ya lo sepan hacer). Mejor hacer lo que dice Christian, Google Colab es un ambiente que debería dar acceso a todos al uso de ese hardware, y así todos pueden tener más o menos la misma oportunidad, y no vérselas solos con sus propios recursos.

**Comment by josejimenezp** [comment]
Hola, sigo teniendo problemas con Google Colab

![image](https://user-images.githubusercontent.com/48298035/122849977-7a361400-d2da-11eb-9219-e109d5b0512a.png)
