### ISSUE TITLE
[Tarea 1] Duda input parte 4.1

### ISSUE THREAD

**Issue by catalinamusalem** [UC-IIC2613/Syllabus#16]
Hola! Me podrían dar un ejemplo de como se ve el input sensorial? O que tipo de información contiene?

Muchas gracias!

**Comment by aamedinaj** [comment]
Si recuerdas, el profesor comentó en una clase que en el "mundo del Wumpus" hay entradas sensoriales para el agente (jugador) tales como "brisa" o "hedor". En el archivo `extra.lp` se indica de qué tipo es la entrada sensorial, y en qué casilla se encuentra:
>sense_breeze(1,3).
sense_stench(0,2).

🦊

**Comment by catalinamusalem** [comment]
En el archivo extra.lp me queda la duda sobre que es safe(1,1)?
Gracias

**Comment by aamedinaj** [comment]
Hola, primero que todo, el _extra.lp_ fue uso exclusivo del profesor (es el ejemplo del enunciado). No es necesario que el suyo se llame exactamente _safe_, pero era para indicar que era una casilla que, con seguridad, era segura. 
Recomendación: no le des tantas vueltas a ese punto en particular.

🦊
