### ISSUE TITLE
[Tarea 3] Duda respecto a lo que retorna face_landmarks(image)

### ISSUE THREAD

**Issue by FelipeA7** [UC-IIC2613/Syllabus#160]
Hola, estaba en la pregunta 1 tratando de mostrar los landmarks de una foto de cada emoción, pero no entiendo muy bien que es lo que retorna el método fr.face_landmarks(image). En un principio pensé que retornaba las ubicaciones de cada punto en la imagen, pero al hacer un print de los resultados me dan coordenadas negativas y otras que son mayores a 48 (siendo que la imagen es de 48x48)
Traté de buscar en internet pero no encontré resultados útiles.
![image](https://user-images.githubusercontent.com/48482398/122825748-55c54200-d2b0-11eb-9bc6-1792fe413a67.png)

**Comment by JupaOlivares** [comment]
Hola tengo el mismo problema, no se si es problema de formato o así debería ser el output y no lo estamos interpretando como se debe

**Comment by IngElecPuc** [comment]
Hola 
Este tema ya se había preguntado antes. #154.
Saludos

**Comment by JupaOlivares** [comment]
> Hola
> Este tema ya se había preguntado antes. #154.
> Saludos

La issue estaba cerrada y no me aparecia! Gracias
