### ISSUE TITLE
[Tarea 3] Arquitectura de ensamblaje de clasificadores

### ISSUE THREAD

**Issue by gicrot** [UC-IIC2613/Syllabus#161]
Hola, no sé a que se refiere en la pregunta 6 con diseñar una arquitectura de ensamblaje de clasificadores, por si lo vimos en una clase y se me pasó o si tienen algún ejemplo de a que se refiere esto, ya que piden un diagrama sobre esto igual.

**Comment by IngElecPuc** [comment]
Hola Gerardo
Por el momento, te puedo contestar que un ensamblaje es una combinación de las técnicas de clasificación. Esa combinación puede tomar muchas formas, pueden ser en cascada, en paralelo, puede ser una red de técnicas, etc. Cada etapa va a mover los datos a un nuevo espacio, puedes pensar en que cada modelo sería algo así como una transformación. La idea es que se puedan combinar las técnicas para tener un modelo que gane varias de las ventajas de los otros, y se reduzcan también sus desventajas "ayudándose cada modelo con el otro". Te recomiendo que hagas la investigación que te pide la pregunta. Así verás de primera mano porqué se hace esto.
Saludos

**Comment by NickCastillo** [comment]
Hola! Con respecto a esta misma pregunta. Si encontramos que en vez de hacer X (tipo de características por ejemplo) hubiera sido mejor hacer Y, podemos hablar de una arquitectura de ensamblaje para mejorar el rendimiento pero considerando el uso de Y? o deberíamos seguir con las ideas iniciales X?

**Comment by IngElecPuc** [comment]
La arquitectura se pide a un nivel mayor de abstracción. El entregable tiene forma de diagrama o psudocódigo (el primero es más adecuado). Dicho esto, tal nivel de abstracción lo puede hacer independiente de la forma de la matriz de características, de manera que se pueda adaptar a varias matrices. Esto implica que no importa la cantidad exacta de características.
