### ISSUE TITLE
[Tarea 3] hiperparámetro slack en SVC

### ISSUE THREAD

**Issue by szabala** [UC-IIC2613/Syllabus#162]
Hola, en el enunciado se indica que:

> Para los clasificadores SVM y arbol de decisión haga un estudio de hiperparámetros, utlizando el método set_params. Con SVM seleccione tres valores de kernel y cinco valores de _slack_

¿A que hiperparámetro del SVM se refieren con _slack_? Leyendo la [documentación](https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html#sklearn.svm.SVC) del clasificador que nos piden utilizar no encuentro ningún hiperparámetro que regule el uso de variables de _slack_. Agradezo de antemano por la aclaración 😄

**Comment by aamedinaj** [comment]
Hola, 
El hiperparámetro al que te refieres es la C, que regula el segundo término a optimizar en el problema de optimización asociado a SVM

🦊

**Comment by szabala** [comment]
Super, gracias!
