### ISSUE TITLE
[Tarea 3][pregunta 1] Dlib retorna las caras dadas vuelta

### ISSUE THREAD

**Issue by gsalinas0** [UC-IIC2613/Syllabus#163]
Hola. Estoy en la pregunta 1 intentando graficar los landmarks. Me pasa que con todas las caras que intento analizar, `dlib` las devuelve todas dadas vuelta. He intentado de todo para darlas vuelta pero no se como, ¿alguna recomendación (o alguien a quien le pueda mostrar mi código :sweat:)?. ¿Tiene esto que ver con que algunos de los valores predichos por `dlib` sean negativos?
Por ejemplo, con la imagen numero 40 me tira esto:
![image](https://user-images.githubusercontent.com/68198662/122860422-ad34d380-d2eb-11eb-8c4f-bb0f94a15e38.png)
![image](https://user-images.githubusercontent.com/68198662/122860438-b4f47800-d2eb-11eb-9a10-2a90e759c6e2.png)
Y si invierto las coordenadas que me retorna `dlib`, obtengo esto:
![image](https://user-images.githubusercontent.com/68198662/122860531-dfdecc00-d2eb-11eb-88ed-e7d0cb236da2.png)

**Comment by dfloreaa** [comment]
A mi me ocurrió algo parecido y creo que te puedo ayudar, el tema es que si te fijas en los ejes de coordenadas, para tu imagen el eje _y_ va desde 48 a 0 (de abajo hacia arriba) y tu eje _x_ desde 0 a 48, por tanto, y esta "invertido", pero a la hora de trabajar con los puntos _y_ va desde 0 a 48 y _x_ de 0 a 48 también.

![image](https://user-images.githubusercontent.com/62019645/122964007-d473bb00-d354-11eb-853b-6519abde8299.png)
vs
![image](https://user-images.githubusercontent.com/62019645/122963849-a8f0d080-d354-11eb-90ec-0bc72c949201.png)

Aquí se nota un poco mejor, para que tengas la misma imagen a ambos lados, debes hacer que tu eje y vaya desde un mismo valor abajo hasta un mismo valor arriba

Ojalá te sirva!

**Comment by gsalinas0** [comment]
Ahh bueena, muuchas gracias!

**Comment by IngElecPuc** [comment]
Hola
El estándar para trabajos con imágenes es siempre con el origen el la esquina superior izquierda, el eje x crece hacia la derecha, y el eje y siempre crece hacia abajo. Además, con imágenes RGB, el primer canal es rojo, el segundo verde, y el tercero azul. Eso no nos importa aquí, pero es por si después les interesa trabajar con imágenes.
Saludos
