### ISSUE TITLE
[Tarea 3] ¿Qué es específicamente una matriz de características?

### ISSUE THREAD

**Issue by dfloreaa** [UC-IIC2613/Syllabus#164]
Hola, cuando en el enunciado se menciona que `Construya las matrices de características X, y los vectores de etiquetas y correspondientes a cada set.`, a qué se refiere específicamente, entiendo que y son las labels para los datos, pero ¿qué son las matrices de características? No encuentro nada sobre ellas en internet

Se referirán por ellas a un array de numpy (o el formato en que uno prefiera) que contiene la información relevante sobre los datos? De ser así, cuando nos dicen que debemos construirlas se refieren a armarlas y almacenarlas en nuestro dataset?

Muchas gracias de antemano :)

**Comment by aamedinaj** [comment]
Hola,

Las matrices de caracteristicas pueden ser arrays, dataframes, etc. que contienen la información que tú consideras necesaria para hacer la predicción. Un ejemplo básico es cuando vieron árboles de decisión: cada fila era una instancia, y cada columna era una caracteristica (outcast, nublado, viento, etc).
En esta tarea es esencialmente lo mismo, solo que las columnas no son tan explicitas,  es tarea tuya definir qué entenderás por características (y justificarlo donde corresponda).

Espero eso te explique más, intenté no darte la solución explicita,  por eso lo ambiguo.

🦊
