### ISSUE TITLE
[T3][Colab] Colab funciona mal

### ISSUE THREAD

**Issue by tocococa** [UC-IIC2613/Syllabus#165]
Hola! 
Es normal que Colab funcione lento? Se demora en abrir nuevas celdas, anda a tirones cuando uso markdown en una celda de texto, tarda en registrar input y además se desconecta cada cierto rato y tengo que volver a ejecutar todas las celdas, tampoco me guarda lo que he ejecutado si cierro la pestaña y la vuelvo a abrir, cada vez que abro el proyecto tengo que volver a instalar face_recognition y actualizar PIL.
No se si es comportamiento normal o estoy usando mal Colab y me tiene bastante lateado porque me estoy demorando mucho más en hacer la tarea de lo que siento que debería estar tardándose.

**Comment by chris-carstens** [comment]
Hola! @tocococa lo que sí es normal es que al cerrar colab tengas que correr nuevamente las celdas para descargar las librerías o datos, porque se almacena solo durante la sesión, pero no debería demorar mucho la descarga. Recuerda usar colab con la GPU para que te corra más rápido el programa. Si el tema es que tu pc anda lento, te recomiendo cerrar otras pestañas de chrome o tareas del pc, el hardware que nos presta colab a todos es el mismo así que, al menos en eso, deberías tener la misma velocidad que todos.

**Comment by tocococa** [comment]
Ya probé con eso :'c, no creo que sea mi PC porque es un tarro más o menos potente, pero lo que me tiene más lateado que el input lento o demás, es que mientras ocupo Colab se desconecta y ahí tengo que volver a ejecutar todas las celdas, voy a ver si logro instalar face_recognition localmente y no usar Colab nomás, porque estaba averiguando un poco más y me tinca que es culpa de Google que no optimiza para Firefox. 

Gracias por la respuesta igual!
Edit:
![image](https://user-images.githubusercontent.com/22779371/123027386-c1400a00-d3ab-11eb-951d-c5112f17383d.png)
![image](https://user-images.githubusercontent.com/22779371/123027902-90aca000-d3ac-11eb-9546-a609e90fdcc8.png)

**Comment by ezekiel39** [comment]
Mismo problema en chrome 2023... (El problema de la desconección)
