### ISSUE TITLE
[Tarea 3] Pregunta 2

### ISSUE THREAD

**Issue by CataAlamos** [UC-IIC2613/Syllabus#167]
Hola, ¿La matriz característica es de este estilo o sólo debe incluir los pixeles? 

En caso de que el formato que tengo este malo, ¿Qué debe incluir la matriz característica?
<img width="400" alt="Screen Shot 2021-06-22 at 17 31 08" src="https://user-images.githubusercontent.com/62016215/123002227-abb4eb00-d37f-11eb-8985-94b00969cffd.png">

Muchas gracias de antemano

**Comment by Huasito-Appel** [comment]
Me sumo a la consulta, no tengo claro del todo que debemos entregar, tanto para la matriz como para el vector y

**Comment by IngElecPuc** [comment]
Hola, te sugiero que revises este issue #164. 
Saludos
