### ISSUE TITLE
[Tarea 3] ¿Que clasificadores hay que usar?

### ISSUE THREAD

**Issue by joaquinhernandezg** [UC-IIC2613/Syllabus#168]
En la pregunta 3 dice "Entrene todos los clasificadores". A que clasificadores se refiere exactamente? De lo que dice a continuación se infiere que solamente SVM, Decision Tree y Naive Bayes, pero me queda la duda.

**Comment by aamedinaj** [comment]
Hola :D

En la introducción de las actividades (punto 4.1) dice 

> Para ello puede elegir un clasificador, bien sea SVM, Bayesiano ingenuo, o árbol de decisión, como estrategia
> inductiva.

Esos 3 modelos serían "todos"

🦊
