### ISSUE TITLE
uso de gdown

### ISSUE THREAD

**Issue by baseba** [UC-IIC2613/Syllabus#169]
Hola en la tarea nos indican qeu podemos usar el comando gdown  -id [id] para descargar los datos, no me queda claro el uso de este, se utiliza en consola? o se usa directamente en el colab?

**Comment by chris-carstens** [comment]
En colab puedes insertar un comando con un ! antes. Paricularmente debes usarlo así:
!gdown --id 1rR0CjYZDgMfZDVYlyPxJdYpDN1XH5AYq
