### ISSUE TITLE
[Tarea 1] 3.1 Typo Π

### ISSUE THREAD

**Issue by lucas-valenzuela** [UC-IIC2613/Syllabus#17]
Hola,
Puede ser que haya un typo en el enunciado y que el Π que señalo en la imagen sea realmente Π' ?

<img width="951" alt="Captura de Pantalla 2021-04-14 a la(s) 18 47 16" src="https://user-images.githubusercontent.com/48392863/114790065-10d1dc00-9d52-11eb-9ed7-eb24d49c1ce1.png">

**Comment by jfuentesg26** [comment]
Hola! Efectivamente hay un typo. El Π señalado en la imagen es un Π'. Se actualizará el enunciado durante el día con este cambio. 
Espero que esto no te haya generado muchos problemas y gracias por preguntar! :)
