### ISSUE TITLE
[Tarea 3][Pregunta 3] Uso de set_params

### ISSUE THREAD

**Issue by sperezmasri** [UC-IIC2613/Syllabus#170]
Hola! Es obligación el uso del método set_params? O se pueden ir creando modelos donde al instanciarlos le "setiemos" los parametros? Saludos

**Comment by fivaldivia** [comment]
Hola, en realidad es lo mismo si lo haces de una forma a otra. Aunque es mejor si lo haces con set_params como se pide en el enunciado, pero como más te acomode!
