### ISSUE TITLE
[Tarea 3] [Pregunta 3] Número de testeos de hiperparámetros

### ISSUE THREAD

**Issue by ignacio-urrutia** [UC-IIC2613/Syllabus#171]
Hola! En la pregunta 3 nos piden probar con diferentes hiperparámetros, por ejemplo para SVM debemos probar tres valores de kernel y cinco de slack, la idea es probar todas las combinaciones de esos valores (15 testeos) o probamos dejando uno constante en cada caso (8 testeos)? Lo mismo para árbol de decisión. 

Gracias y saludos

**Comment by IngElecPuc** [comment]
Hola
Tienes que hacer los 15 testeos y desplegar una tabla con los resultados de cada par. Lo mismo para el árbol de decisión.
Saludos

**Comment by ignacio-urrutia** [comment]
Bacán, muchas gracias. Lo otro: puede ser que con ciertos valores de C me corra con algunos kernel y con otros no?
