### ISSUE TITLE
[Tarea 3] [Pregunta 1] Imágenes sin face_landmarks

### ISSUE THREAD

**Issue by cristobalgon** [UC-IIC2613/Syllabus#172]
Hola, al empezar a hacer la tarea, me di cuenta de que hay algunas imágenes a las cuales les aplico el filtro de 'face_landmarks' y no me retornan nada (una lista vacía). Lo encuentro súper curioso, pero qué se podría hacer en ese caso??

Gracias! :)

**Comment by Huasito-Appel** [comment]
not, ayudante pero se contesto en otra issue (cuando la encuentre la tageo). basicamente era que no se lo pasaramos a los clasificadores.
