### ISSUE TITLE
[Tarea  3] Pregunta 3. Predicciones de los modelos muy similares

### ISSUE THREAD

**Issue by DiegoEmilio01** [UC-IIC2613/Syllabus#173]
Hola, las features que extraje funcionan relativamente bien. El problema es que los 3 modelos son muy parecidos en cuanto a resultados. El mejor y el segundo, en cuanto a accuracy, tienen menos de una milésima de diferencia. Por lo tanto, me parece que no puedo responder la pregunta y debería responder con otro enfoque. Por ejemplo, por qué todos se ajustan igual o ninguno destaca (en comparación con por qué es mejor uno que en realidad no es mejor).

Además, esto tal vez podría incidir en las siguientes preguntas. Lo que mas me preocupa es que se acepte un análisis en base a mis resultados a pesar que la pauta tenga sentido que uno sea mejor.

Muchas gracias de antemano, saludos.

**Comment by IngElecPuc** [comment]
Hola Diego
Me parece que tu enfoque es correcto. Al fin y al cabo es lo que puedes hacer con tus resultados. Ten en cuenta que es posible que hayas encontrado buenos hiperparámetros para los tres casos, y si tus resultados son buenos, entonces debes procedes como indicas.
Ten en cuenta, que uno de los métodos tiene pocas opciones para darle hiperparámetros, o la opción interesante requiere de un estudio intenso del set de datos que no estamos pidiendo. En nuestro caso, con una matriz de características que podría ser "típica" de construir ese método no dio buenos resultados. 
Si por alguna razón, has desarrollado un buen trabajo en el preprocesamiento de los datos, es bastante probable que todas las clasificaciones sean relativamente buenas (aunque casi siempre pasa que hay algún método que se queda atrás por la particularidad del problema). En ese caso considera que también podría ser esa la razón de tales resultados.
Saludos
