### ISSUE TITLE
[Tarea 3] [P1]

### ISSUE THREAD

**Issue by tomasalvarez13** [UC-IIC2613/Syllabus#174]
Hola, cuando nos piden 'desplegar  las  mismas  imágenes  ahora  utilizando  el formato que tiene la Figura 2', es necesario mostrar 2 imágenes (una con los landmarks y la imagen superpuestos y otra solo con los landmarks)? O con desplegar solo la con los landmarks superpuestos a la imagen está bien? Gracias

**Comment by fivaldivia** [comment]
Hola, debes mostrar ambas imágenes que se muestran en la Figura 2!

**Comment by tomasalvarez13** [comment]
Con respecto a esto, es estrictamente necesario que sea una al lado de la otra, o puede ser una abajo de la otra?
