### ISSUE TITLE
recorrecciones T2

### ISSUE THREAD

**Issue by javiermingo** [UC-IIC2613/Syllabus#176]
Hola! donde se puede hacer la recorreccion de la T2?

**Comment by FeBalla** [comment]
> Hola! donde se puede hacer la recorreccion de la T2?

Hola! El formulario para la recorrección se habilitará el sábado 26 de junio. Estábamos esperando un avance con la corrección de las tareas atrasadas y no lo habilitamos jueves y viernes por el receso académico.
