### ISSUE TITLE
[Tarea 3] Accuracy esperado

### ISSUE THREAD

**Issue by Brocoleta** [UC-IIC2613/Syllabus#177]
Hola, que accuracy deberia ser aceptable para el modelo, me esta dando aprox 40%, pero nose si esto es aceptable o se espera algo mucho mejor como 90%?

**Comment by gustavobarrezueta** [comment]
Hola! En esta misma línea me gustaría preguntar qué método debemos usar para medir el accuracy, ya que existen muchos en la librería.

**Comment by fivaldivia** [comment]
Hola @Brocoleta, nose en qué parte de la tarea te refieres pero en al comparación de modelos, más que un accuracy específico, te debiesen dar distintos accuracy, unos más altos y otros más bajos, con los cuales debieses poder sacar conclusiones y responder a las preguntas.

@gustavobarrezueta en cuánto a lo que preguntas, en el enunciado hay una parte donde se explica el `accuracy score` por lo que fíjate ahí. Sin embargo, cualquier método de la librería que entregue lo que se pide se puede usar.

**Comment by gustavobarrezueta** [comment]
Creo que había pasado por alto por completo esa parte, muchas gracias @fivaldivia!

**Comment by javier-ICO** [comment]
Me sumo a la duda de Brocoleta, creo que se refiere como al rango de accuracy que es suficiente para saber que lo que uno está haciendo está bien (como por ejemplo la calidad de las features), ¿Es razonable que el mejor de los modelos con los mejores hiperparámetros tenga una accuracy del 50%, o 70% o 90%?, por ejemplo, o es irrelevante?.
