### ISSUE TITLE
[Tarea 3][Pregunta 5]

### ISSUE THREAD

**Issue by Huasito-Appel** [UC-IIC2613/Syllabus#179]
Hola, Para esta pregunta me quedo con que los resultados era casi identicos, tengo un 1% de variacion respecto al accuracy y un par de cambios en la matriz de confucion, pero nada significativo. Por lo que no se muy bien como realizar esta pregunta ya que no tengo mucho analisis comparativo que hacer.
Quedo atento a sugerencias. Gracias

**Comment by joaquinhernandezg** [comment]
Me pasa exactamente lo mismo, mi accuracy y la matriz de confusión replican exactamente lo mismo del punto anterior.

**Comment by Huasito-Appel** [comment]
@joaquinhernandezg nos quedamos con las ganas :(

**Comment by FeBalla** [comment]
Se nos pasó esta _issue_ 😢 De todos modos, el análisis no tenía que estar estrictamente ligado a la precisión, sino que se podían considerar otras características. Espero hayas podido llegar a alguna respuesta:c
