### ISSUE TITLE
[Tarea 1] Duda programa a realizar Parte 4.1

### ISSUE THREAD

**Issue by fjquintana** [UC-IIC2613/Syllabus#18]
Hola!

Tengo una duda con el programa que hay que hacer en la parte 4.1. Lo que hay que hacer no es un programa que tenga un único modelo, en donde aparece **p** si y solo si el agente puede saber que **p** es verdad, sino más bien un programa que tenga varios modelos, y sea tal que el agente puede saber **p** si es que **p** aparece en todos los modelos, y que pueda saber que **q** es falso si es que **q** no aparece en ningún modelo, cierto?

Gracias!

**Comment by jmopaso** [comment]
Hola, es correcto lo que dices. Sólo un detalle, es un programa que, **en general, tiene múltiples modelos**, es decir, pueden haber casos en que te entrega sólo uno (cuando sólo hay un mundo posible).

**Comment by fjquintana** [comment]
Perfecto, muchas gracias!
