### ISSUE TITLE
[Tarea 3] [Pregunta 2] Máximo de características

### ISSUE THREAD

**Issue by antoniaalcayaga** [UC-IIC2613/Syllabus#180]
Hola, 

En la pregunta 2 tenemos que contestar  "¿Cuánto es el máximo de características que puede incluir en cada matriz X?"  y no entiendo la pregunta ni que es lo que quieren que respondamos, ya que no recuerdo que en clases pasáramos que la matriz tuviera que tener un número máximo de características y tampoco el programa me exigió que la matriz tuviera un tamaño especifico. Entonces mas que nada me gustaría que me explicaran la pregunta porque no entiendo a que se refieren.

Muchas graciaas :)

**Comment by IngElecPuc** [comment]
Hola
En un marco general es cierto que no se ponen límites a esa matriz, pero esto a nivel teórico. El tema a contestar es, ¿cuál es el máximo de características posibles para la matriz X para este problema, set de datos y herramientas dadas?
Saludos

**Comment by sofiacorreabusquets** [comment]
Hola, con respecto a esto mismo: ¿es significativo que se pregunte por *cada* matriz X? El conteo de características refiere ¿a la cantidad atributos para cada instancia, o a los atributos multiplicados por la cantidad de instancias en cada set? Pregunto porque el máximo solo difiere para *cada* matriz X (aquellas de train, test y val) si se considera su tamaño en instancias.

Gracias de antemano 🤗

**Comment by FelipeLara00** [comment]
Tengo la misma duda con respecto a la matriz de características X. Son el máximo de atributos que se deben poner en la matriz X? O se refiere a otra cosa?

Saludos!
