### ISSUE TITLE
[Tarea 3] Git Push

### ISSUE THREAD

**Issue by jorge-ovalle** [UC-IIC2613/Syllabus#181]
Hola! Git no me deja pushear el _jupyter notebook_  porque al parecer tiene almacenadas en el entorno de ejecución archivos de gran tamaño. Qué hago para poder subir el _notebook_ al repo?

**Comment by SarahEverke** [comment]
Hola, 
¿Te funciona guardarlo desde drive en github (Archivo > Guardar una copia en github)?
