### ISSUE TITLE
Datos que usar en preguntas 3 y 4

### ISSUE THREAD

**Issue by FelipeA7** [UC-IIC2613/Syllabus#183]
Hola, entiendo que al ir variando los parámetros, se debe ir evaluando con los datos de validación, pero luego para reportar las matrices de confusión yo estaba haciéndolo con los datos de testing. Después leí la pregunta 5 y recién ahí dice que se evalúe el modelo con los datos de testing. 
Entonces me salió la duda, en la pregunta 3 y 4 trabajamos solo con los de entrenamiento y validación? O los de validación los usamos para ajustar parámetros y luego la matriz de confusión la reportamos a partir de los datos de testing?

**Comment by IngElecPuc** [comment]
Hola
Es bien importante que hayas hecho esta pregunta. En general el set de validación está para buscar hiperparámetros. Y si vas reportando los resultados con ese set durante esta búsqueda entonces estás bien. Eso significa que en la pregunta 4 deberías utilizar el mismo set para reportar la matriz de confusión, a modo de término de tu proceso de entrenamiento. Ya en la pregunta 5 se te pide que utilices test, pues has cambiado de etapa, y la matriz de confusión de 4 ahora te sirve como herramienta de comparación para ver cómo generaliza tu modelo.
Saludos

**Comment by FelipeA7** [comment]
> Hola
> Es bien importante que hayas hecho esta pregunta. En general el set de validación está para buscar hiperparámetros. Y si vas reportando los resultados con ese set durante esta búsqueda entonces estás bien. Eso significa que en la pregunta 4 deberías utilizar el mismo set para reportar la matriz de confusión, a modo de término de tu proceso de entrenamiento. Ya en la pregunta 5 se te pide que utilices test, pues has cambiado de etapa, y la matriz de confusión de 4 ahora te sirve como herramienta de comparación para ver cómo generaliza tu modelo.
> Saludos

Perfect! aprovechando la pregunta, cuando piden el mejor y peor rendimiento de cada categoría en la matriz de confusión, hay que verlo más o menos al ojo o no? Porque sino la única forma que se me ocurre es haciéndolo a mano

**Comment by IngElecPuc** [comment]
En la guía te aparece un método para que puedas analizar cada categoría. Esto también lo vimos en la ayudantía.
