### ISSUE TITLE
[Tarea 3] Pregunta 6: Bagging - Boosting

### ISSUE THREAD

**Issue by FranciscoCabello** [UC-IIC2613/Syllabus#184]
Hola,

¿Es necesario explicar la matemática atrás de bagging y boosting o es simplemente explicar como funciona cada técnica?

Saludos.

**Comment by fivaldivia** [comment]
Hola, lo importante es que investigues y definas las técnicas y las compares, ya va en tu criterio si explicas o debes explicar la parte matemática para responder lo que te menciono. Ojala haya quedado claro!
