### ISSUE TITLE
Pregunte 6: Bagging y Boosting

### ISSUE THREAD

**Issue by sebaelsaca** [UC-IIC2613/Syllabus#185]
Hola, tengo una duda de Bagging y Boosting. El tema es que investigué de ambos y se que sklearn ofrece funciones que te permiten ensamblar con una función y quería saber si las podemos ocupar o se espera que construyamos algo desde cero? Por ejemplo, random forest de sklearn.

**Comment by IngElecPuc** [comment]
Hola
La misma guía dice que no es necesario entrenar nada. Lo importante es tratar de contestar lo que dice ahí. 
Saludos
