### ISSUE TITLE
[Tarea 3] Proceso de corrección

### ISSUE THREAD

**Issue by tomytable** [UC-IIC2613/Syllabus#186]
Hola, quería preguntar si para la corrección de la tarea 3 el ayudante va a correr todo el código o se va a fijar en el output que las celdas tengan. Pregunto esto porque procesos como cargar los datos a colab me está tomando mucho tiempo (cerca de 10 minutos) y lo estoy haciendo manualmente, es decir, sin código. Además, algunos comandos pueden variar dependiendo si se revisa en colab o directamente desde jupyter.

Además, hay ciertos procesos que están randomizados como la división entre el set de entrenamiento y validación por lo que los valores de accuracy pueden variar levemente al correrlo otra vez, entonces no estoy seguro de referirme a valores específicos.

Gracias!

**Comment by chris-carstens** [comment]
Hola, en general las tareas se revisarán solo outputs, por lo que los resultados ya deben estar corridos y explícitos. Esto no implica que en algunos casos el ayudante pueda ejecutar código para ver ciertas cosas.
Respecto a los comandos previos, no te preocupes por eso, se revisará finalmente desde el punto en que comienzas el preprocesamiento de datos. De todos modos los ayudantes sabrán cargar los datos en colab. Aún así, ¿qué problema tuviste para cargar los datos?

Respecto a los procesos randomizados, tampoco hay problema en eso, puedes (y debes, de hecho) referirte a valores específicos obtenidos. De todos modos, estos métodos tienen atributos random_state para sembrar semillas, para que en distintas ejecuciones del código te entreguen el mismo resultado, lo cual te puede ser útil durante el desarrollo de la tarea.

**Comment by tomytable** [comment]
Gracias por la rápida respuesta, el único problema que tuve para cargar los datos fue el tiempo que demora pero por lo que dices esto no debería ser un inconveniente.
