### ISSUE TITLE
[Tarea 3] Pregunta 4: Imágenes del set de datos

### ISSUE THREAD

**Issue by jaimecoloma** [UC-IIC2613/Syllabus#187]
Hola! Quería saber qué se espera cuado piden mirar las imagenes en esta parte, no entiendo muy bien cuantas debo mostrar o si debería buscar alguna que falle u otra alternativa.
Quedo atento.

**Comment by ebrzovic** [comment]
Lo que se espera en esta parte es que mires las imágenes de set de datos para apoyarte en la justificación de tus respuestas de las preguntas. Un ejemplo puede ser"en la imagen real X observé que cuando la persona está muy alegre, su boca está muy abierta lo cual afecta el algoritmo de clasificación de cierta forma".
Quedo atento a cualquier duda :)

**Comment by Baelfire18** [comment]
O sea se deben volver a mostrar las imagenes en esa parte? Y deben corresponder a cada set (train, test, validate) o no es necesario?

**Comment by jaimecoloma** [comment]
Es que eso es lo que no tengo claro, idealmente mostrar unas 2 o 3 imagenes por clase y sus landmarks? Y sumado a lo que mencionaron arriba, da lo mismo a que set pertenezcan o deben ser de uno específico? (asumo sería el Train)

**Comment by ebrzovic** [comment]
Hola, en esta parte no es obligación mostrar, pero  si crees que te puede facilitar mucho la explicación, te recomiendo subir una foto. 
Ahora recuerden que en la pregunta 1 ya tienen la obligación de desplegar por lo menos una imagen de cada clase en el jupyter.
No tiene que pertenecer a algún sub set en particular, las pueden sacar del dataset original si les sale más fácil. Lo que importa que es sea al azar de cada clase con el formato del enunciado .

**Comment by jaimecoloma** [comment]
Ya perfecto! Con saber que eran para facilitar la explicación me quedo tranquilo. 
Gracias! 😄
