### ISSUE TITLE
[Tarea 3] Formato de entrega

### ISSUE THREAD

**Issue by Baelfire18** [UC-IIC2613/Syllabus#188]
En cuanto al formato de entrega debe ser solo:
```
T3/
    INTEGRIDAD.TXT
    Tarea_3.ipynb
```
- Solo con esos dos archivos cierto?
- Y el `.ipynb` debe tener algún nombre en concreto ? Había leído algo de nombre, apellido y número de alumno, pero no sabía si solo debían estar en la tarea o ser el nombre del archivo en sí. 
De ser el nombre del archivo debe ser en algún formado en específico? camelCase, snake_case, etc?
- Las respuestas a las preguntas deben ir junto a las celdas o en un apartado al final?

Muchas gracias y buenas noches!

Edit: En caso de haberme basado en internet donde pongo los links?

**Comment by ebrzovic** [comment]
Hola :), 

Tu archivo `.ipynb` debe contener tu nombre, apellido y número de alumno en alguna parte del archivo, (ojalá que esté al principio jajaj). Sobre el  nombre de archivo y formato no se especifica nada, pero sería ideal que se relacionase con la tarea 3 y tenga un formato entendible y ordenado. El nombre que pusiste `Tarea_3.ipynb` está bien. 
Las respuestas de a las preguntas deben ir junto a las celdas. (asegúrate de deshabilitar la opción "Omitir el resultado de las celdas").

Puedes citar el link del formato que tú desees. Puedes hacerlo en formato de APA, ICONTEC o IEEE. En caso de que parafrases puedes poner el link al lado del código o en una bibliografía. Una forma que puedes hacerlo, es poner un hipervínculo de la siguiente forma [YouTube] (https://youtube.com). (en el Jupyter no debe estar separado)

Saludos y buena noches

**Comment by Baelfire18** [comment]
Muito obrigado
