### ISSUE TITLE
[Tarea 3] Pregunta 6

### ISSUE THREAD

**Issue by CataAlamos** [UC-IIC2613/Syllabus#189]
Hola, no me queda claro lo que nos están pidiendo. Tengo entendido que seleccionamos un modelo pero no se a que se refiere con "una arquitectura de ensamblaje de clasificadores"? Estos son los hiperparametros? 

Muchas gracias

**Comment by IngElecPuc** [comment]
Hola
Un ensamblaje en una combinación de modelos para aprovechar sus mejores características y reducir sus debilidades. Una arquitectura sería, para el caso de la pregunta, un diagrama con esa combinación, seguida de tus explicaciones de porqué funcionaría, (consideranto tanto la materia como las características de este problema). Te recomiendo que hagas la investigación. 
Saludos
