### ISSUE TITLE
[Tarea 1] Parte 4.1 Aclaraciones Gold

### ISSUE THREAD

**Issue by vchadwick** [UC-IIC2613/Syllabus#19]
¿Hay que incluir dentro de los mundos posibles el predicado gold?  Especificamente para la parte 1 de la pregunta 4.
(Se menciona indirectamente)

**Comment by fjcroquevielle** [comment]
Creo que no, no sale en el enunciado por lo menos

**Comment by FeBalla** [comment]
Confirmaré lo antes posible la respuesta, pero a priori lo lógico es que si existen predicados que definen si hay un pozo o wumpus en una celda, entonces también debería haber uno que diga si se trata de la celda con el oro. Por lo tanto, el predicado `gold` debería aparecer en el modelo 😄 (mundos posibles)

**[ACTUALIZACIÓN]** Traigo la siguiente respuesta desde el olimpo 🌥️.  "No es necesario que creen el predicado `gold`, aunque podrían hacerlo". Explican que no es necesario porque el código en Python va a identificar cuando llegan a la celda con oro. Además, podría serles de ayuda definir un predicado como `safe(x,y).`  que aparezca cuando se tenga certeza de que moverse a (x, y) sea seguro.

**Comment by Aloncarrasco** [comment]
Cual sería la diferencia entre safe(x,y). y alive(x,y).?

**Comment by nmendicoa** [comment]
alive es una celda ya visitada, safe es una celda que sabes que es segura pero que no has visitado
