### ISSUE TITLE
[Tarea 3][Pregunta 3] Entrenar Clasificador y Matriz de características

### ISSUE THREAD

**Issue by beatrizacuna** [UC-IIC2613/Syllabus#190]
Hola! Mi matriz de características es de la forma:
![Captura de pantalla 2021-06-29 a la(s) 14 49 09](https://user-images.githubusercontent.com/48481963/123851484-39955680-d8e9-11eb-9dd2-3fedc52d29a6.png)

Y cuando ejecuto:
`nb_clf = GaussianNB()`
`nb_clf.fit(matrix_features_train, y_train)`
me tira un ValueError: float() argument must be a string or a number, not 'list'

Mis preguntas son: está bien que mi matriz de características se vea así? si es si, cómo puedo arreglar este error para poder entrenar el clasificador?
Muchas gracias :)

**Comment by sofiacorreabusquets** [comment]
Hola! No soy ayudante, pero el modelo espera que cada feature sea un solo número y no tiene implementado el manejo de excepciones para que sea una lista de tuplas.

**Comment by IngElecPuc** [comment]
Hola
En efecto el modelo espera que tu matriz de características solo posea números. Mi consejo es que tomes los datos de pandas y los pases a numpy que es lo más adecuado. De todas maneras asegúrate de que el formato en numpy también sea el adecuado. 
Saludos

**Comment by beatrizacuna** [comment]
Gracias @IngElecPuc  :) a qué te refieres con "los pases a numpy"? no entendí, es a un numpy array?

**Comment by IngElecPuc** [comment]
Si, a un numpy array. Sorry lo vago.

**Comment by beatrizacuna** [comment]
@IngElecPuc convertirlo a un numpy array me arroja el error only size-1 arrays can be converted to Python scalars al usar fit. He investigado y no sé cómo podría convertirlo a un size-1 array
