### ISSUE TITLE
Google Colab

### ISSUE THREAD

**Issue by beatrizacuna** [UC-IIC2613/Syllabus#191]
Hola! Me sale esto en pantalla cuando intento ejecutar mi notebook y no se qué hacer :( ayuda

![Captura de pantalla 2021-06-29 a la(s) 15 50 47](https://user-images.githubusercontent.com/48481963/123858709-d2c86b00-d8f1-11eb-831f-35aa5fd3ce93.png)

**Comment by sofiacorreabusquets** [comment]
Harta gente lo solucionó compartiendo el notebook con otra cuenta de google y abriéndolo en la 2a ;)

**Comment by IngElecPuc** [comment]
Hola
Colab tiene ciertas restricciones de uso de las GPU. Esto se ha comentado en la ayudantía. El primer consejo útil es el que te da tu compañera. 
El segundo, es que guardes tus variables relevantes en tu drive (como las matrices de características extraídas con dlib).
Aquí hay una guía de cosas interesantes que puedes hacer en Colab, la que te comento, montar el drive, es el consejo n°2:
https://towardsdatascience.com/10-tips-for-a-better-google-colab-experience-33f8fe721b82
Saludos
