### ISSUE TITLE
[Ayudantía 9] Subir script

### ISSUE THREAD

**Issue by emyskog** [UC-IIC2613/Syllabus#196]
Van a subir el script de la ayudantia 9? Sería de gran ayuda para realizar la tarea.

**Comment by FeBalla** [comment]
> Van a subir el script de la ayudantia 9? Sería de gran ayuda para realizar la tarea.

Hola! Estamos discutiendo si subir o no ese notebook por motivos pedagógicos. Esta decisión debería estar a más tardar hoy, así que responderé de nuevo esta misma _issue_ para informar de la respuesta.

**EDIT:** Decidimos subir el notebook, así que pueden encontrarlo en la carpeta de las ayudantías. Mucho éxito con su tarea :)
