### ISSUE TITLE
Problema con robot.html

### ISSUE THREAD

**Issue by tomasalvarez13** [UC-IIC2613/Syllabus#2]
Hola, estoy tratando de correr la solucion de la ayudantia,y no me arroja ningun error. Sin embargo abro robot.html en el navegador y me aparece el canvas vacio. Que podrá ser?

**Comment by FeBalla** [comment]
> Hola, estoy tratando de correr la solucion de la ayudantia,y no me arroja ningun error. Sin embargo abro robot.html en el navegador y me aparece el canvas vacio. Que podrá ser?

Hola, ¿estás corriendo el archivo que está con la resolución (bodegas_pauta.lp)? ¿Podrías adjuntar alguna captura de pantalla con el comando que usaste para ejecutar el programa?

**Comment by tomasalvarez13** [comment]
El problema era la version de python. Tenía que ser >= 3.

**Comment by FeBalla** [comment]
> El problema era la version de python. Tenía que ser >= 3.

Ah sí, para el  curso se usará Python 3, en particular lo de ayer está hecho en Python 3.8.X

**Comment by FeBalla** [comment]
**[ACTUALIZACIÓN]** Me he topado con que a personas que usan Mac no les funciona el comando del visualizador, lo que puede ser un problema para los ejercicios de la ayudantía o tareas. Mac trae instalado Python por defecto en otra versión y estos códigos están hechos en Python3, por lo que al escribir el comando como se vio en la ayudantía puede no funcionar. Por lo tanto, lo que deben hacer es cambiar en el comando el `python process.py` por `python3 process.py`

**Comment by Gsalinas1506** [comment]
> > El problema era la version de python. Tenía que ser >= 3.
> 
> Ah sí, para el curso se usará Python 3, en particular lo de ayer está hecho en Python 3.8.X

Hola! Una pregunta, hay algún problema con usar python 3.7.X durante el curso?
