### ISSUE TITLE
[Tarea1] Parte 2.2 caminos no iluminados

### ISSUE THREAD

**Issue by Aloncarrasco** [UC-IIC2613/Syllabus#21]
Si tengo un camino_k(A,B,k), existe un camino entre A y B con  k arcos no iluminados, este camino puede tener arcos iluminados también? (No se menciona que estos k arcos no iluminados sean los únicos que contiene el camino). 

está bien si uso negación en esta pregunta?

**Comment by aamedinaj** [comment]
Hola, el enunciado dice
>`conectado_k(X,Y,K)` aparece en el modelo **si y solo si** existe un camino entre X e Y con **exactamente K** arcos no iluminados

O sea, ninguno de esos K debe estar iluminado para cumplir lo pedido.
Puedes usar negación si te sirve.

🦊

**Comment by Aloncarrasco** [comment]
Pero por ejemplo entre X e Y podría tener un camino de largo K+3 que tiene K arcos no iluminados, entonces entre X e Y existe un camino con exactamente k arcos no iluminados (que también tiene 3 arcos iluminados) entonces camino(X,Y,K) está en el programa, esta bien eso?

**Comment by aamedinaj** [comment]
Estaría bien 😃

**Comment by Aloncarrasco** [comment]
Ooo gracias :),
Otra pregunta en la P2.5 el enunciado dice:
"no exista ninguna ruta entre cada par de esquinas que estén conectadas por un camino con más de una calle sin iluminar."
entonces puedo tener caminos con 1 una calle sin iluminar?

**Comment by aamedinaj** [comment]
Claro, sería equivalente a "de manera que todo camino que conecte 2 nodos tenga, a lo más, 1 calle sin iluminar", así que sí puedes tener caminos con 1 calle sin iluminar

**Comment by Aloncarrasco** [comment]
Entiendo, pero al alcalde le interesa que la ruta minima tenga a lo más una camino sin eliminar o que cualquier ruta tenga a lo más un camino sin iluminar?

**Comment by aamedinaj** [comment]
Ignora el mensaje anterior, estoy confirmando 🙏

**Comment by Aloncarrasco** [comment]
ok gracias :D

**Comment by aamedinaj** [comment]
> entonces puedo tener caminos con 1 una calle sin iluminar?

En respuesta a esto, puedes tomar la instrucción cómo " entre cada par de nodos, el camino que menos calles oscuras tiene debe tener a lo más una calle oscura." 

(Disculpa la demora 😞 )

**Comment by jmopaso** [comment]
Sólo para complementar, para esta parte se modificó el enunciado para explicarlo de forma más clara. La explicación del enunciado señala que lo que se busca es `entre cada par de equinas, exista un camino con a lo más una calle sin iluminar.`
