### ISSUE TITLE
Duda Parte 2.2

### ISSUE THREAD

**Issue by ancontardo** [UC-IIC2613/Syllabus#22]
Tengo una pregunta sobre la definición de una calle iluminada. En la tarea dice: "Si instala una luminaria en una esquina, entonces todas las calles que llegan a esa esquina se encuentran iluminadas tambien"

Supongamos que el nodo(a) esta conectado con el nodo(b) y solo el nodo(b) tiene una luminaria. Esto produce que el arco(a,b) este iluminado, ¿esto implica que el arco(b,a) tambien este iluminado?

**Comment by aamedinaj** [comment]
Es un grafo no dirigido así que, efectivamente, estaría iluminado

🦊

**Comment by tomasalvarez13** [comment]
Para esta parte tenemos que considerar que si por ejemplo el arco (a,b) no esta iluminado, y hago la secuencia a-b-a, esta estaría pasando por 2 arcos sin iluminar, es decir, conectado_k(a,b,2) seria verdadero?
