### ISSUE TITLE
Restricciones

### ISSUE THREAD

**Issue by fjcroquevielle** [UC-IIC2613/Syllabus#23]
Hola, tenía una duda respecto a las opciones que puede tomar un determinado modelo. Puede haber un pozo pegado a un wumpu?. Gracias!!

**Comment by jfuentesg26** [comment]
Hola! Si a "pegado" te refieres a que están en celdas vecinas, si es posible, ya que no rompe ninguna regla, lo que no debe ocurrir es que estén en una misma celda.

**Comment by fjcroquevielle** [comment]
Muchas gracias!!
