### ISSUE TITLE
Problemas para instalar clingo

### ISSUE THREAD

**Issue by FelipeLara00** [UC-IIC2613/Syllabus#25]
Hola!
Estoy usando el link que mando el profesor para descargar clingo en windows pero no se que hacer con los archivos que están dentro del .zip y no puedo usar clingo.

Gracias!

**Comment by jfuentesg26** [comment]
Hola! Debes extraer la carpeta del .zip y guardarlo en tu disco local.
Aquí te dejo un paso a paso de lo que debes hacer: https://spaceshipparking.blogspot.com/2018/10/installing-and-using-clingo-on-windows_21.html

Espero te resulte! Cualquier cosa me avisas!

**Comment by FelipeLara00** [comment]
Me funciono perfecto, muchas gracias!
