### ISSUE TITLE
Duda Parte 3.1

### ISSUE THREAD

**Issue by nbarriav** [UC-IIC2613/Syllabus#26]
Hola, quería saber si para la demostración se puede usar el algoritmo para la definición de modelo o debe ser estrictamente la matemática usando álgebra de conjuntos

**Comment by jmopaso** [comment]
Hola, 

En la pregunta sólo se pide que para la demostración uses la definición de modelo de un programa sin negación, donde en clases se vieron dos formas una matemática y otra algorítmica, por la que puedes usar la que más estimes conveniente.

Saludos!
