### ISSUE TITLE
[Tarea 1] Dudas Parte 4

### ISSUE THREAD

**Issue by milosoria** [UC-IIC2613/Syllabus#27]
Hola! No me queda clara la utilidad de la funcion find_path de agent.
Y en el archivo wumpus.lp es necesario definir la regla para shoot?
Gracias!

**Comment by sufigueroa** [comment]
Holaa! Lo que hace en find_path es encontrar caminos posibles entre dos celdas, lo que resulta útil al momento de tomar una decision sobre el siguiente movimiento que debe realizar el agente. Y no es necesario que definas shoot en wumpus.lp porque get_action se debería encargar de esta acción.
