### ISSUE TITLE
[Tarea 1] Posible Ayudantía para el lunes  

### ISSUE THREAD

**Issue by gustavobarrezueta** [UC-IIC2613/Syllabus#28]
Hola! Sé que es un poco tarde para pedir esto, pero me gustaría que se considerará que la ayudantía del lunes, en vez de que pasemos materia sea para revisar la tarea, ya que siento que hay varias dudas a nivel general y no hemos tenido esta instancia de resolución de dudas. Ojalá puedan tomarlo en cuenta.
Desde ya, muchas gracias.

**Comment by jmopaso** [comment]
Hola Gustavo,

Se acaba de mandar un anuncio al respecto. Al final habrá clases hoy día en horario de ayudantía y el día jueves se realizará la ayudantía que lo más probable sea principalmente para responder dudas de la tarea.

Saludos

**Comment by gustavobarrezueta** [comment]
Gracias José!
