### ISSUE TITLE
Input y predicado alive(x,y) Parte 4.1

### ISSUE THREAD

**Issue by antoniaalcayaga** [UC-IIC2613/Syllabus#29]
Hola!

Tengo 2 dudas:

Respecto a lo que representa el predicado alive en esta parte. Por lo que entiendo lo que estamos modelando es solo el conocimiento que tiene el agente dentro del mundo, entonces no entiendo el sentido del predicado, ya que por la explicación del programa, una celda será visible si el agente pasa por ella, pero en este caso no estamos moviendo al agente. Mi dudas son entonces ¿Qué representa este predicado exactamente? ¿Cuándo se considerara en este caso a una celda como visible? y en caso de que este entendiendo mal la pregunta si me podrían corregir.

La segunda duda que tengo es el input del programa. ¿Este será el tamaño del tablero y lo sensorial (brizas y hedores), y por tanto todo el conocimiento del agente se debe basar en esto?.

Muchas gracias!!

**Comment by fnberrios** [comment]
Me sumo a las dudas de @antoniaalcayaga

**Comment by sufigueroa** [comment]
Holaa! En la primera parte debes modelar los mundos posibles qué hay dado el input entregado. Aunque no se pide el movimiento con pasos, es útil modelar los caminos posibles que puede tomar el agente, esto le permitirá también que él adquiera la información del mundo. El predicado alive(x, y) te sirve para saber si una celda ya fue descubierta (forma parte del camino) con todo lo que esto implica. 

Con respecto a la segunda duda, el input sera el tamaño del tablero con el tablero y la información sensorial. Con esta información el agente debe ser capaz de deducir los modelos posibles que lo satisfagan.
