### ISSUE TITLE
Control 6 y Negación en ASP

### ISSUE THREAD

**Issue by nfragav** [UC-IIC2613/Syllabus#3]
Hola. No entiendo bien por qué en la pregunta 4 del control 6 no se incluye p11 en el modelo. Si alguien pudiera explicarlo con peritas y manzanas, estaría muy agradecido.

También quiero preguntar en qué biobliografía puedo encontrar la materia de negación en ASP para poder estudiarla.

**Comment by FeBalla** [comment]
¡Hola! disculpa por la demora. Para entender esta pregunta lo mejor es tener la definición a mano e ir paso a paso. La definición dice lo siguiente (Va con peras y manzanas 🍐 🍎  -ALERTA DE MUCHO TEXTO-):

![red_def](https://user-images.githubusercontent.com/48292394/113961668-6b1fe980-97f4-11eb-856b-cb3e9c565cbd.png)

Entonces, tenemos las reglas del problema original y queremos reducir el programa con el conjunto `X={p1, p3, p5, p7, p9, p11}`:
````
p1 :- not p2.
p2 :- not p3.
p3 :- not p4.
p4 :- not p5.
p5 :- not p6.
p6 :- not p7.
p7 :- not p8.
p8 :- not p9.
p9 :- not p10.
p10 :- not p11.
````
Todas estas sentencias están de la forma `Head <- Pos, not (Neg)`, donde para estos casos, `Pos` es nulo o vacío, pues no hay condiciones en afirmativo, mientras que todas tienen un `Neg`, ya que en todas hay una condición del predicado en formato de negación. Por ejemplo, la primera sentencia tiene `Head=p1`;  `Pos=(nulo)` y `Neg=p2`.

Teniendo esto claro, el segundo paso de la definición nos dice que debemos borrar todas las reglas que están en la forma antes descrita, tales que la intersección entre `Neg` y `X` no sea vacía. Para entender esto con un ejemplo, puedes mirar la segunda sentencia, donde `Neg=p3` y como `p3` está también en el conjunto `X`, entonces se trata de una regla que se debe borrar. Siguiendo esta lógica, se deben borrar las reglas 2, 4, 6, 8 y 10, quedando el problema reducido hasta ahora de la siguiente manera:
````
p1 :- not p2.
p3 :- not p4.
p5 :- not p6.
p7 :- not p8.
p9 :- not p10.
````
Ahora, el último paso de la definición señala que todas las reglas (tal como las definimos al inicio) que tengan una intersección vacía de `Neg` con el conjunto `X` serán reemplazadas por una nueva regla donde ya no aparece la parte `not (Neg)`, sino que solo `Pos`. Por ejemplo, del modelo reducido que se tiene hasta ahora, la primera sentencia (`p1 :- not p2.`) tiene un `Neg=p2`, donde `p2` no aparece en el conjunto `X`. Por lo tanto, esta regla debe ser reemplazada borrando la parte de la negación y solo dejando la afirmación, pero como para esta regla `Pos=(nulo)`, entonces es equivalente a decir que `p1 <- {}` o en su defecto en Clingo:
`p1.`
Entonces, siguiendo con esta lógica, ya que todas las reglas son del mismo estilo, el modelo reducido quedaría finalmente como:
````
p1.
p3.
p5.
p7.
p9.
````
Espero se haya entendido y cualquier duda no dudes en consultar  😃

**Comment by nfragav** [comment]
Muchas gracias Fernando! Me quedó muy claro! 👏🙌
