### ISSUE TITLE
Duda Parte 3.1

### ISSUE THREAD

**Issue by lewebe** [UC-IIC2613/Syllabus#30]
Hola, basta con encontrar **un** modelo M' tal que M es subconjunto de M' para que esta demostración sea válida? O se debe demostrar que todos los modelos M' que son modelos de Pi' tienen como subconjunto a M?

**Comment by jmopaso** [comment]
Hola!

Debes demostrar la propiedad de monotonía para **todos** los casos de programas en lógica sin negación. Es decir, no basta que des sólo un ejemplo donde esto se cumpla, sino que debes usar la definición de modelo para programas sin negación para demostrarlo en todos los casos.
