### ISSUE TITLE
[Tarea 1] Implementación  negación

### ISSUE THREAD

**Issue by nfragav** [UC-IIC2613/Syllabus#31]
Hola!

Estoy intentando implementar negación en una parte de la tarea y recibo un error de `unsafe variable`. Solo estoy usando variables en esta parte del programa y si quito la negación se groundea con éxito. Quería preguntar si era posible recibir ayuda con este trozo de código o si un ayudante conoce razones de por qué pasa esto.

Gracias!

**Comment by jmopaso** [comment]
Hola!

Este es un clásico problema en clingo cuando se ocupa negación, ya que clingo te pide definir previamente donde se "mueven" las variables al ocupar negación, en caso contrario, como bien dices el programa te retornará ```unsafe```.

Por lo tanto, sólo a modo de ejemplo, si pretendo usar negación **no sería correcto** hacerlo de esta forma:

```
no_valido(X,Y) :- not valido(X,Y)
```

En este caso, no le explicité a clingo por donde se mueven mis variables, por lo que el programa me retornaría unsafe. La forma correcta de hacerlo es la siguiente:

 ```
no_valido(X,Y) :- arco(X,Y), not valido(X,Y)
```
