### ISSUE TITLE
[Tarea1] [Modificación Enunciado] Duda parte 3.1

### ISSUE THREAD

**Issue by Aloncarrasco** [UC-IIC2613/Syllabus#32]
Para esta demostración tengo que asumir que aparecen reglas tipo:
{a;b;c}.?
o eso no podría estar?

Además,
es posible que el programa pi' se le agreguen reglas tipo:
:-p. por que entonces el modelo M' podría no satisfacer pi'

**Comment by jmopaso** [comment]
Hola!

Sobre lo segundo, no es posible que el programa contenga reglas del tipo ```:-p```, ya que estas son reglas de cabeza vacía, las cuales no debes considerar

**Comment by jmopaso** [comment]
Hola de nuevo, un update importante sobre lo primero que señalas. Es importante considerar que las reglas de los programas **solo serán del tipo `Head <- Body` con `|Head| = 1`**, es decir, el número de átomos en `Head` debe ser estrictamente 1. Esto no estaba previamente en el enunciado por lo que te agradezco la pregunta, **el enunciado ya fue modificado considerando este detalle**. De todas formas, para las personas que ya lograron hacer la demostración, lo más probable es que quede automáticamente bien para el caso de `|Head| = 1`, por lo que no tendrían que hacerla de nuevo.

**Comment by Baelfire18** [comment]
@jmopaso Creo modificaste el de canvas pero no aún el de syllabus

**Comment by jmopaso** [comment]
Gracias por avisar, ahora si está
