### ISSUE TITLE
[Tarea1] Duda parte 2.4

### ISSUE THREAD

**Issue by Juanvg213** [UC-IIC2613/Syllabus#33]
Hola,

Para realizar la aproximación del programa instanciado,  ¿Podemos asumir el peor caso? Me refiero al grafo donde todos sus nodos estén conectados ya que este sería el que origine mas instancias del programa.

**Comment by jfuentesg26** [comment]
Hola! La idea es que la aproximación sea correcto para cualquier grafo,  con n nodos y m arcos,  es decir, no solo para aquellos grafos que estén todos los nodos conectados. 
Ahora si quieres trabajar con el peor caso (O(n) por ejemplo), debes justificar porqué tu aproximación es correcta para cualquier grafo.
