### ISSUE TITLE
Duda 3.2 Inducción

### ISSUE THREAD

**Issue by lewebe** [UC-IIC2613/Syllabus#34]
Hola! Me queda la duda si para la base inductiva sobre el número de reglas del programa debiera ser  con n = 0 reglas o con n = 1 regla.

**Comment by fnberrios** [comment]
Quiero sumarme a dudas de esta pregunta, cuando dice:
![image](https://user-images.githubusercontent.com/34272957/115174820-f1131e80-a097-11eb-881e-f17c9e52277a.png)
¿se refiere a la cardinalidad de Head? Es decir, la cantidad de átomos que hay en Head.
Gracias de antemano.

**Comment by FeBalla** [comment]
Hola a amb@s!

**Primera pregunta**
> Hola! Me queda la duda si para la base inductiva sobre el número de reglas del programa debiera ser con n = 0 reglas o con n = 1 regla.

**R:** Para el caso base de la inducción debes considerar `n=0` reglas.

**Segunda pregunta**
> Quiero sumarme a dudas de esta pregunta, cuando dice:
> ![image](https://user-images.githubusercontent.com/34272957/115174820-f1131e80-a097-11eb-881e-f17c9e52277a.png)
> ¿se refiere a la cardinalidad de Head? Es decir, la cantidad de átomos que hay en Head.
> Gracias de antemano.

**R:** Estás en lo correcto. Cuando se dice `|Head| <= 1` se refiere a que el  _Head_ tiene a lo más 1 átomo.
