### ISSUE TITLE
[Tarea 1] Dudas varias P4

### ISSUE THREAD

**Issue by jorge-ovalle** [UC-IIC2613/Syllabus#35]
Hola! Hay hartas cosas que no me quedan claras de lo que me piden:

(1) ¿Debo definir en un archivo la posición inicial del agente o eso lo hace el programa de python?
(2) En `wumpus.lp` qué tenemos que hacer exactamente. ¿La idea es que acaso el agente recorra la grilla y vaya haciendo visibles las celdas y viendo que celda es segura? ¿Hasta que punto debo recorrer la grilla?
(3) No entiendo muy bien lo de si el número de wumpus y pozos es observable o no para el agente.  
(4) En `get_action` de la clase `Agent` qué  debemos hacer y ¿por qué debo asegurarme que todo átomo esté en todos los modelos? Si hay múltiples modelos posibles tal vez solo uno me sirva como solución...

Espero se entienda. Estoy medio confundido con esta parte

**Comment by Aloncarrasco** [comment]
me sumo a las preguntas

**Comment by Aloncarrasco** [comment]
Se supone que wumpus.lp lo voy a usar despues en el python?

**Comment by jmopaso** [comment]
Hola!

Voy a ir contestando las preguntas por orden:

1. Si, la posición inicial del agente lo maneja el programa de python según el mapa entregado. En `wumpus.lp` sólo debes preocuparte que dada una "situación" tu programa retorne lo deseado.

2. Lo que tienes que hacer en el archivo `wumpus.lp` es que dado la definición de una grilla y la información de ciertos inputs sensoriales (especificado en otro archivo que podría ser llamado `extra.lp` ) los modelos que debe retornar tu programa deben corresponder a los **mundos posibles** (donde el agente sabe p cuando p aparece en todos los modelos, etc). De esta forma, a través de este programa podrías distinguir, por ejemplo, en que posición se encuentra un wumpus, un pozo o que posición es segura para ser visitada por el agente, todo esto siempre dado una información previa (grillas e inputs sensoriales).

3. Esto cobra más sentido para la segunda parte de la tarea, que el número de wumpus y pozos sea observable quiere decir que el agente sabe de antemano cuantos pozos y wumpus hay en el tablero (de hecho puedes obtener ese número con las funciones `get_num_pits()` y `get_num_wumpus()`). Esto puede ser muy útil para determinar si un problema tiene solución o no, te recomiendo que revises la issue #36 donde se muestra un ejemplo.

4. `get_action` es la función que dada una percepción que reciba el agente (ej: sense_stench en una cierta posición) debe retornar una acción posible, ya sea `(goto, x, y)` *moverse a (x,y)*,  `(shoot, x, y)` *disparar a (x,y)* o `(unsolvable)` *cuando agente descubre que el problema no tiene solución*. Además debes asegurarte que los movimientos que realices correspondan a un átomo que está en todos los modelos, precisamente por la **semántica de mundos posibles**, ya que sólo los átomos que están en todos los modelos son lo que el agente sabe con seguridad.

Espero que te sirva. Saludos!
