### ISSUE TITLE
[Tarea 1] Parte 4, problemas sin solución

### ISSUE THREAD

**Issue by szabala** [UC-IIC2613/Syllabus#36]
Hola!
Queria confirmar (para ver si entendi bien) si el siguiente escenario es uno donde se necesita saber el numero de pozos y wumpus para poder resolverlo:
![image](https://user-images.githubusercontent.com/48331715/115276739-6c64e680-a111-11eb-823f-41bf0578450d.png)
¿Esto es por la regla de seguridad?
Gracias de antemano!

**Comment by jmopaso** [comment]
Exactamente, ese problema en particular sólo se puede resolver si el ambiente está en modo observable (donde se el número de pozos y wumpus), para satisfacer la regla de seguridad.

**Comment by szabala** [comment]
Gracias!

**Comment by Aloncarrasco** [comment]
> Exactamente, ese problema en particular sólo se puede resolver si el ambiente está en modo observable (donde se el número de pozos y wumpus), para satisfacer la regla de seguridad.

En dicha situación, yo puedo dispararle a cualquiera de esos lugares donde puede haber un wumpus?
