### ISSUE TITLE
Código ayudantía no corre: "could not opne input file!"

### ISSUE THREAD

**Issue by jorge-schenke** [UC-IIC2613/Syllabus#37]
No sé por qué clingo me contesta esto cuando trato de correr el código del problema 1... Alguien conoce el error? Asumo que es un problema con el archivo probl1.lp pero no lo he cambiado en nada :/.
![Captura](https://user-images.githubusercontent.com/69639964/115286181-c5864780-a11c-11eb-846a-6b13e98936ec.JPG)

**Comment by FeBalla** [comment]
Si no me falla la memoria, no te está funcionando porque el problema 1 no se llama de esa manera, sino que se llama `prob1.lp` (tienes una letra "`l`" demás)
