### ISSUE TITLE
[Tarea 1] 2.3 Predicado "conectado_k/3" debe contener caminos cíclicos?

### ISSUE THREAD

**Issue by DiegoEmilio01** [UC-IIC2613/Syllabus#39]
¿Puede existir conectado(a, a, 2) en el modelo? Eso me da problemas en las preguntas de más adelante, pero dice "Tal como en la pregunta anterior, asegura que conectado_k no ‘pierda’ caminos en el grafo" y eso me hace pensar que debería tener esos ciclos entre inicio y final de un camino.

**Comment by tomasalvarez13** [comment]
Tengo la misma duda, porque si conectado(a,a,2) existe, entonces para la parte 2.5 nunca habrá una calle sin iluminar.

**Comment by tomasalvarez13** [comment]
Tengo la misma duda. Me pasa que si en la parte 2.5 existe una calle sin iluminar, entonces siempre voy a poder generar un camino que pase 2 veces por esa calle, por lo que mi programa siempre iluminará todos los arcos.

**Comment by FeBalla** [comment]
Puedes verlo como que no deberían aparecer en el modelo caminos que unan un nodo consigo mismo sin haber nodos intermedios. No obstante, como dijo el profesor, no debería ser un problema, pero puedes filtrarlos. Para quienes tengan la misma duda y sigan sin entender, los **últimos 15 minutos de la clase del 20/04/2021** se respondió esta (y otras) dudas.

**[ACTUALIZACIÓN]** Por lo que noté, la duda se solucionó porque algunos tenían el enunciado desactualizado. Los cambios en el enunciado están aplicados en el archivo en el Syllabus y en Canvas, y la explicación de los cambios respectivos están en _issues_ con la etiqueta `IMPORTANTE`. Lamentamos los inconvenientes que puedan haber surgido por estas modificaciones.

**Comment by DiegoEmilio01** [comment]
Gracias, hoy veré que onda. Sí considero que hayan nodos intermedios. El tema es que el mínimo no me está funcionando con una sentencia parecida a la del enunciado o la que se vio en la última ayudantía.
(Edit: tenía el enunciado desasctualizado)

**Comment by tomasalvarez13** [comment]
Podría interpretarse como que se pide que entre cada par de nodos, el camino que menos calles sin iluminar tenga, no tenga mas de una?
 Por ejemplo si tengo el siguiente grafo, que los nodos iluminados en el optimo sea solo el nodo a?
![Captura realizada el 2021-04-20 13 00 16](https://user-images.githubusercontent.com/48598610/115435965-68e86280-a1d8-11eb-972b-71c669c4bc2d.png)

**Comment by FeBalla** [comment]
> Podría interpretarse como que se pide que entre cada par de nodos, el camino que menos calles sin iluminar tenga, no tenga mas de una?
> Por ejemplo si tengo el siguiente grafo, que los nodos iluminados en el optimo sea solo el nodo a?
> ![Captura realizada el 2021-04-20 13 00 16](https://user-images.githubusercontent.com/48598610/115435965-68e86280-a1d8-11eb-972b-71c669c4bc2d.png)

Vengo a responder mientras que no he olvidado la pregunta, estamos evaluando para dar una respuesta precisa 😄 

**[ACTUALIZACIÓN]** A mí parecer particular son definiciones similares, aunque no equivalentes. Sin embargo, el profesor señala que **sí** pueden verlo de esa manera.

**Comment by DiegoEmilio01** [comment]
@tomasalvarez13 a mi me está dando que también podría sere C. Todos los nodos restantes pueden ir a otro en un paso (sí o sí cumple) . Hasta C pueden llegar en 2 pasos pero con uno iluminado. Y desde B basta con pasar por C para ir a D. Como que una esquina iluminada es muy poderosa porque no determinísticamente puedo elegir pasar por el único camino que cumple la condición.

**Comment by FeBalla** [comment]
> @tomasalvarez13 a mi me está dando que también podría sere C. Todos los nodos restantes pueden ir a otro en un paso (sí o sí cumple) . Hasta C pueden llegar en 2 pasos pero con uno iluminado. Y desde B basta con pasar por C para ir a D. Como que una esquina iluminada es muy poderosa porque no determinísticamente puedo elegir pasar por el único camino que cumple la condición.

Nada impide que existan múltiples modelos óptimos. De hecho, lo que mencionas es correcto, tanto `A` como `C` en el grafo que ponen de ejemplo puede servir; es más, para ese caso en particular cualquier nodo lo permitiría.
