### ISSUE TITLE
[Tarea 1] Dudas parte 1 y 2

### ISSUE THREAD

**Issue by gustavobarrezueta** [UC-IIC2613/Syllabus#4]
Hola! Tengo un par de dudas de la tarea. La primera es que en la parte 1, en el item 2, cuando nos piden "Especula sobre qué sistema computacional sería necesario implementar..." no estoy muy seguro a qué se refiere sistema computacional. Me encantaría si pueden darme un ejemplo de un sistema computacional (es un lenguaje de programación, es un paradigma, etc). La segunda duda es sobre la parte 2; no me queda claro cuál es el tipo de archivo que piden para el item 1 de esa parte. De hecho, intuyo que uno de los números en el apartado "Qué entregar en esta parte"  debe estar mal puesto porque no se menciona un tipo de archivo para el item 1.
Gracias!

**Comment by aamedinaj** [comment]
Sobre la duda 2: la Parte2/Pregunta1 se respondería en respuestas.pdf, piensa en que si te piden una "explicación" de algo, no se va a leer en código, sino que en los pdfs.

🦊

**Comment by jmopaso** [comment]
Como bien señala Pavel se trata de un *typo* en el enunciado, este ya fue corregido. Gracias por avisar!

A modo de resumen la estructura de lo que deben subir a su repositorio en GitHub es la siguiente:
```
T1/
    INTEGRIDAD.txt
    Parte1/
        respuesta.pdf
    Parte2/
        respuestas.pdf (pregunta 1 y 4)
        2.lp
        3.lp
        5.lp
    Parte3/
        respuesta.pdf
    Parte4/
        wumpus.lp
        agent.py
```

Sobre tu primera duda, debes considerar que en la conversación entre Lex y Mitchel se habla mucho sobre cómo el humano realiza analogías. Por ejemplo en el video se habla que los humanos para hacer una analogía realizamos una especie de simulación previa, entonces ¿Cómo realizar un proceso similar en el ámbito de ASP con herramientas puramente computacionales?¿En que colaboran estas herramientas/sistemas para lograr el objetivo? Lo importante es que los ejemplos que des sean netamente computacionales (no humanos).

Además es importante considerar que el objetivo de esta pregunta, más que tener una respuesta correcta o incorrecta, es que reflexionen sobre estas temáticas y desarrollen una argumentación consistente que incluya la materia del curso y que conteste las preguntas del enunciado.

Saludos!

**Comment by gustavobarrezueta** [comment]
Gracias por la explicación, José, entendí mucho mejor. Gracias a ambos por sus respuestas!

**Comment by FeBalla** [comment]
[AVISO] Recuerden **no cerrar** las _issues_. ¡Nosotros las cerraremos cuando sea oportuno!
