### ISSUE TITLE
[Tarea 1]  Pregunta 4.2: Simulación html

### ISSUE THREAD

**Issue by ignacio-urrutia** [UC-IIC2613/Syllabus#40]
Hola, tengo un problema con el archivo generado para la visualización del wumpus en el html. Me funciona bien la simulación en los cuadros de texto que imprime el programa, pero en el visualizador me pasaba que el agente al disparar no mata a los Wumpus y pasa sobre ellos. Después de revisar un poco el código, me di cuenta que solo les dispara si el orden en que están los Wumpus en el archivo generado `simulation.txt` es el mismo en el que se dispara, cosa que no ocurre automáticamente. Les escribo para que lo tengan cuenta para las correcciones y quizá para un posible upgrade de los archivos. (No quito la opción de que me haya confundido o haya alterado algo del código asi que confírmenme por favor si les ocurre esto también) .

Gracias!

**Comment by jmopaso** [comment]
Hola Ignacio, lo voy a revisar. Me puedes decir con que mapa estas probando el código?

**Comment by ignacio-urrutia** [comment]
Sisi, el mapa era el siguiente:
4,4
GW.I
.W..
.W..
.W..

Igual, como te decía, depende del orden en el que el agente "decida"
dispararle a los Wumpus porque si es el mismo orden que se escriben en el
archivo simulation.txt, funciona bien.

**Comment by jmopaso** [comment]
Ok Ignacio, sigo revisando los archivos, cualquier cambio en los archivos de simulación les aviso. En todo caso, guíense más por el output que les arroja el programa por consola, el archivo simulación es sólo para que puedan jugar y visualizar de mejor forma su trabajo. También recuerda la regla de benevolencia, donde sólo debes disparar a un wumpus si es la única forma de avanzar.

**Comment by carolinamaggi** [comment]
me pasó lo mismo, al agregarle más wumpus se genera mal.

**Comment by jmopaso** [comment]
Hola! 

Ya actualice el paquete de archivos para la visualización, ahora debería funcionar bien. El paquete nuevo está disponible acá en GitHub y también en Canvas.

En todo caso, les recuerdo guiarse más por el output que les entrega el programa en consola, el archivo de simulación es sólo para que puedan jugar y visualizar mejor su trabajo.

Saludos
