### ISSUE TITLE
[Tarea 1] Output de #minimize CLINGO

### ISSUE THREAD

**Issue by DiegoEmilio01** [UC-IIC2613/Syllabus#41]
Hola, estoy leyendo el libro y viendo mi output de mi programa y no logro entender muy bien el significado de las soluciones. Me sugirieron que eran las respuestas a través de la optimización que hace Clingo pero quería comprobar eso.

I.e. ¿La respuesta más optima es la que debería tomar el alcalde?

**Comment by FeBalla** [comment]
> Hola, estoy leyendo el libro y viendo mi output de mi programa y no logro entender muy bien el significado de las soluciones. Me sugirieron que eran las respuestas a través de la optimización que hace Clingo pero quería comprobar eso.
> 
> I.e. ¿La respuesta más optima es la que debería tomar el alcalde?

No sé si me queda muy clara tu pregunta, pero como supondrás, la sentencia `#minimize` de Clingo minimiza algo en el programa según cómo lo utilices. La idea es que lo consulten en el libro su uso, puedan experimentar quizás con algún ejemplo hecho por ustedes para comprenderlo y, luego de todo eso, ver qué implicancia tiene esa sentencia en el programa. 

De acuerdo con eso, estarás minimizando algo que tendrá una implicancia en el contexto del problema.  En la ayudantía 1 de ASP lo comenté muy por encima (demasiado, por lo que no sé si sirva de algo ir a revisarlo, aunque puede ser)

**Comment by DiegoEmilio01** [comment]
Muchas gracias por la respuesta! Creo que con los test que hice logré entender lo que hace. Según yo lo estoy usando bien. Mi output por consola sería el siguiente:

```
Solving...
Answer: 1
iluminado(a) iluminado(f)
Optimization: 2
Answer: 2
iluminado(b)
Optimization: 1
OPTIMUM FOUND

Models       : 2
  Optimum    : yes
Optimization : 1
```
Creo que me Clingo debería mostrarme solo el más óptimo, pero no hace eso. Así que me gustaría saber cómo interpretar ese otro modelo que me arroja. Porque, los "Optimization: 1" que me arrojan los test es lo que a mano debería estar correcto.

**Comment by FeBalla** [comment]
Sí lo encontró, la forma en que Clingo encuentra el óptimo es iterativa: 

"_The directives `#maximize` and `#minimize` instruct clingo to improve the first stable model that it generated using a `#sum` aggregate expression as the measure of quality, **and to keep looking for better and better stable models until the best model is found**_"

En el libro, en la página 124 habla de cómo se presenta este _output_. Lamento no poder responder de forma más clara, pero la idea es que le echen un ojo al libro 👀

**Comment by DiegoEmilio01** [comment]
Muchas graciass! Ahora entiendo a que se refería ese párrafo ajajaj
