### ISSUE TITLE
[Tarea 1] Parte 2.2

### ISSUE THREAD

**Issue by gustavobarrezueta** [UC-IIC2613/Syllabus#42]
Hola! Sé que la en la issue #21 se trata un poco de este tema pero aún no me queda muy claro el enunciado. Se nos dice que "Además, escribe el predicado conectado_k/3 que es tal que conectado_k(X,Y,K) aparece en el modelo si y solo si existe un camino entre X e Y con exactamente K arcos no iluminados. Tal como en la pregunta anterior, asegura que conectado_k no ‘pierda’ caminos en el grafo." 
Mi pregunta es si un camino entre dos nodos tiene uno (o mas) arcos iluminados entonces ese camino se anula y no se considera?, o sí se considera pero con k siendo el numero de arcos no iluminados?
Por ejemplo, teniendo el siguiente grafo, y suponiendo que el nodo "e" está iluminado; en mi programa debe aparecer conectado_k(a, e, 1)? o no debe aparecer ningún predicado conectado_k para "a" y "e" ?(si fuera así no tendría ningún predicado conectado_k para ningún nodo con "e" y "f" ).
![AFmEFvtrXzDOrLLS](https://user-images.githubusercontent.com/48266655/115485877-88f14380-a223-11eb-83dc-9b74bde71e0a.png)

**Comment by aamedinaj** [comment]
Hola, 
(voy a asumir que te refieres solo a la parte 2.2 de la issue 21)

Si tuvieses ` conectado_k(X,Y,K)` significaría que puedes tener, entre X e Y,  cualquier cantidad de calles iluminadas y `K` calles no-iluminadas. Así que en tu pregunta: sí se considera pero con k siendo el número de arcos no iluminados.
En tu ejemplo, y solo tomando `e `como nodo iluminado, debería aparecer `conectado_k(a,e,1)` (de igual forma debería aparecer `conectado_k(a,f,1)`, pues el arco` (a,b)` es el que está aportando la no-iluminada)

🦊

**Comment by gustavobarrezueta** [comment]
Entiendo perfecto. Muchas gracias!
