### ISSUE TITLE
[Tarea 1] P4.2 sin movidas shoot.

### ISSUE THREAD

**Issue by Aloncarrasco** [UC-IIC2613/Syllabus#43]
Hola,  que pasa si ya no tengo casillas seguras al momento de dispara?
debo intentar dispara a una casilla donde podría no haber un wumpus?
o puedo dispara a una casilla donde si o si ha un wumpus?

**Comment by aamedinaj** [comment]
Hola,
Te acuerdas que en el ejemplo visto en clases del wumpus el agente no se movía a una casilla hasta estar completamente seguro que, en esa casilla, no había ni  hoyo ni wumpus?
Bueno, la idea es que dispares cuando ya estés completamente seguro que estará el wumpus (o que no tienes otro camino que recorrer), porque las balas son escasas.

🦊

**Comment by jorge-ovalle** [comment]
> Hola,
> Te acuerdas que en el ejemplo visto en clases del wumpus el agente no se movía a una casilla hasta estar completamente seguro que, en esa casilla, no había ni hoyo ni wumpus?
> Bueno, la idea es que dispares cuando ya estés completamente seguro que estará el wumpus (o que no tienes otro camino que recorrer), porque las balas son escasas.
> 
> 🦊

Pero si estoy en una situación donde no tengo celdas seguras a las que moverme y no estoy seguro si en las celdas inseguras hay un wumpus o un pit, igual disparo para ver si puedo avanzar o solamente puedo disparar cuando no tengo opciones y estoy 100% seguro que en una celda en particular hay un wumpus?

**Comment by aamedinaj** [comment]
En el caso que el dices, donde ya no tiene celdas seguras y no estás seguro de sí dónde vas a disparar hay un wumpus o no, entonces deberías retornar que no hay solución
