### ISSUE TITLE
[Tarea 1] Negación en ASP

### ISSUE THREAD

**Issue by jorge-ovalle** [UC-IIC2613/Syllabus#44]
En clases no lo vimos, pero pueden haber reglas con una negación en _Head_?. Por ejemplo:
`not q :- p.`
`p.`

**Comment by aamedinaj** [comment]
Hola, 
Aunque prácticamente es posible, no tiene sentido usarla (te recomiendo no usarla).
Ejemplo:
>p.
>not q :- p.

Retornaría lo mismo que solo `p.`. Sin embargo, en la primera le dices exactamente que podría haber una constante q, entonces te va a avisar 
>info: atom does not occur in any rule head:  q

🦊
