### ISSUE TITLE
[Tarea 1] 4.2 Atributos Agente

### ISSUE THREAD

**Issue by sperezmasri** [UC-IIC2613/Syllabus#45]
Hola! Se puede crear nuevos atributos en la clase Agente? O solo se pueden usar los que ya vienen?

**Comment by jmopaso** [comment]
Hola! Si puedes agregarle atributos, lo importante es que logres lo que dice el enunciado.

Saludos!

**Comment by sperezmasri** [comment]
Ok, gracias!
