### ISSUE TITLE
[Tarea 1] Entorno observable

### ISSUE THREAD

**Issue by jorge-ovalle** [UC-IIC2613/Syllabus#47]
Que el ambiente sea observable significa que puedo saber la ubicación exacta de wumpus y pits o solamente puedo conocer su numero sin saber donde se encuentran exactamente?

**Comment by jmopaso** [comment]
Hola!

Significa que sólo sabes la cantidad, puedes obtenerla con `get_num_wumpus()` y `get_num_pits()`. Saludos
