### ISSUE TITLE
Duda output pregunta 4.1

### ISSUE THREAD

**Issue by kylevon** [UC-IIC2613/Syllabus#48]
Qué específicamente hay que incluir en el output? Pregunto esto porque no se especifica en el enunciado, por lo que no sé hasta donde incluir. Tenemos que enumerar todos los modelos que podrían ser posibles dado lo percibido? Es decir, asignar cada elemento del tablero como safe, wumpus, pit? O lo que importa tal vez sea solamente que deduzcamos los safe's en los lugares adyacentes a alive(X,Y) en cada mundo paralelo? Creo que el primer _approach_ que mencioné es ridículo dado el tamaño de la cantidad de modelos (O(3^n) siendo n la cantidad  de celdas de las cuales no tengo información.

**Comment by benjavicente** [comment]
Hola! yo le pregunté esto al profesor por lo mismo, terminé con un archivo de 100Mb realizando lo primero 😅

Hay que hacer lo segundo, solo para los adyacentes.

**Comment by kylevon** [comment]
Gracias! Solo para aclarar, si un output **solo** especifica **todos** los posibles estados (wumpu, pit, safe) **viables** (no violan con las reglas del juego) de las casillas vecinas a las que tienen alive en distintos mundos, entonces ese output sería correcto?

**Comment by FeBalla** [comment]
**Pregunta 1:**
> Qué específicamente hay que incluir en el output? Pregunto esto porque no se especifica en el enunciado, por lo que no sé hasta donde incluir. Tenemos que enumerar todos los modelos que podrían ser posibles dado lo percibido? Es decir, asignar cada elemento del tablero como safe, wumpus, pit? O lo que importa tal vez sea solamente que deduzcamos los safe's en los lugares adyacentes a alive(X,Y) en cada mundo paralelo? Creo que el primer _approach_ que mencioné es ridículo dado el tamaño de la cantidad de modelos (O(3^n) siendo n la cantidad de celdas de las cuales no tengo información.

**R:** Tal como te respondió el compañero antes, efectivamente basta con deducir `safe` para las celdas adyacentes!


**Pregunta 2:**
> Gracias! Solo para aclarar, si un output **solo** especifica **todos** los posibles estados (wumpu, pit, safe) **viables** (no violan con las reglas del juego) de las casillas vecinas a las que tienen alive en distintos mundos, entonces ese output sería correcto?

**R**: Efectivamente, ese _output_ debería ser correcto. De todos modos, confirmaré la respuesta durante mañana para ser más preciso, pero diría que estás en lo correcto 👍 .

**Comment by tomasalvarez13** [comment]
Hola, no me queda claro que debo retornar. Por ejemplo si tengo un input del siguiente tipo:
![Captura realizada el 2021-04-22 09 17 27](https://user-images.githubusercontent.com/48598610/115720988-9570bb80-a34b-11eb-942f-9f5e3bd4b574.png)
Cuales serian los modelos que debiera retornar mi programa?

**Comment by jmopaso** [comment]
Hola Tomás,

Primero que nada encuentro muy bueno que te pongas en casos y especules lo que debería retornar el archivo wumpus.lp, muy bien!
Ahora viendo tu input, hay que tomar en cuenta que tu archivo wumpus,lp debe retornar todos los mundos posibles, por lo tanto **sólo considerando los pits** (porque tu archivo wumpus.lp podría retornar los predicados que tu estimes convenientes `ej: wumpus(x,y) o safe(x,y)` ) tu programa debería retornar al menos dos modelos de la forma:
```
Modelo 1: pit(3,1) pit(4,2)
Modelo 2: pit(3,1)
```
Donde si lo piensas tiene mucho sentido, porque el predicado `pit(3,1)` sale en todos los modelos, por lo que se con seguridad que en el (3,1) hay un pozo. Sin embargo, también me aparece en uno de mis modelos el predicado `pit(4,2)`, porque existe la posibilidad de que también haya un pit en la celda (4,2), pero no puedo saberlo con seguridad.

Saludos.

PD: Todo lo anterior suponiendo que las celdas amarillas son celdas visibles y las verdes no visibles.

**Comment by tomasalvarez13** [comment]
Buenisimo ahi me quedo claro, te pasaste

**Comment by kylevon** [comment]
Gracias, a mi también me quedó claro 👍
