### ISSUE TITLE
[Tarea 1] 4.1 Safe

### ISSUE THREAD

**Issue by CataAlamos** [UC-IIC2613/Syllabus#49]
Hola, tengo una duda sobre ¿Qué consideramos como safe? ¿El agente esta safe si cae en un lugar donde hay breeze o stench? También, intente probar mi código con extra.lp y me da un solución unsatisfiable. ¿Está bien lo entregado en extra?
Muchas gracias

**Comment by FeBalla** [comment]
> Hola, tengo una duda sobre ¿Qué consideramos como safe? ¿El agente esta safe si cae en un lugar donde hay breeze o stench? También, intente probar mi código con extra.lp y me da un solución unsatisfiable. ¿Está bien lo entregado en extra?
> Muchas gracias

Hola! 😄 El predicado `safe(x,y)` es una sentencia que recomendamos usar porque puede facilitar el trabajo, pero el enunciado no te obliga a usarlo. Sin embargo, para ayudarte con tu duda: les propusimos el predicado `safe(x,y)` que representa que moverse a la celda `(x,y)`  - que no ha sido necesariamente visitada - es seguro. Por lo tanto, `safe` no señala que la celda en la que se está actualmente sea segura, pues eso sería más similar a `alive` (que indica que está vivo), sino que indica que, dado el conocimiento que tienes, el movimiento hacia la celda `(x,y)` es ciertamente **seguro**.
