### ISSUE TITLE
[Tarea 1] Correspondencia preguntas-archivos

### ISSUE THREAD

**Issue by sofiacorreabusquets** [UC-IIC2613/Syllabus#5]
Hola! Tengo dos confusiones con respecto al enunciado de la tarea, que me imagino se podrían deber solamente a _typos_.

1. En la parte 2, la pregunta 1 no aparece como contenido en ninguno de los archivos a entregar, mientras que la pregunta 2 es la única que aparece tanto en el PDF como en un archivo LP. ¿Dónde se responde la pregunta 1? Y, para la 2, ¿tanto se programa en un LP como se describe en el PDF? ¿Se supone que uno de esos dos números "2" diga en realidad "1"?

2. Dentro de los archivos a entregar, las partes 1 y 3 piden un pdf que se llame `respuesta`, pero la 2 pide uno que se llame `respuestas`. ¿Cuidamos mantener esa diferencia en el etiquetado para concordar con el enunciado, o usamos solo uno de esos nombres por consistencia?

Gracias de antemano 🤗

**Comment by aamedinaj** [comment]
Hola, respondiendo una mitad de tus dudas
> 1. En la parte 2, la pregunta 1 no aparece como contenido en ninguno de los archivos a entregar, mientras que la pregunta 2 es la única que aparece tanto en el PDF como en un archivo LP. ¿Dónde se responde la pregunta 1? Y, para la 2, ¿tanto se programa en un LP como se describe en el PDF? ¿Se supone que uno de esos dos números "2" diga en realidad "1"?

Referenciando una [issue previa](https://github.com/UC-IIC2613/Syllabus/issues/4#issuecomment-817237256), en la parte2/pregunta1 te piden una explicación, por lo que debería ir en el pdf. Por otro lado, en la pregunta 2 te piden que modifiques código, pero no se indica una explicación, por lo que debería entregar solo el `.lp` de esa pregunta.

**en caso de cualquier modificación de esto se avisará oportunamente**

🦊

**Comment by aamedinaj** [comment]
> 2. Dentro de los archivos a entregar, las partes 1 y 3 piden un pdf que se llame `respuesta`, pero la 2 pide uno que se llame `respuestas`. ¿Cuidamos mantener esa diferencia en el etiquetado para concordar con el enunciado, o usamos solo uno de esos nombres por consistencia?

Da lo mismo, no hay que tener tanto cuidado en eso. 

🦊

**Comment by sofiacorreabusquets** [comment]
@aamedinaj Muchas graciassss
