### ISSUE TITLE
[Tarea 1]  Pregunta 3.3 duda enunciado

### ISSUE THREAD

**Issue by DiegoEmilio01** [UC-IIC2613/Syllabus#50]
"Supón ahora que permitimos incorporar algunas reglas con negación y que estas reglas podrían generar múltiples modelos. No permitiremos disyunción en los programas, (...)"

¿No se contradice el enunciado al decir que podría haber múltiples modelos pero no hay disyunción? o  ¿se refiere a que podríamos tener pero dada la condición establecida después no hay múltiples modelos?

**Comment by FeBalla** [comment]
> "Supón ahora que permitimos incorporar algunas reglas con negación y que estas reglas podrían generar múltiples modelos. No permitiremos disyunción en los programas, (...)"
> 
> ¿No se contradice el enunciado al decir que podría haber múltiples modelos pero no hay disyunción? o ¿se refiere a que podríamos tener pero dada la condición establecida después no hay múltiples modelos?

No me termina de quedar muy clara tu duda, pero creo que hay una pequeña confusión con el enunciado 👀. Se te dice que se permite incorporar reglas con negación, pero no con **disyunción**. Un ejemplo de una regla con **disyunción** podría ser la siguiente sentencia:
````
p, q :- r.
````
Habíamos comentado en clases que este tipo de reglas puede llegar a presentar comportamientos que, a primera vista, pueden parecer contra intuitivos, pero que se explicaban en base al concepto de minimalidad del modelo. Acá se te señala que **no habrán reglas de este tipo**. Por lo tanto, no veo la contradicción que señalas, pero pienso que quizás se trata de una confusión con el término **disyunción** más que nada. Cualquier cosa, puedes volver a preguntar por esta misma _issue_ 😃 .

**Comment by DiegoEmilio01** [comment]
Okey. Me causó confusión que dijera que podría, pero no habrán; en vez de decirlo altiro jajajaja. Muchas graciass!
Edit: ya entendí que podría pasar jajajaj
