### ISSUE TITLE
Duda pregunta 4.2, uso de wumpus.lp en agent.py

### ISSUE THREAD

**Issue by kylevon** [UC-IIC2613/Syllabus#51]
Para la pregunta 4.2 se espera el uso del archivo wumpus.lp que creamos anteriormente? Si no es así, lo podemos usar de todos modos? Usando algo como:

```
import subprocess
subprocess.call("llamada a wumpus.lp", shell=True)
```

**Comment by aamedinaj** [comment]
Hola, ~~como se comentó en la sesión de la mañana~~ es esencial que en la primera parte hagas un archivo wumpus.lp para trabajar en la segunda parte.

🦊

**Comment by kylevon** [comment]
Entonces sí puedo usar el archivo wumpus.lp en agents.py? Cómo lo uso? Con la estrategia que planteé?

**Comment by benjavicente** [comment]
En el archivo que entregan se hace esa llamada a `wumpus.lp` junto al input sensorial (`extra.lp`), línea 84 o 86:
https://github.com/UC-IIC2613/Syllabus/blob/9443f5a804cf7cd024e3fc9473b9ec138fe5fefc/Tareas/Tarea%201/Parte%204/agent.py#L81-L87

**Comment by kylevon** [comment]
Oh, perfecto. Gracias de nuevo Benja 😁
