### ISSUE TITLE
Pregunta 2.2 con ciclos

### ISSUE THREAD

**Issue by FelipeA7** [UC-IIC2613/Syllabus#52]
Hola, si tengo un grafo con varios arcos y ciclos, entonces es posible que el predicado conectado_k entregue varios resultados para algún valor de X e Y?
Por ejemplo, si tengo el grafo: (lo amarillo está iluminado)
![image](https://user-images.githubusercontent.com/48482398/115782003-22863580-a389-11eb-944d-dccd7358e8b9.png)
Estaría correcto que mi programa entregue conectado_k(a,e, 0) y conectado_k(a,e,2) al mismo tiempo?
Pues se puede ir de A a E a través de (A->B->E) que tiene 0 caminos no iluminados y también a través de (A->B->C->D->E) que tiene 2 camino no iluminados

**Comment by jfuentesg26** [comment]
Hola! Tu programa si estaría correcto, ya que para ambos predicados, conectado_k(a,e,0) y conectado_k(a,e,2), existe un camino entre a y e con la cantidad de arcos no iluminados que corresponde.

**Comment by FelipeA7** [comment]
Gracias!

**Comment by emyskog** [comment]
Mi pregunta es similar, pero que pasa si es conectado_k(e,e,2) y conectado_k(e,e,4), y el camino que toman es el mismo, solo que uno va y vuelve? Puede devolverse al mismo nodo?

**Comment by jfuentesg26** [comment]
Hola! A que te refieres con que "va y vuelve"?

**Comment by FelipeA7** [comment]
Retomando esto pero para la pregunta 2.3 de camino_minimo, puede ser que esta retorne más resultados de los que se debe? Por ejemplo, con el ejemplo anterior, dentro de los outputs de camino_minimo obtengo "camino_minimo(a,e,2)" y también "camino_minimo(a,e,0)".
El primero se obtiene pues es el camino con menor calles iluminados si usamos la ruta (A->B->C->D->E)
el segundo es el camino con menor calles iluminados si usamos la ruta (A->B->E)

Está bien que retorne los 2 o debería retornar solo la segunda? Sé que quizás es medio trivial pero no se me ocurre como filtrar el primer resultado :(
