### ISSUE TITLE
Pregunta 1.2

### ISSUE THREAD

**Issue by FelipeA7** [UC-IIC2613/Syllabus#53]
Hola, a qué se refiere con sistema computacional en la 1.2?

**Comment by aamedinaj** [comment]
Ve si te sirve una [respuesta anterior](https://github.com/UC-IIC2613/Syllabus/issues/4#issuecomment-817322944) . Si no te sirve, detalla un poco más 🙏 

🦊

**Comment by FelipeA7** [comment]
gracias, no había visto eso
