### ISSUE TITLE
[Tarea 1] #Minimize solo entrega una solución (Parte 2.5)

### ISSUE THREAD

**Issue by PabloRabeloRoa** [UC-IIC2613/Syllabus#54]
Hola, he estado trabajando en la parte 2 pregunta 5 y logro encontrar una respuesta óptima, sin embargo solo se muestra una y no todas. Se que hay otras respuestas óptimas distintas ya que cuando excluyo el modelo que me entrega en la primera ocasión encuentra otra respuesta distinta de igual tamaño (valor óptimo). Mi duda es como se puede mostrar todos estos modelos óptimos.

**Comment by FeBalla** [comment]
Hola, lamento la demora 😢 Si te refieres a cómo pedirle a Clingo que muestre todos los modelos de un programa, debes añadir el _flag_ `-n0` al comando de ejecución. En las _slides_ de la Ayudantía 1 hay información sobre esto!

**Comment by tomytable** [comment]
Hola, no sé si Pablo se refería a esto pero yo estoy teniendo el mismo problema. Tengo una configuración en la que se puede prender un nodo u otro y en ambos casos resulta. Es decir, tengo dos óptimos en los que puedo prender solo un nodo, sin embargo, al minimizar los modelos, clingo entrega solo uno de ellos a pesar de usar el flag ```-n0```. Basta con que muestre uno o debo mostrar todos los óptimos?
Gracias

**Comment by FeBalla** [comment]
> Hola, no sé si Pablo se refería a esto pero yo estoy teniendo el mismo problema. Tengo una configuración en la que se puede prender un nodo u otro y en ambos casos resulta. Es decir, tengo dos óptimos en los que puedo prender solo un nodo, sin embargo, al minimizar los modelos, clingo entrega solo uno de ellos a pesar de usar el flag `-n0`. Basta con que muestre uno o debo mostrar todos los óptimos?
> Gracias

Ah, comprendo tu duda. Bastaría con que muestres uno de los óptimos, siempre y cuando realmente lo sea! 😄
