### ISSUE TITLE
[Tarea 1] 4.2 código agent.py, return de unsat_without

### ISSUE THREAD

**Issue by sgutgar** [UC-IIC2613/Syllabus#55]
Hola, quería saber si el código que viene escrito en agent.py se debe dejar intacto o no, ya que por ejemplo en la linea 90, la función unsat_without dentro de get_action retorna solo un boolean en torno a los modelos. Esto es ineficiente ya que como voy a necesitar los modelos afuera de esta función tendría que volver a repetir el código. Se puede cambiar este return o el codigo se debe dejar intacto.

**Comment by jmopaso** [comment]
Hola, 

Es preferible que dejes el código base intacto, sobre todo lo que está dentro de `get_action`, además no es estrictamente necesario que hagas uso de la función `unsat_without` para tu solución, está se dejó ahí porque para el profesor le fue útil usarla. También considera que la función `unsat_without` no está completa, esta deberías adaptarla según tu solución para que te retorne lo deseado (`True` si programa resultante no tiene modelos y `False` en caso contrario).

No entendí muy bien a que te refieres con usar los modelos afuera de esa función. La idea es que dentro de la función `get actions` hagas todo lo necesario para retornar el movimiento del agente.

Saludos!

**Comment by carolinamaggi** [comment]
Me sumo a la pregunta porque yo también retorné los modelos en usan_without() y no solamente True o False

**Comment by Pdesolmi** [comment]
Yo también retorno modelos en esa función
