### ISSUE TITLE
[Tarea 1] 4.2 ejemplo enunciado

### ISSUE THREAD

**Issue by sgutgar** [UC-IIC2613/Syllabus#56]
Hola, quería saber si el paso 4 que se hace en el enunciado (['go to', 1, 2]) esta bien. Ya que según lo que yo entendí el agente no tiene porque saber que ese lugar es safe, ya que tanto el sense breeze como el sense stench podrían significar que en esa posición hay algo.

**Comment by sufigueroa** [comment]
Holaa! El agente si puede saber que la celda (1, 2) es segura porque si el wumpus hubiese estado ahi, hubiera sentido su olor en (1, 3) pero no lo hizo. Lo mismo con el pit, si este hubiese estado en el (1, 2) el agente hubiera sentido la brisa en el (0, 2) :)
