### ISSUE TITLE
Pregunta 2.2 Tuplas

### ISSUE THREAD

**Issue by tvallotton** [UC-IIC2613/Syllabus#58]
Hola, quiero saber como contar un objeto compuesto por otros dos objetos dentro de un set. Intente con cosas como:
```
#count { (X, Y) : expr(X, Y) }
#count { X, Y : expr(X, Y) }
#count { tupla(X, Y) : expr(X, Y) }
```
Pero ninguna me resulta. Hay alguna forma de hacer esto?

**Comment by sufigueroa** [comment]
Holaa! Creo que no entiendo muy bien lo que quieres contar, puedes explicarmelo mejor plis? :)

**Comment by tvallotton** [comment]
Lo que pasa es que estoy tratando de contar el numero de arcos(X, Y). Puedo contar los nodos si hago algo como `#count { X : condicion(X) }`, pero no puedo contar el numero de arcos `#count { arco(X, Y) : condicion(X) }`. Queria saber si hay alguna manera de hacer algo asi.

**Comment by sufigueroa** [comment]
Siii claro que se puede, el lado izquierdo de tu count esta bien. Trata probando con condiciones distintas para que veas como funciona el count.

**Comment by tvallotton** [comment]
Ah. Ahora hice un test y me funcionó. Gracias

**Comment by sufigueroa** [comment]
Yaa buenisimo!! Suerte!! :)
