### ISSUE TITLE
[Tarea 1] Duda 2.2

### ISSUE THREAD

**Issue by gsalinas0** [UC-IIC2613/Syllabus#59]
Hola, tengo una duda con la 2.2 de la Tarea.
Lo que pasa es que el enunciado indica lo siguiente.
_escribe el predicado iluminada/2 que es tal que iluminada(X,Y) aparece en un modelo únicamente cuando (X,Y) es un arco que representa a una calle que está iluminada._
Definí un grafo como el de esta foto.
![image](https://user-images.githubusercontent.com/68198662/115970914-96ece000-a513-11eb-9a68-393e08169ba2.png)
y clingo me arroja este modelo al "iluminar" los nodos A y B.
![image](https://user-images.githubusercontent.com/68198662/115970994-006cee80-a514-11eb-8daa-b998ec427ec5.png)
Mi pregunta es si es necesario "recortar" a la mitad los resultados para que no se muestren redundancias. Por ejemplo, para este grafo concreto, deberían contener el modelos simultáneamente a `iluminada(a, e)` y  `iluminada(e, a)`?

Gracias de antemano

**Comment by sufigueroa** [comment]
Holaa! Claro que puedes dejarlo asi, como son grafos no dirigidos para ambos direcciones es cierto :)
