### ISSUE TITLE
[Tarea 1] Posible error en Parte 2 del Ejercicio 1

### ISSUE THREAD

**Issue by benjavicente** [UC-IIC2613/Syllabus#6]
Hola! Parece que esto que nos entregan está malo:

```prolog
arco(a,b).
arco(b,c).
arco(b,e).
arco(e,f).
nodo(X) :- arco(X,Y).
nodo(Y) :- arco(X,Y).

camino(X,Y,Largo) :- arco(X,Y), Largo=0.  % Largo 0?
camino(X,Y,Largo) :- camino(X,Y,L1), camino(X,Y,L2), Largo=L1+L2.  % Suma el largo del mismo camino?
```
Si el largo inicial es `0`, el largo nunca aumentará en la suma `Largo=L1+L2 -> 0 = 0 + 0`. Creo que debería ser `1`.
Además el segundo predicado de camino se está sumando el largo del mismo camino. Creo que debería haber un nodo intermediario (`camino(X,Z,L1), camino(Z,Y,L2)`).

**Comment by nachobascar** [comment]
Me sumo para esperar por la respuesta

**Comment by jmopaso** [comment]
Hola Benjamín,

Efectivamente se trata de un error en el código, este ya fue modificado en el enunciado de la tarea. Muchas gracias por avisarnos!

El código finalmente quedó asi.
```
arco(a,b).
arco(b,c).
arco(b,e).
arco(e,f).
nodo(X) :- arco(X,Y).
nodo(Y) :- arco(X,Y).

camino(X,Y,Largo) :- arco(X,Y), Largo=1.
camino(X,Y,Largo) :- camino(X,Z,L1), camino(Z,Y,L2), Largo=L1+L2.
```

Saludos!
