### ISSUE TITLE
[Tarea 1] P2.1

### ISSUE THREAD

**Issue by beatrizacuna** [UC-IIC2613/Syllabus#60]
Hola! Estoy teniendo problemas con count.
La siguiente línea : #count{ X : camino(X,Y,Largo)}. debería contar los elementos del conjunto camino(X,Y,Largo)? Y si no, qué hace?
Gracias :)

**Comment by sufigueroa** [comment]
Holaa! Lo que haria ese count seria contar cuantos X aparecen cuando camino(X,Y,Largo) se cumple. Se entiende? :)

**Comment by beatrizacuna** [comment]
o sea siempre sería 1?

**Comment by sufigueroa** [comment]
Probablemente si
