### ISSUE TITLE
[Tarea 1] 2.4 Interpretación tamaño del programa

### ISSUE THREAD

**Issue by tomytable** [UC-IIC2613/Syllabus#61]
Hola, tengo la duda de lo que se refiere el tamaño del programa instanciado. Es la cantidad de instancias para cada uno de nuestros predicados en función de m y n? Hay que obtener resultados independientes para el el programa de la pregunta 2 y 3?

Gracias!

**Comment by emyskog** [comment]
up

**Comment by jac-34** [comment]
up x2

**Comment by fernandomg18** [comment]
up x3

**Comment by jfuentesg26** [comment]
Hola! Con respecto a la primera parte de tu pregunta la cantidad de instancias hace referencia a la suma de los átomos instanciados para cada uno de tus predicados. Como ejemplo supón el siguiente programa:

animal(X) :- gato(X)
gato(felix)

Nota que esto genera 2 átomos instanciados que son gato(felix) y animal(felix), entonces tu cantidad de instancias es 2. Ahora para tu caso debes buscar una forma de expresar esa cantidad de instancias en función de m y n. 

Con respecto a lo segundo, debes entregar un solo resultado que contenga tanto las instancias generadas por los predicados de la pregunta 2 como de la pregunta 3. 

Espero haya quedado claro! Cualquier cosa estaré atenta :)

**Comment by tomytable** [comment]
Me queda claro, gracias!
