### ISSUE TITLE
[Tarea 1] P.4 "atom does not occur in any rule head:   sense_breeze(X,Y)"

### ISSUE THREAD

**Issue by DiegoEmilio01** [UC-IIC2613/Syllabus#62]
Hola, mi programa funciona bien al parecer, pero cuando el agente no ha descubierto celdas con olor o briza, su respectiva regla arroja esta advertencia en el output. ¿Es correcto que lo haga? ¿Existe alguna forma de silenciarlo (desde el código o comando de ejecución)?

¡Muchas gracias por adelantado!

**Comment by dtgazmuri** [comment]
Hola!

Tal como dices tanto tú como el mensaje, esto ocurre porque ninguna regla que contenga a `sense_breeze(X,Y)` en la `Head` es parte del modelo. Esto no es un problema. Más que una advertencia es simplemente información.
