### ISSUE TITLE
P.3.1 - Subconjunto de si mismo

### ISSUE THREAD

**Issue by amahns1** [UC-IIC2613/Syllabus#63]
Hola!

En la definición vista en clases, `M` es un modelo de `π` solamente si `M` es minimal. 
En la pregunta nos piden demostrar: dado `π subset π'` y `M` modelo de `π`, mostrar que existe `M'` de `π'` tal que `M subset M'`.

Mi duda es que me da la sensación de que `M` debe ser igual a `M'` para que se cumpla `M subset M'`. No veo manera de que en todos los casos haya un minimal `M'` que sea más grande o igual que `M`. Puede ocurrir que `M' subset M`
¿Es correcta la intuición? ¿Tienen que ser distintos `M'` y`M`?

**Comment by dtgazmuri** [comment]
Hola!

No necesariamente son iguales. Piensa que `M'` es un modelo de un programa que tiene al menos las mismas reglas que el programa del cual `M` es modelo. El programa `\pi'` puede contener reglas adicionales no presentes en `pi`(debido a que `\pi \subset \pi'`), las cuales deberán ser consideradas a la hora de construir un modelo para él.

**Comment by dtgazmuri** [comment]
Hola!

No necesariamente son iguales. Piensa que `M'` es un modelo de un programa que tiene al menos las mismas reglas que el programa del cual `M` es modelo. El programa `π'` puede contener reglas adicionales no presentes en `π` (debido a que `π subset π'`), las cuales deberán ser consideradas a la hora de construir un modelo para él.

**Comment by amahns1** [comment]
Hola!

Entiendo. Pero en la definición de programa sin negación se exige que `M` sea un modelo minimal de un programa `π`. Además, hay que probar que existe un modelo `M'` perteneciente a `π` tal que `M subset M'`. En ese caso, si `M'` es más grande que `M` dejaría de ser minimal, por lo que para que `M'` sea minimal de `π'`, `M'` no debería ser equivalente a `M`?

**Comment by dtgazmuri** [comment]
Para que `M` sea modelo de un programa `π`, se debe cumplir que `M ∩ Head ≠ ∅` para cada `Head ← Body ∈ π` donde `Body ⊆ M`. Así, si el programa `π'` introduce reglas nuevas (respecto a `π`), estas **deben** ser consideradas al construir un modelo `M'`. El concepto de minimalidad no se trata de ignorar reglas que deben considerarse, sino que de elegir la mínima cantidad de átomos posibles de cada una de estas.

**Comment by beatrizacuna** [comment]
@dtgazmuri  Aquí querias decir Body ⊆ M?

**Comment by dtgazmuri** [comment]
Sí, tienes razón. Lo editaré.
Gracias!
