### ISSUE TITLE
[Tarea 1] Pregunta 3.3 - A qué se refiere con "átomos negados"?

### ISSUE THREAD

**Issue by dfloreaa** [UC-IIC2613/Syllabus#64]
A la hora de calcular la complejidad de nuestro algoritmo, dice que a lo más puede ser exponencial en el número de átomos negados en el programa, a que se refiere con "átomos negados"? En el enunciado dice que el programa es sin negación

**Comment by jfuentesg26** [comment]
Hola! El programa si tiene negación, nota que el enunciado dice justo después de la enumeración :  "Supón ahora que permitimos incorporar algunas reglas con negación...".

En este caso los átomos negados son aquellos que provienen de predicados que se niegan en tu programa. Espero haya quedado claro! Quedo atenta :)
