### ISSUE TITLE
[Tarea 1] Cardinalidad de Body en 3.2

### ISSUE THREAD

**Issue by benjavicente** [UC-IIC2613/Syllabus#65]
Hola! Las reglas tipo ``Head ← Body`` pueden tener ``Body = 0``, es decir, reglas de formato `a :- .` o `a.`?

**Comment by dtgazmuri** [comment]
Hola!

Las dos siguientes líneas son equivalentes y válidas:

`a :- .`
`a.`

En ambos casos, `a` estará en el modelo.

Saludos

**Comment by fernandomg18** [comment]
Hola! otra duda relacionado con esto, las reglas del tipo `:- a` quieren decir que la cardinalidad del Head es 0? y por lo tanto el Head de algún modo seria vacío?

**Comment by dtgazmuri** [comment]
Una regla de ese tipo funciona como la negación de `a`. Esto quiere decir que si escribes la regla `:- a.`, `a` no estará en el modelo.

**Comment by fernandomg18** [comment]
Muchas gracias!
