### ISSUE TITLE
[Pregunta 2.1] Camino de varios largos.

### ISSUE THREAD

**Issue by knight-who-says-ni** [UC-IIC2613/Syllabus#66]
Hola!! Tenia una duda con la 2.1, y es que podría pasar que entre dos nodos hay más de una manera de llegar de uno al otro (sin ciclos). En este caso, deberíamos mostrar solo la más corta? O esta bien si mostramos ambas??

Muchas gracias!!

**Comment by jfuentesg26** [comment]
Hola!! Esta bien si muestras ambos caminos si es que son distintos :)

**Comment by knight-who-says-ni** [comment]
Gracias!!
