### ISSUE TITLE
[Tarea 1] Disparar sin saber si hay wumpus

### ISSUE THREAD

**Issue by nachobascar** [UC-IIC2613/Syllabus#67]
Hola!! Quería saber si, en el caso que no haya nada más que hacer, y se tengan celdas donde podrían haber wumpus pero no se sabe con seguridad. ¿Podría disparar a esas celdas y luego marcarlas como seguras? Ya que, aunque no haya un wumpu, después de disparar es seguro que no hay nada. ¿O solo se puede disparar cuando se sabe con seguridad que hay un wumpu?

**Comment by jmopaso** [comment]
Hola!

Es preferible que dispares sólo cuando estás seguro que ahí hay un wumpus, revisa la issue #43 donde se habla algo parecido.

Saludos!
