### ISSUE TITLE
Duda enunciado pregunta 3.3

### ISSUE THREAD

**Issue by amahns1** [UC-IIC2613/Syllabus#68]
Hola!

El enunciado de la pregunta 3.3 dice 

> Entrega un algoritmo recursivo, que sea en el peor caso exponencial en el número de átomos que
aparecen negados en tu programa, y que usa al algoritmo descrito arriba como subrutina para calcular
correctamente todos los modelos.

Tego un par de dudas respecto a esto y a la pregunta en general:

1) No me queda claro la función del nuevo algoritmo. ¿El algoritmo debe calcular los modelos posibles del programa con negación?
2) Cuando piden que en el peor caso sea exponencial lo entiendo. ¿A qué se refiere con que sea en el peor caso exponencial en el número de átomos que aparecen negados en el programa? ¿El algoritmo debe calcular la cantidad de átomos negados?
3) ¿Qué es exactamente un átomo negado? Si tengo por ejemplo not q, q sería un átomo negado que tengo que contabilizar?

Gracias y muchos saludos :)

**Comment by dtgazmuri** [comment]
Hola!

1. Sí, debe retornar todos los modelos de un programa que podría tener algunas reglas con negación.
2. Se refiere a que la complejidad debe ser, en el peor caso, igual o menor a exponencial respecto a la cantidad de reglas con negación en el programa. No debes calcular la cantidad de átomos negados. Te recomiendo revisar e intentar entender la notación O de complejidad.
3. Sí, lo sería. Además, una regla con negación es de la forma `Head ← Pos, not (Neg)`, donde Head, Pos y Neg son conjuntos de átomos.

Saludos y éxito!

**Comment by amahns1** [comment]
Entiendo.

Gracias!
