### ISSUE TITLE
Inducción en Pregunta 3.2

### ISSUE THREAD

**Issue by ignaciovilla** [UC-IIC2613/Syllabus#69]
Leyendo la issue #34 me surge la siguiente duda, ¿si n=0 entonces |Head| = 0, o puede ocurrir que n=0 y |Head| = 1?
Muchas gracias

Quería agregar, que tan formal tiene que ser la demostración? en el sentido de que estoy recién teniendo un ramo en que se habla sobre las demostraciones formales y no se si con lo que se hasta ahora puedo hacer una demostración formal a este problema.
Muchas gracias nuevamente.

**Comment by jfuentesg26** [comment]
Hola! El caso que sugieres no puede ocurrir, nota que si ya tienes un |Head| = 1, tu programa puede ser algo asi:

gato(X)

Pero gato(X) ya cuenta como regla, así que es contradictorio.  Con respecto a la formalidad, te recomiendo que estudies un poquito sobre inducción, pero básicamente debes encontrar un caso base que sabes que cumple lo pedido, y encontrar un "paso de inducción" que te permita decir "Si se cumple esto para X entonces se cumple para X + 1", quedando esas dos cosas claras y bien explicadas tu demostración debería estar bien. Escríbeme si no quedo claro! Saludos!

**Comment by ignaciovilla** [comment]
En este caso "Si se cumple esto para X entonces se cumple para X + 1", si tendría que considerar ambos casos |Head|=0 y |Head|=1 para "X" y "X+1" o no?
Y además tengo la misma duda sobre formalidad para toda la pregunta 3, porque en la 3.1 también se pide una demostración y no se como verificar que lo que hice en el resto de la pregunta cumple con la formalidad.
Muchas gracias

**Comment by jfuentesg26** [comment]
Con respecto a la primera parte debes considerar todos los casos donde |Head| <= 1 como lo dice el enunciado.
Con respecto a la pregunta 3.1 puedes basarte en el formato que utiliza el profesor en sus demostraciones.

**Comment by ignaciovilla** [comment]
Muchas gracias
