### ISSUE TITLE
[Administrativo] Discord

### ISSUE THREAD

**Issue by beatrizacuna** [UC-IIC2613/Syllabus#71]
Hola! Quería saber si tenemos discord del curso, porque tengo unas dudas en mi código que preferiría en lo posible responder por voz 😄

**Comment by Dnpoblete** [comment]
Hola @beatrizacuna! 

Lamentablemente no tenemos Discord y veo complicado que lo implementemos para este semestre dado la cantidad de ayudantes que somos y el tiempo extra que implicaría tener un Discord 😔.  De todas formas hablaré el tema con los profesores, con la finalidad de ver si podríamos hacer algo por el estilo para un par de ayudantías este semestre, pero lo veo muy poco probable. De todas formas te invito a enviar tus dudas por una o más issues, se que a veces es más fácil hacerlo por voz y compartir pantalla, pero puedes explicarlo lo más detallado por escrito y enviar pantallazos (sin dar la respuesta) como se ha hecho en otras issues, y de paso resolvemos la duda una vez y le queda al resto de les estudiantes en caso de que tengan la misma duda 😄.

Mucho éxito en la Tarea ✨

**Comment by beatrizacuna** [comment]
Encuentro buena opción la de dedicar ayudantías a resolver dudas de la tarea, ojalá se pueda hacer 😄
