### ISSUE TITLE
[Tarea 1] 2.5: No logro encontrar el mínimo

### ISSUE THREAD

**Issue by gsalinas0** [UC-IIC2613/Syllabus#72]
Hola. Para la actividad 2.5 de la tarea en mi codigo realizo lo siguiente:

- defino el grafo, nodos y arcos.
- defino un predicado `contar_encendidos` que me cuenta cuantos nodos tengo iluminados. Esto es lo que intento minimizar.
- defino los predicados `iluminada` y `arco_oscuro` que me indican si un arco del grafo está siendo iluminado o no.
- defino el predicado conectado_k(X,Y,K), que de aparecer en el modelo, indica que entre los nodos Xe Y hay un camino que tiene K arcos sin iluminar (arcos oscuros).
- defino el predicado `camino_oscuro(X,Y,K)`, que aparece en el modelo si existe un `conectado_k(X,Y,K)` con K>1.

Luego para intentar usar el `minimize`
- dejo un predicado que permita a clingo "encender/iluminar" los nodos que quiera, como en el ejemplo del libro.
- hago un regla que filtre los `caminos_oscuros`
- hago una regla que con `minimize`, minimice el argumento de `contar_encendidos`. Según mi razonamiento, debería minimizar la cantidad de nodos que se encienden, para que así este predicado tenga un menor valor.

Con este grafo:
![image](https://user-images.githubusercontent.com/68198662/116160917-dc9adb80-a6c0-11eb-8ee5-194da4dcba1b.png)

Obtengo este resultado:
![image](https://user-images.githubusercontent.com/68198662/116160888-d278dd00-a6c0-11eb-97fb-b1b6ccd3fc28.png)

Cosa que se me hace muy extraña, ya que claramente solamente con iluminar el nodo F debería ser suficiente para que se cumpla la condición, ya que siempre existirían caminos desde un nodo a otro con a lo más 1 camino sin iluminar (K =<1).
Algo que me llama la atención, es que al mostrar los `conectado_k(X,Y,K)`, solo se me muestran los caminos que tienen K=0, cuando yo en ningún momento defino que K debe ser necesariamente 0.

¿Qué es lo que puedo estar haciendo mal?¿Entendí mal como se usa el minimize?¿Está mal mi razonamiento?

Saludos

**Comment by FeBalla** [comment]
Hola! Es un poco complicado saber con certeza qué puede estar fallando, ya que no podemos ver el código. Sin embargo, por la naturaleza de la respuesta creo que lo que puede estar fallando es la parte en la que detectas que efectivamente se pueda llegar a cualquier nodo con a lo más una calle oscura. Creo esto por lo siguiente:

- El primer modelo que encuentra durante el proceso de optimización tiene iluminados los nodos `A`; `C` y `E`. Si bien esto **no tiene que ser necesariamente así**, ya que aún no encuentra el supuesto óptimo, parece estar buscando una disposición de la luminaria tal que todos los nodos estén adyacentes a uno encendido.
-  Teniendo en cuenta lo anterior, pareciera que esta condición se repite en el óptimo que encuentra tu modelo, puesto que `B` no necesita realmente estar encendido, pero da la sensación que, por como definiste algún predicado, no le es posible estar sin contacto de un nodo iluminado.

Por lo tanto, si bien **no significa que el error esté aquí** 👀, trataría de _debuguear_ inicialmente bajo esta lógica, es decir, revisar el predicado que verifica la condición de a lo más una calle oscura entre cualquier par de nodos.
