### ISSUE TITLE
[Tarea 1]  complejidad 3.3

### ISSUE THREAD

**Issue by lucas-valenzuela** [UC-IIC2613/Syllabus#73]
Hola, 

El enunciado dice:
> Entrega un algoritmo recursivo, que sea en el peor caso exponencial en el número de átomos que aparecen negados en el programa (...)

Entiendo con exponencial que la complejidad máxima sería algo del estilo `base^n`. Ahora bien, podría ser base igual a `n`, implicando que la complejidad límite es `n^n`? Lo pregunto porque no se dice nada con respecto a la base, y matemáticamente hablando tengo extendido que `n^n` también es una expresión exponencial.

Lo pregunto porque creo cómo hacer una solución factorial que cumple que `O(n!) < O(n^n)`

Saludos

**Comment by aamedinaj** [comment]
Hola, si te fijas `n^n` es mucho más violento que una base fija, crece mucho más rápido que un orden exponencial. No podrías usarlo. 

🦊
