### ISSUE TITLE
[Tarea 1] - Duda cantidad modelos Parte 3.2

### ISSUE THREAD

**Issue by benjavicente** [UC-IIC2613/Syllabus#74]
En el enunciado se menciona que hay que demostrar para `|Head| <= 1`, cuando debería ser `|Head| = 1`, ya que con `|Head| = 0` el enunciado a demostrar es falso.

**Comment by jmopaso** [comment]
Hola! Fíjate que en el enunciado se señala que tiene `a lo más un modelo`.

Saludos.

**Comment by benjavicente** [comment]
Va, toda la razón 😅
