### ISSUE TITLE
[Control Clase 12] Duda enunciado

### ISSUE THREAD

**Issue by CataAlamos** [UC-IIC2613/Syllabus#75]
Hola, tengo dudas del enunciado, ¿En las grillas se permite el movimiento diagonal? Otra duda que tengo, ¿Cuando dice que se expande dos nodos, se refiere que los dos caminos llegan al nodo objetivo y de ahí se compara O se expande solamente C1, y se da vuelva a C2 y C4?
Muchas gracias

**Comment by tomytable** [comment]
Tengo la misma duda respecto a los nodos que "expando". ¿Considero que expandir el nodo es ver con quienes está conectado? Y en ese caso, considero que estoy expandiendo el nodo inicial (h=4)? O empiezo a contar los expandidos con los nodos h=3 y h=3? 
Gracias

**Comment by Jamidd** [comment]
Hola, 

> ¿En las grillas se permite el movimiento diagonal?

como se dice en el enunciado, estan disponibles los 8 movimientos (arriba, abajo, izq, der, diag izq sup, diag izq inf, diag der sup, diag der inf).

> ¿Cuando dice que se expande dos nodos, se refiere que los dos caminos llegan al nodo objetivo y de ahí se compara O se expande solamente C1, y se da vuelva a C2 y C4?

En A* existe una parte del algoritmo que se conoce como expansión. En esta tú eliges un nodo bajo un criterio y revisas a sus "hijos" para ver si los metes a la lista `Open`. Lo que se pide es que esta parte del algoritmo solo se ejecute dos veces antes de terminar la ejecución del algoritmo y entregar la solución. ¿Cuáles son condiciones necesarias en el grafo para que esto ocurra?
Si no se acuerdan del pseudocódigo lo pueden buscar o usar este que encontré [en este link](https://mat.uab.cat/~alseda/MasterOpt/AStar-Algorithm.pdf).
Saludos,
Jaime

**Comment by tomytable** [comment]
Gracias!

**Comment by Jamidd** [comment]
Hola, 

> ¿Considero que expandir el nodo es ver con quienes está conectado? Y en ese caso, considero que estoy expandiendo el nodo inicial (h=4)? O empiezo a contar los expandidos con los nodos h=3 y h=3?

A muy grandes rasgos, en A* tu partes con un nodo inicial
- lo expandes y agregas sus 'hijos' a open de ser pertinente (expansión 1)
- elijes un nodo de open bajo cierto criterio
- lo expandes y agregas sus 'hijos' a open de ser pertinente (expansión 2)
- elijes un nodo de open bajo cierto criterio
- lo expandes y agregas sus 'hijos' a open de ser pertinente (expansión 3)
- ...
Lo que se pide son los criterios para que el algoritmo solo haga dos expansiones y entregue la solución. 

Espero quede un poco mas claro.
Saludos, 
Jaime.
