### ISSUE TITLE
[Tarrea 1]2.5: El minimize debe entregar soluciones con la misma cantidad de nodos iluminados?

### ISSUE THREAD

**Issue by gsalinas0** [UC-IIC2613/Syllabus#76]
Hola. Entiendo que al intentar trabajar con el `minimice`, le estamos diciendo a clingo que, dada una condición, minimice la cantidad de nodos que hay que iluminar. Mi pregunta es... para todos los modelos que debise dar clingo, ¿en todos debería indicarse que se iluminen la misma cantidad de nodos?
Pregunto porque en lo que tengo yo, para este grafo:
![image](https://user-images.githubusercontent.com/68198662/116290886-f6d8c600-a761-11eb-9ace-9b00215051b3.png)
clingo me arroja dos opciones, que son:
![image](https://user-images.githubusercontent.com/68198662/116291239-5a62f380-a762-11eb-9760-e35f253d5910.png)
En el ejemplo del libro, `maximize` entregaba un listado de posibilidades, desde el peor hasta el mejor optimizado, asi que asumo que para este caso debiese pasar lo mismo. O debemos incluir en el modelo solo aquellos modelos con la menor cantidad de nodos iluminados, que para este caso serían solo 2?
También encuentro raro que clingo solo entregue la solución de iluminar `a` y `b` como la única más optima, ya que por ejemplo si se iluminan `f` y `c`, también se cumpliría la condición de llegar desde cualquier nodo hacia cualquier nodo pasando únicamente por caminos con a lo más una calle sin iluminar.

**Comment by gsalinas0** [comment]
Con respecto a la última duda, hice la prueba en clingo de utilizar `#minimize` por un lado, e iluminar otros nodos manualmente. Me retornó esto:
(`par_listo(X,Y)` significa que entre los nodos X e Y hay un camino con a lo más una calle a oscuras)
![image](https://user-images.githubusercontent.com/68198662/116294447-fb06e280-a765-11eb-8b66-f9c05b7b5374.png)
Como se ve tanto la opción entregada por el #minimize como la que plantee yo, hacen que todos los nodos tengan conexión con todos, pero clingo solo me entrega una de ellas (en la que se ilumina 'a' y 'b').
El código que se entregue finalmente debe contener todas las soluciones optimas? o con que se entregue una basta?

**Comment by FeBalla** [comment]
Te dejo una serie de comentarios a continuación:

- Para el ejemplo que muestras, si se trata de que haya a lo más una calle oscura entre cualquier par de nodos, entonces el óptimo se alcanzaría tan solo con que se encienda un único nodo cualquiera. 
- Tanto `#minimize` como `#maximize` se pueden entender como sentencias derivadas de un problema de optimización que busca minimizar/maximizar la cantidad de apariciones de un predicado en el modelo. Por lo tanto, entendiendo que se trata de un problema de optimización, el **valor óptimo** es único (en este caso cuántas veces aparece un predicado en el modelo), es decir, no podría haber un óptimo donde el predicado aparezca 2 veces y otro en el que aparezca 3. **OJO**👀: esto no significa que no puedan haber múltiples óptimos. Con esto me refiero a que pueden haber otros modelos óptimos donde, por ejemplo, la disposición o aparición de otros predicados (o incluso del que se optimiza) sean diferentes, pero se debe respetar que la cantidad de apariciones sea igual. En resumen, si en este caso basta con que haya 1 nodo iluminado, todos los óptimos tendrán 1 nodo iluminado, ya sea el nodo `A` o `B`, etc.
- Finalmente, debería bastar con que presentes uno de los posibles óptimos 😄
