### ISSUE TITLE
[Tarea 1] [Parte 4] Shoot action

### ISSUE THREAD

**Issue by joaquinhernandezg** [UC-IIC2613/Syllabus#78]
Es obligatorio que shoot se haga sobre una celda adyancente? No sale explícitamente en el enunciado y el programa tampoco lo prohibe.

**Comment by jmopaso** [comment]
Hola!

No es obligatorio, puedes disparar desde cualquier posición siempre y cuando estés seguro que ahí hay un wumpus y cumplas con el principio de benevolencia.

Saludos!
