### ISSUE TITLE
[Pregunta 2]

### ISSUE THREAD

**Issue by ignaciovilla** [UC-IIC2613/Syllabus#79]
Me surge la siguiente duda, puedo asumir que no necesito tener un camino de la forma "camino(a,a,k)" con k <= 0- ya que no le veo la utilidad de definir un camino que vuelva a si mismo.
Muchas gracias.

**Comment by dtgazmuri** [comment]
Hola

Si es que k <= 0, en realidad no se tiene un camino, pues no se recorre ningún arco. Así, no tendría sentido que `camino(A,A,0)` estuviera en el modelo (creo que esa era tu duda).

Saludos

**Comment by ignaciovilla** [comment]
Perdón, era k >= 0.

**Comment by dtgazmuri** [comment]
En ese caso, tu modelo sí debería incluir `camino(A,A,k)`, pues el camino efectivamente existe. No es trivial decirlo, pues el hecho de que esto esté presente en el modelo significa que el grafo es cíclico.

**Comment by ignaciovilla** [comment]
Perfecto, gracias
