### ISSUE TITLE
[Tarea 1] Duda Parte 2 Pregunta 1

### ISSUE THREAD

**Issue by CataAlamos** [UC-IIC2613/Syllabus#8]
Hola, cree un ciclo en arco(a,e) y arco(e,a) pero el output me da lo mismo que cuando no tengo ciclos. ¿Debe cambiar el output y en ese caso cual es el error de laforma que defini ciclos?
<img width="770" alt="Screen Shot 2021-04-11 at 15 07 38" src="https://user-images.githubusercontent.com/62016215/114317771-ab72b680-9ad7-11eb-992c-ae9eed5815da.png">

**Comment by aamedinaj** [comment]
Hola, habían unos cuantos errores en el ejemplo que van a ser corregidos (se va a subir una nueva versión del enunciado). Con eso arreglado te debería resultar el experimento.

🦊
