### ISSUE TITLE
[Tarea 1] Parte 4.2 - Sentir la briza 

### ISSUE THREAD

**Issue by baosse** [UC-IIC2613/Syllabus#81]
Holaa, tengo una duda con implementar los movimientos cuando hay pozos cercanos. 

Cuando se ponen pozos cercanos solo retorna la sensación de briza una sola vez, por lo que el pozo podría estar a pualquiera de sus lados, pero si tengo muchos pozos cerca, como sabrá de qué pozo viene la brisa? me surgió la duda porque al colocar al agente en la posición (3,2) en map.txt me toma el primer pozo como el que se encuentra en (2,3) y el próximo paso que ejecuta es ir al lado contrario, que es donde se encuentra el otro pozo.
Mi duda es si esto está puesto apropósito con el fin de que dejemos que el problema no se puede resolver o se pierde o si debemos hacer algo para que nos retorne los dos sense_breeze(x,y).

**Comment by FeBalla** [comment]
Hola! Bajo el caso que tu mencionas, si te encuentras rodeado, por ejemplo, por 2 pozos, entonces solo puedes moverte a una celda si tienes una certeza **demostrable** de que aquel movimiento es seguro. Me explico: si estás en una celda `(x,y)` y sientes una brisa, entonces debe haber un pozo en una o más de las celdas vecinas. Por lo tanto, si yo cuento con **tan solo esa información**, entonces es claro que no podría realizar ningún movimiento, ya que no tengo certeza de seguridad para ninguno de ellos. Sin embargo, durante el transcurso del juego vas adquiriendo información que te permita saber que en ciertas celdas no puede haber un pozo y, en consecuencia, sean seguras.

Dicho esto y para responder a tu pregunta, si estás en una celda, sientes una brisa y **no tienes ningún otro tipo de información que te permita saber de la ubicación de el(los) pozo(s)**, entonces en ese punto tendrías un programa sin solución. Eso se relaciona directamente a las reglas IV y VIII que aparecen en el enunciado. Mucho ánimo y éxito! 😄

**Comment by baosse** [comment]
Muchas gracias!
