### ISSUE TITLE
[Tarea 1] Monotonía

### ISSUE THREAD

**Issue by beatrizacuna** [UC-IIC2613/Syllabus#82]
Holaa 😺  perdón lo pava pero en las clases no encontré la definición de monotonía y busqué en google pero prefiero asegurarme de que es la correcta, alguien podría definirla aquí? Graciaaas 💓

**Comment by FeBalla** [comment]
En particular para la tarea cuando te piden demostrar la monotonía se refieren exactamente a lo que viene después en el enunciado:

"_Específicamente, demuestra que si Π y Π0 son dos programas tales que Π ⊆ Π0 y M es un modelo de Π, entonces existe un modelo M0 de Π0 tal que M ⊆ M0_"

No es necesario que te confundas con el concepto en sí, sino que debes demostrar eso 😄 . Mucho ánimo!

**Comment by beatrizacuna** [comment]
Yaa gracias 😄  y otra duda, puedo decir que existe el modelo M' para demostrar que M ⊆ M' ? o debo demostrar primero que existe el modelo M'?
