### ISSUE TITLE
[Tarea 1] penalidad atraso

### ISSUE THREAD

**Issue by jac-34** [UC-IIC2613/Syllabus#83]
Hola, ayer se me olvido pushear una parte de la pregunta 3 y queria ver cual es la penalidad de pedir que te corrijan con atraso, para ver si vale la pena subir lo que se me olvido y aceptar el descuento o dejarlo asi no mas.

Gracias

**Comment by Dnpoblete** [comment]
Hola@jac-34, el descuento es de 5 décimas por día de atraso con un máximo de 1 semana, por lo que podrías entregar hasta las 23:59 de hoy y tener un descuento de 5 décimas. Si deseas entregar tarde y que consideremos los cambios que realizaste fuera del plazo, debes enviar un correo a iic2613@ing.puc.cl como se notificó en el último anuncio enviado por canvas hasta hoy a las 18:30. De lo contrario se considerará lo que entregaste hasta ayer a las 23:59.
