### ISSUE TITLE
[Ayudantía 4] Pregunta demostración de cota

### ISSUE THREAD

**Issue by bjbarias** [UC-IIC2613/Syllabus#84]
Hola! Estaba revisando la ayudantía 4, y no me quedó claro lo que pasa en el minuto 19:45:
<img width="427" alt="Screenshot_7" src="https://user-images.githubusercontent.com/37160829/117720656-edf9e280-b1ac-11eb-932d-8cd57919dbb9.png">

¿Qué es el s*? Creo que no se define.

Gracias!

**Comment by fivaldivia** [comment]
Hola! El s* viene de g*(s) la cual es la distancia de el estado inicial a un estado óptimo, el cual sería s*. Avísame si quedó claro!

**Comment by bjbarias** [comment]
Hola! No me queda claro. No es goal el estado optimo? o qué es un estado óptimo.
