### ISSUE TITLE
Video Parte 2 [Tarea 3]

### ISSUE THREAD

**Issue by antoniaalcayaga** [UC-IIC2613/Syllabus#85]
Hola, 

Me surgió la duda si en el video podemos asumir que quienes lo ven ya conocen la heurística de distancias manhattan y si debemos explicar el algoritmo (que sale en el paper) con que se calcula la heurística de conflictos lineales o solo hay que explicar como se calcula con los ejemplos para las distintas situaciones.

Gracias!!

**Comment by jmopaso** [comment]
Hola! 

Sobre tu primera duda, como dice en el enunciado ```la idea es que el video pueda ser comprensible para una persona que le hayan enseñado A* con el ejemplo del puzzle```, se entiende por esto que quienes ven el video al menos saben de heurísticas, te recomiendo que el enfoque que le des a tu video sea similar a como lo enfrentan en el _paper_ que hay que leer en esta parte, de todas formas si te quieres referir a la distancia manhattan puedes hacerlo, pero no te recomiendo entrar en tanto detalle, más que nada céntrate en los 4 objetivos que se señala en la pregunta. Sobre tu segunda duda, uno de los objetivos que te piden es ```Que explique la idea de cómo se calcula``` por lo que si deberías explicarlo (al menos la idea).

De todas formas el video tiene que ser concreto y abordar sólo los temas que se piden en el enunciado.

Saludos!
