### ISSUE TITLE
Tarea 2 - Parte 2.1 a) Costo de un estado a otro

### ISSUE THREAD

**Issue by vchadwick** [UC-IIC2613/Syllabus#86]
Hola! Tengo una duda sobre el costo de un estado s a otro s', denotado como c(s,s') en la definición de consistencia. ¿Ese valor necesariamente va a ser 1? Porque en definitiva, para un grafo cualquiera podriamos definir el costo de ir a un estado a otro como cualquier valor constante C >= 0.

**Comment by aamedinaj** [comment]
Hola
No es necesariamente 1 en general, pero en particular para el problema del puzle tiene sentido que todos los movimientos van a tener el mismo costo (a los vecinos), y por simplificación se toma costo = 1. Si quieres hacer una respuesta más general, puedes, pero no ganas mucho 🤔 .

🦊
