### ISSUE TITLE
[Tarea 2][Pregunta 1] Duda criterio de desempate

### ISSUE THREAD

**Issue by milosoria** [UC-IIC2613/Syllabus#87]
Hola! Tengo una pequeña duda en el criterio de desempate que se describe en el enunciado 
>Una buena implementación, al tener dos nodos en la Open con el mismo valor f (es decir, dos nodos n1 y n2 tales
que f(n1) = f(n2)), debiera preferir para expansión a aquel que tiene el mayor valor g
Por qué se toma el nodo con mayor g y no al revés? Pensaría que el desempate lo gana el nodo con menor h y/o menor g.
De antemano, gracias!!

**Comment by diegomendieta** [comment]
Hola @milosoria, si entendí bien, la duda que tienes es parte de la pregunta que debes responder. En todo caso, piensa que si dos nodos tienen un mismo f, entonces a mayor g, menor h. La pregunta es: qué significa que un nodo tenga mayor g que otro y, por qué, en ese caso, me conviene elegirlo?
