### ISSUE TITLE
[Tarea 2][Pregunta 1] Parte 4

### ISSUE THREAD

**Issue by josejimenezp** [UC-IIC2613/Syllabus#88]
Hola! En el enunciado dice que modifiquemos el archivo astar, pero me hace más sentido modificar el archivo binary_heap. Es necesario modificar el astar o se puede hacer modificando el otro archivo? Gracias!

**Comment by SarahEverke** [comment]
Hola, para resolver la pregunta no es necesario modificar el archivo `binary_heap`.

**Comment by knight-who-says-ni** [comment]
Pero podemos modificarlo?? Yo ya lo hice modificando `binary_heap` y me hace mucho mas sentido hacerlo de esa forma... Gracias!!

**Comment by DiegoEmilio01** [comment]
Tengo otra duda, en caso de que sea obligatorio hacerlo en `astar` yo utilicé como API las funciones `extract` e `insert` pero se demora muchísimo, ¿se deben usar funciones mas básicas implementadas en dicho módulo?

**Comment by SarahEverke** [comment]
Hola, para que tu implementación sea más eficiente podrías definir la prioridad de forma que la cola de prioridades se ordene automáticamente usando g+h y luego por -g.

**Comment by DiegoEmilio01** [comment]
Pero para hacer eso bien necesitaría hacerlo en `binary_heap`

**Comment by SarahEverke** [comment]
Hola, no es necesario. Puedes modificar cómo se está calculando `fvalue`.
Saludos

**Comment by DiegoEmilio01** [comment]
Aaaaah creo que ya entendi, muchas gracias

**Comment by BernaValdivieso** [comment]
Hola, a mí no me quedó tan claro. Yo tenía la misma idea de ir sacando y metiendo nodos en el heap binario, pero me pasó lo mismo de que no era eficiente. Mi duda es que si modifico el `fvalue`, al final no estoy comparando nada, estoy modificando el f según una característica que encuentro importante, para que ese f sea mejor o peor de lo que debería, y así esté mejor o peor en la prioridad del heap. Esa es la idea? Y otra cosa, esta mejora se supone que debería ser en todo o se puede dar el caso por ejemplo, de que tenga mejor tiempo, menos expansiones, pero mayor costo total con mi implementación?

**Comment by emyskog** [comment]
A mi me pasa eso, es más caro pero es más raído y se expande menos. Al final que queremos mejorar?

**Comment by SarahEverke** [comment]
Hola, la idea es que redefinas cómo se está calculando `fvalue` y que la cola de prioridades se ordene automáticamente con ese nuevo valor. 
Una mejora debiese ser que disminuya la cantidad de de expansiones generadas al implementar la regla de quiebre de desempates. Aunque, pueden haber casos que esto no se cumpla.

**Comment by emyskog** [comment]
Pero puede aumentar el costo?

**Comment by szabala** [comment]
@SarahEverke 
> Hola, la idea es que redefinas cómo se está calculando `fvalue` y que la cola de prioridades se ordene automáticamente con ese nuevo valor.

Me queda una duda aún con esta respuesta. Si cambiamos como se calcula el fvalue y reordenamos el heap no estamos resolviendo el problema de los empates no? simplemente estamos usando otro fvalue para la prioridad del heap, pero este último no revisa cuando los fvalues sean iguales para ordenarse.  Además, si los empates ocurren cuando dos nodos tienen el mismo fvalue, ¿como identificamos los empates si redifinimos como se calcula el fvalue?

**Comment by SarahEverke** [comment]
Lo que queremos es que al tener dos nodos en Open con el mismo valor de f, se prefiera el nodo que tiene el mayor valor de g o menor h. Por ejemplo, si redefines tu `fvalue` de tal forma que use como primer criterio g+h y luego -g, estarías prefiriendo los nodos que tienen un mayor valor de g frente a los nodos que tienen un mismo f pero un menor g.
