### ISSUE TITLE
[Tarea 2][Pregunta 1] Critero de desempate

### ISSUE THREAD

**Issue by gustavobarrezueta** [UC-IIC2613/Syllabus#89]
Hola! Sé que esta duda la trataron en una issue anterior pero lo vuelvo preguntar porque tenía la misma duda y la respuesta no la resolvió.
En el enunciado se dice que el criterio de desempate que debemos ocupar es expandir aquel nodo que tenga mayor g. Además, debemos encontrar por qué lo anterior "tiene sentido", pero me pasa que lo contrario me hace sentido jajaja. Mi pregunta es, es posible que el enunciado esté mal y en vez de decir mayor g y menor h quisieron decir lo contrario?
De verdad, me ayudaría harto si me pueden ayudar porque es la primera parte de la pregunta.
Gracias!

**Comment by diegomendieta** [comment]
Hola, voy de nuevo. 

El enunciado está bien. Acabo de buscar y hay preguntas en stackoverflow que pueden ser de ayuda; te recomiendo que busques por ahí, a ver si se te aclara el panorama. La pregunta quiere que contestes por qué, en caso de empate, conviene más como criterio de desempate la función g(n) (que corresponde al costo real del camino recorrido hasta n) que h(n) (que corresponde a la (sub)estimación de la distancia que falta para llegar al nodo objetivo).

Si tampoco queda claro, por favor sigue comentando hasta que así sea.
