### ISSUE TITLE
[Tarea 1] P1.2 sistema computacional

### ISSUE THREAD

**Issue by Aloncarrasco** [UC-IIC2613/Syllabus#9]
En la Parte 1 pregunta 2, se nos pide que especulemos sobre que sistema computacional sería necesario implementar para que un programa en lógica realice analogías y mi pregunta es a que se refiere con "sistema computacional", tendríamos que describir el código que permitiría esto? o las características que tendría ese sistema?

**Comment by FeBalla** [comment]
Hola! La pregunta no es tanto de escribir un código, sino que **reflexionar**  y **describir** sobre qué herramientas relacionadas al ASP y lo que hemos visto en el curso pueden ser de utilidad. En esta _[issue](https://github.com/UC-IIC2613/Syllabus/issues/4)_ se da una respuesta en más detalle. La pregunta es bastante abierta mientras argumenten, así que tranquil@s!

**Comment by Aloncarrasco** [comment]
gracias
