### ISSUE TITLE
[Tarea 2][Pregunta 1] Inducción del video

### ISSUE THREAD

**Issue by gsalinas0** [UC-IIC2613/Syllabus#90]
Hola. Estoy viendo el video que se menciona en la pregunta 1.2, pero no logro entender la inducción que hace el profe cerca del minuto 2:30. Me lo podrían por favor explicar (de preferencia con peras y manzanas)?

Saludos

**Comment by gsalinas0** [comment]
Tampoco entiendo este reemplazo que hace el profesor:
![image](https://user-images.githubusercontent.com/68198662/118594017-b247b580-b776-11eb-9040-7ec1c52d58b5.png)
Me llama la atención que _s_ tenga un f menor que _s*_, que se se trata de un nodo (en la open) que forma parte del camino óptimo hacia _sgoal_, lo que me haría pensar que debería tener un f menor que cualquier otro nodo en la open. Para mi se me hace una contradicción, o no se si estoy entiendo mal la notación

**Comment by diegomendieta** [comment]
Hola, @Gsalinas1506. Lo que se intenta demostrar es que en todo momento, durante la ejecución de Weighted A*, hay un estado en Open que: está en el camino óptimo; y que el costo registrado hasta alcanzarlo corresponde a la distancia real desde el inicio.

La inducción parte presentando el caso base, considerando el nodo de inicio. En este se cumple trivialmente que está en un camino óptimo hacia el nodo objetivo, y que su costo óptimo es igual al costo registrado (g) hasta llegar a él (cero).

Luego de esto, se presenta la hipótesis inductiva, en que se asume que las propiedades anteriormente mencionadas se cumplen en una iteración arbitraria; es decir, en una iteración k, existe s* en Open que pertenece a un camino óptimo y que el g(s*) registrado corresponde al costo real para llegar a él. Se busca demostrar, entonces, que lo mismo ocurre en la iteración k+1.

Por un lado, si no se expande s*, entonces s* se mantiene en Open, y las propiedades se mantienen. Por otro lado, al estar s* en el camino óptimo, al expandirlo tenemos que encontrar obligatoriamente un nodo s' que pertenezca también al camino óptimo (y agregarlo a Open) y, como este fue encontrado por s*, entonces el costo de ir de s* a s' debe corresponder al mínimo de todos los costos para alcanzar s' desde s*. De esta forma, queda demostrado el lema presentado.

En relación a la segunda pregunta, el nodo s que se extrae de Open para expandirlo corresponde siempre al nodo que tenga menor f dentro de todos los nodos de Open. Esto es lo que se presenta en la primera línea de la foto que subiste. En particular, y como demostramos anteriormente que siempre hay un nodo s* en Open, entonces f(s) tiene que ser menor o igual a f(s*). 

Vale la pena mencionar que lo que dices de que cada nodo que forma parte del camino óptimo debería tener un f menor que cualquier otro nodo de Open es incorrecto. Imagínate el caso en que utilizaras una heurística h(s) = 0 para todo s. En ese caso, un nodo cercano al inicio que no corresponde al camino óptimo tendría un valor de f pequeño, y un nodo cercano al final perteneciente al camino óptimo tendría un valor de f grande.

Espero haya podido aclarar tu duda. Éxito!

**Comment by gsalinas0** [comment]
Yaa perfecto, ya entendí. Muchas Graciass
