### ISSUE TITLE
[Tarea 2][Pregunta 1] A* o Weighted A*

### ISSUE THREAD

**Issue by josejimenezp** [UC-IIC2613/Syllabus#92]
Hola, me entró la duda si estamos implementando A* o Weighted A*, ya que hay preguntas que se hacen sobre uno y otras sobre otro. Por otro lado, el código que nos entregan es de A* (que se nota en la función fvalue que no toma en cuenta el weight) pero también tiene la opción de cambiarle el peso, entonces estoy un poco confundido 😕

**Comment by diegomendieta** [comment]
Hola, implementa Weighted A*. Recuerda que A* es un caso particular de Weighted A*, por lo que si luego necesitas correr A*, basta con usar w=1.
