### ISSUE TITLE
[Tarea 2][Pregunta 1] Exponencialmente más ineficiente

### ISSUE THREAD

**Issue by DiegoEmilio01** [UC-IIC2613/Syllabus#93]
Hola, me gustaría saber a que se refiere con "exponencialmente más ineficiente". ¿Es esto que de O(n) pasa a O(2**n)? En ese caso, ¿pasar de O(1) a O(n) cuenta como exponencialmente más ineficiente? Por ahora, se me ocurre solo ese último caso como ejemplo.
Muchas gracias de antemano!

**Comment by fivaldivia** [comment]
Hola Diego, exponencialmente más ineficiente significa que usando la regla de empates debiese demorar O(e^n). Como dices en tu ejemplo, si tienes O(n) en caso normal en el peor caso, este debiese pasar a O(e^n).

**Comment by DiegoEmilio01** [comment]
El tema es que encontré en fuentes externas que el peor caso es `O(b**d)` con `d` el largo de la solución. Tratando de no hacer mucho spoiler, ¿tiene que ver la ayuda del enunciado con dicha información?

**Comment by fivaldivia** [comment]
No se a qué te refieres con d como el largo de la solución, pero si es relacionado a la profundidad del problema estás por buen camino!

**Comment by Huasito-Appel** [comment]
Hola! con describir el problema y dar a entenderlo es suficiente? o debo demostrar que cumple la ineficiencia?
