### ISSUE TITLE
[Tarea 2][Pregunta 2.1b] Demostración con palabras

### ISSUE THREAD

**Issue by gustavobarrezueta** [UC-IIC2613/Syllabus#94]
Hola! Tengo una duda. En este pregunta la demostración que hice fue con palabras, a partir de algo que noté que ocurre en el algoritmo. Mi pregunta es si puede estar bien esa demostración con palabra o si necesariamente debe haber una demostración matemática con desigualdades y operaciones?
Gracias.

**Comment by SarahEverke** [comment]
Hola, no hay problema que tu demostración sea con palabras. Lo importante es que argumentes adecuadamente. Sin embargo, hacer una demostración matemática podría ser más sencillo.

**Comment by gustavobarrezueta** [comment]
Lo hice con palabras porque no se me ocurre la demostración matemática jaja pero entiendo, gracias.
