### ISSUE TITLE
[Tarea 2][Problema 2.2] Archivos a utilizar 

### ISSUE THREAD

**Issue by gustavobarrezueta** [UC-IIC2613/Syllabus#95]
Hola!
En esta pregunta se nos pide implementar la clase LightPuzzle. Mi pregunta es qué tanto código de la Parte 1 podemos reutilizar para hacer este problema.
Gracias.

**Comment by fivaldivia** [comment]
Hola, claro que pueden utilizar todo el código que tienen a mano para hacer las preguntas de la tarea, por lo que puedes utilizar el de la Parte 1 para la Parte 2.

**Comment by gustavobarrezueta** [comment]
Genial. Muchas gracias.
