### ISSUE TITLE
 [Tarea2] [Parte 1] [Pregunta 1]

### ISSUE THREAD

**Issue by JupaOlivares** [UC-IIC2613/Syllabus#97]
> explica por qu´e la demostraci´on del video, sigue funcionando.

Con la demostración del video se refieren a la del profesor Jorge Baier en Youtube? O en otras palabras nos piden demostrar poque teniendo (o no) la regla mencionada en el enunciado se mantiene la w-suboptimalidad?

**Comment by diegomendieta** [comment]
Hola, lo que dices es equivalente. Explica por qué la demostración del profesor Baier en Youtube se mantiene al agregar la regla. Recuerda que el video demuestra que Weighted A* consigue soluciones, como tú dices, w-subóptimas, y que A* es un caso particular de Weighted A*, con w=1.
