### ISSUE TITLE
[Tarea 2][Nuevo archivo]

### ISSUE THREAD

**Issue by Huasito-Appel** [UC-IIC2613/Syllabus#98]
Hola! no tengo muy claro a que corresponden los valores de la primera columna del nuevo archivo, ligth_problems.txt, por si alguien me lo puede esclarecer.
gracias!

**Comment by jmopaso** [comment]
Hola!

Los valores de la primera columna son sólo para enumerar los problemas, no tienen ninguna incidencia en el puzzle. Podrías ver el método `load_problems` del archivo `test_preferred_astar` para asegurarte de lo que te digo.

Saludos!
