### ISSUE TITLE
[Tarea 2] [Pregunta 2.2] Usar puzzle.py como base

### ISSUE THREAD

**Issue by JadrinaDA** [UC-IIC2613/Syllabus#99]
Hola! Para la pregunta 2.2 me pregunto si puedo usar el código de puzzle.py como base para hacer mi clase LightPuzzle o si tengo que hacer todo de cero. Tengo que programar algo además de las dos funciones que me piden? 
Muchas gracias,
Jadrina

**Comment by fivaldivia** [comment]
Hola, sí puedes usar/reutilizar todo el código que se da para la tarea según estimes conveniente. Sólo programa lo que se pide en enunciado y lo que te ayude para lograr el objetivo que se pide.

**Comment by JadrinaDA** [comment]
Ok, muchas gracias!
